### ISSUE TITLE
FIND_FORTRAN not defined on Ubuntu

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ISIS3#234]
Using the conda dependencies, configuration fails with a `FORTRAN_LIBRARY` not defined error.  Both the conda env and the underlying OS have libgfortran.so.3 installed.  It looks like the error is being caused within the [FindCholmod.cmake](https://github.com/USGS-Astrogeology/ISIS3/blob/cmake/isis/cmake/FindCholmod.cmake#L29) script.

**Comment by twilson271828** [comment]
I'm going to look into this this weekend.  Things have been a little busy with the IPCE sprints.

**Comment by Kelvinrr** [comment]
The find_library call for libgfortran has issues because CMake by default looks for `<LIBRARY>.so` but libgfortran tends to install itself as `libgfortran.so.<VERSION>`. In other words, because it ends in .3 instead of .so the search fails. So far the solution seems to simply delete the line since it's unnecessary to manually search for libgfortran since we want to use the version that ships with gcc.

**Comment by Kelvinrr** [comment]
This should no longer be an issue after #298
