### ISSUE TITLE
Builds to remove with 3.7.0 release

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ISIS3#2852]
This issue is to collect a list of the builds that we can remove once the 3.7.0 release is released.

- CaSSIS custom build from 3.6.x

**Comment by jlaura** [comment]
hayabusa2

**Comment by SgStapleton** [comment]
Did we decide how many older versions of public releases we wanted to host on anaconda?

**Comment by SgStapleton** [comment]
Also, is it worth collecting the .tar.bz files locally of all builds that have been pushed to anaconda...? This would really just be a just-in-case safety measure. But, I have been thinking about how individuals are pushing these files up and there is no standard local location in case the same build needs to be pushed back up quickly without needing to be remade. Like if we delete the hayabusa2 build after the 3.7.0 release, but then the new release does not work for them for whatever reason and we now have to rebuild the conda build from scratch - hoping to get it the exact same as who knows how that particular individual built it in the first place (what branch was used, what environment was used, etc. etc.). What if that branch has since been deleted!?

**Comment by jlaura** [comment]
:+1: I like the idea of keeping those builds some place. I would love to do that outside of the conda install since we will inevitably `conda clean --all` at some point.

**Comment by SgStapleton** [comment]
So we will just need to decide on where these need to go and I will add that information to the wiki page for building with conda-build. :-)

**Comment by jlaura** [comment]
@all Can I remove the following from anaconda.org with the 3.7.0 release?

conda install -c usgs-astrogeology/label/cassis isis3 
conda install -c usgs-astrogeology/label/hayabusa2 isis3 
conda install -c usgs-astrogeology/label/RC isis3

**Comment by SgStapleton** [comment]
The mission builds do not currently exist in our backup. Should I download those just to have a copy, or do we care enough about custom mission builds...? The RCs are already backed-up in our /work/projects/conda-bld dir.

**Comment by jlaura** [comment]
@SgStapleton I think backing these up makes a ton of sense. Just because, we would like to have a record. Once they are backed up, I will remove them unless someone else weighs in.

**Comment by jessemapel** [comment]
As long as it's reversible if a mission wants to roll back, I am okay with this.

**Comment by SgStapleton** [comment]
I will go ahead and back-up everything that is on there now unless anyone has any objections.

**Comment by SgStapleton** [comment]
All of the isis3 packages out on our Anaconda channel has been backed-up. Feel free to clean-up anything you wish on there.

**Comment by jlaura** [comment]
This is done.
