### ISSUE TITLE
gllssi2isis QIODevice warning message

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#3199]
**ISIS version(s) affected**: 3.6.2

**Description**  
The following message appears when ingesting Galileo SSI images using gllssi2isis:

QIODevice::read (QFile, "/pds_san/PDS_Archive/Galileo/SSI/go_0019/redo/e4/europa/c037466/7300r.lbl"): device not open

**How to reproduce**  
gllssi2isis from=/pds_san/PDS_Archive/Galileo/SSI/go_0019/redo/e4/europa/c037466/7300r.lbl to=7300r.lev0.cub

**Possible Solution**  
Make the message go away after determining everything is indeed ok.

**Additional context**  
This is primarily an FYI as PDS files are ingested into ISIS as expected.  The QIODevice message only goes to screen and is not captured in the print.prt.

**Comment by jlaura** [comment]
I believe that this is due to the fact that the file is symlinked. A solution would be to hide the warning as this is expected behavior from `QIODevice::read` (as far as I can tell).

**Comment by paarongiroux** [comment]
This is happening due to a method called fixPVL where the input file is opened and checked for an open comment to be fixed before anything is done on the file. In order for this to happen, the method needs read/write permissions on the file, so this warning occurs when given a path name to a file that you don't have write permissions to. It doesn't affect the program unless the input file is one of the files that has an open comment. In the case that this warning message is present, the fixPVL method is completely useless since the file can never be opened and therefore the open comment in the file can't be resolved. A solution could be to check if the file can be written to before running the fixPVL method, I'm just not sure if this would be appropriately addressing the issue or just suppressing it.
