### ISSUE TITLE
no incons in qview and other isis3 guis

### ISSUE THREAD

**Issue by afrigeri** [DOI-USGS/ISIS3#3233]
**ISIS version(s) affected**: 3.6.0

**Description**  

Hi,

installing isis3 3.6.0 via miniconda on OSX (10.14.1), activating the environment, the isis modules work ok.  When firing up the GUIs, they show up fine but they are missing the icons. 
maybe I have to check a specific variable indicating the qt dir? 

Alessandro

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by jlaura** [comment]
@afrigeri Would you mind testing our RC2 release candidate (`conda install -c usgs-astrogeology/label/RC isis3`) to see if the behavior is present there? This is 3.7.0 candidate that we will officially release at the end of the month, so if the issue is also present there we definitely want to fix it. If the release candidate is working, would it be possible to upgrade?

Also, @thareUSGS weren't you seeing a similar issue on windows? What was the solution there?

**Comment by jessemapel** [comment]
@afrigeri Do you have the base data area downloaded? All of the icon images are stored in there. There's instructions for the data area on our [readme](https://github.com/USGS-Astrogeology/ISIS3#the-isis3-data-area). You don't need the entire data area, just the [base](https://github.com/USGS-Astrogeology/ISIS3#partial-download-of-isis3-base-data-required).

**Comment by afrigeri** [comment]
Thanks @jlaura @jessemapel!  Rsyncing the base data and setting ISIS3DATA path variable did the trick - now the icons are in place in qview and other modules.
