### ISSUE TITLE
Check wget differences in Isis kernel update scripts

### ISSUE THREAD

**Issue by krlberry** [DOI-USGS/ISIS3#3260]
**Description**  
Check to see if wget agruments / flags outside of the acceptance list having meaningful differences between the “standard scripts” Note: Should have robots=off for all wgets

**Comment by kaitlyndlee** [comment]
Dawn - No -nd or -r flag, but there are not subdirectories we are trying to pick up so shouldn't be a problem. No diff before makedb for ck and spk (5423 db files under ck directory)

Mex uses -R flag for one of the wget calls. Does not have -nd or -r so that they do not pick up any kernels from the former_versions directory, but we can add an exclude-directory flag and include -r and -nd.

MRO - Has some -R flags

Odyssey - Has some -R flags

**Comment by acpaquette** [comment]
What are the -R flags?

**Comment by kaitlyndlee** [comment]
used to reject files that match a regex

**Comment by acpaquette** [comment]
The -R flags seems like something we can just pass in, is there any reason that dawn isn't diff before making the database?

**Comment by krlberry** [comment]
@acpaquette @kdl222 The missing diff in dawn looks like a bug to me and should be added in where it is in all the other files. dawn has 5423 kernel database files and there is no need for that.
