### ISSUE TITLE
caminfo - writing null coordinate values for projected images

### ISSUE THREAD

**Issue by dbolan** [DOI-USGS/ISIS3#3364]
**ISIS version(s) affected**: 3.6.0, 3.7.1, 3.8.0

**Description**  
`caminfo` is attaching null values to LowerLeftLongitude, LowerLeftLatitude, UpperRightLongitude, and UpperRightLatitude. This is a problem because it may be causing ASP's `stereo` to fail when loading the camera model.

**How to reproduce**  
OS: Ubuntu 18.04 64-bit
```sh
lronac2isis from=M152445210LE.IMG to=l0.cub
spiceinit from=l0.cub
lronaccal from=l0.cub to=l1.cub
cam2map from=l1.cub to=l2.cub
caminfo from=l1.cub to=l1.caminfo
caminfo from=l2.cub to=l2.caminfo
```

For me, `l1.caminfo` shows all fields and `l2.caminfo` has null values for LowerLeft* and UpperRight* coordinates.
*EDIT:* Comparing to the documentation in [`caminfo.xml`](https://github.com/USGS-Astrogeology/ISIS3/blob/af857368a3adadd6870ee551c91cbfd4ea60ac1b/isis/src/base/apps/caminfo/caminfo.xml), it also seems like the Mapping, Camstats, and Polygon groups are missing altogether as well.

**Additional context**  
Other things I have tried:
* I was running with the SPICE web service at first, but I eventually downloaded all the ancillary info and tried again
* Tried with several other images, including ones that don't cross the prime meridian and ones that I know have worked for other people
* Images near the pole with polar stereographic map template
* Reinstalling conda and isis3
* Using cubes from processed through PILOT, which have no null values but still lack the Mapping, Camstats, and Polygon groups

I wasn't able to reproduce this issue on a different computer with ISIS 3.7.1. I'm still trying to figure out what the difference between the two setups, haven't seen anything strange yet. The machine I'm having this problem on is running a nearly new installation of Ubuntu, so I haven't even really had a chance to do anything weird with my setup.

Further discussion with details of everything I've tried can be found [here](https://astrodiscuss.usgs.gov/t/asp-stereo-with-spice-web-service/216/3) and [here](https://groups.google.com/forum/#!topic/ames-stereo-pipeline-support/24RzLqkc9CY).

**Comment by jessemapel** [comment]
First of all, thanks for writing a solid bug report!

> * Tried with several other images, including ones that don't cross the prime meridian and ones that I know have worked for other people
> * Images near the pole with polar stereographic map template

Did these image also have Null lower left and upper right coordinates?

**Comment by lwellerastro** [comment]
In regard to running caminfo on a projected cube (l2.cub) - I'm not sure why it ran as caminfo is intended to run on level 1 images (unprojected).  

> EDIT: Comparing to the documentation in caminfo.xml, it also seems like the Mapping, Camstats, and Polygon groups are missing altogether as well.
> 

Caminfo will only generate output for geometry by default.  Run "caminfo -h" to see what parameters are set to or refer to the documentation.  Caminfo does not include the Mapping group in the output because it does not run on level 2/projected images.

I ran the the image through caminfo after ingesting and running spiceinit on M152445210LE with no issues.  Valid latitude and longitude values are reported for all corners.

@jessemapel, my data are under /usgs/shareall/TEMP/lweller/ if you want to grab it and here are my processing steps:

> lronac2isis from=/pds_san/PDS_Archive/Lunar_Reconnaissance_Orbiter/LROC/EDR/LROLRC_0006/DATA/SCI/2011046/NAC/M152445210LE.IMG to=M152445210LE.cub
> spiceinit from=M152445210LE.cub
> caminfo from=M152445210LE.cub to=M152445210LE.pvl geometry=true camstats=true linc=100 sinc=100

I was running under isis3.8.0-RC1

I'm not sure how any of this information feeds back into the OP's problem, but I don't think it is an issue with the image or spice.

**Comment by lwellerastro** [comment]
And just a note on caminfo and NULL values for some keywords (lat/lon corners) - totally legitimate, particularly for disk and limb images where the target/spice does not fill the full frame.

Ok, I just revisited one of my many caminfo output files and it will indeed write out a Mapping Group in conjunction with the Polygon group (when polygon=true), but it has nothing to do with the input being projected.  I think it is just a way of summarizing the polygon when using a sinusoidal projection (which is what it always is as there is no option to use a different projection type).

And I think the reason why the program ran on a level 2 image is because the Instrument and Kernels group are still on the label so caminfo can effectively run campt at the center of the image and successfully get geometry information there.  I just tried this on a projected Galileo file of mine and it ran.  I have some NULL values in the corners because it is projected and there is no data there.  This seems like a bug to me (running on level 2's), especially since the documentation says the program is intended for level 1 files only (hence the "cam" in the name, otherwise it would be "map").

**Comment by jessemapel** [comment]
Maybe the solution here is to raise an error if it's run on a projected image.

**Comment by dbolan** [comment]
I went home to check on my other machine and it turns out that LowerLeft* and UpperRight* were missing on the working images there too, so I don't think that's causing my problem either anymore either.

Sorry, I should have run -help from the start.

**Comment by jessemapel** [comment]
@dbolan Don't feel bad, we usually try to put sanity checks in the apps if you try to use it with incorrect data.

--edit--

you can get all of this by just running the catlab application on the cube

**Comment by lwellerastro** [comment]
I agree on the input image check - maybe look for a Group=Mapping and fail if found.  

@dbolan, as @jessemapel indicated, don't sweat it.  There is a lot to isis and the terminology associated with the applications as well as the input and output data.  Trouble-shooting can sometimes be a big part of image processing, and you have jumped right in.

**Comment by jlaura** [comment]
@dbolan from your perspective, is this resolved?

@jessemapel are we closing this, modifying the issue to be about error reporting, or something else?

**Comment by jessemapel** [comment]
We should change this to error reporting. The fact that it's partially successful on projected images means we should at least have a warning.

**Comment by jlaura** [comment]
I tagged as an enhancement, but am not really sure how best to label this. This is almost a doc (on run) issue.

**Comment by dbolan** [comment]
I was eventually able to prove to myself that the issue I was seeing was part of ASP rather than ISIS:
NeoGeographyToolkit/StereoPipeline/issues/275
Still, thank you for looking into this!

**Comment by jlaura** [comment]
@dbolan :+1: Awesome that you were able to debug to ASP. We have gotten this renamed so will leave open for potential future work. Thanks for the great initial report and for working through the issue with us.
