### ISSUE TITLE
hi2isis>hical>ERROR

### ISSUE THREAD

**Issue by connor-mac-leod** [DOI-USGS/ISIS3#3433]
Hello,

I'm using "hiedr2mosaic.py" and I get the following error, which was also reported by another user ( see this discussion: https://groups.google.com/forum/#!topic/ames-stereo-pipeline-support/nHHuyNvrIp8 ) in the NASA ASP forum:

**USER ERROR** Failed in GainUnitConversion module.
**ERROR** An unknown NAIF error has been encountered. The short explanation provided by NAIF is [SPICE(SPKINSUFFDATA)]. The Naif error is [Insufficient ephemeris data has been loaded to compute the position of 499 (MARS) relative to 0 (SOLAR SYSTEM BARYCENTER) at the ephemeris epoch 2015 JUL 23 14:24:33.835.].
**USER ERROR** Failed in GainUnitConversion module.
**ERROR** An unknown NAIF error has been encountered. The short explanation provided by NAIF is [SPICE(SPKINSUFFDATA)]. The Naif error is [Insufficient ephemeris data has been loaded to compute the position of 499 (MARS) relative to 0 (SOLAR SYSTEM BARYCENTER) at the ephemeris epoch 2015 JUL 23 14:24:33.835.].

My base and mro data are up to date. 

What can I do??

Thank you in advance for your help.

Piero

**Comment by jessemapel** [comment]
@connor-mac-leod Can you fill out the remainder of the bug report form please. What version of ISIS are you using and how can this be reproduced.

**Comment by rbeyer** [comment]
Piero,

Can you reproduce this outside of hiedr2mosaic.py by just running

    hi2isis fr= something.img to= hirise.cub
    hical fr= hirise.cub to= hirise.cal.cub

This should produce the same error that you're seeing, but provides the minimal ISIS-only error that folks can help you with here.  This smells like a SPICE problem, and in the ASP thread, I gave Divya some suggestions to see if other commands with HiRISE or CTX images fail too, and that might help narrow down where the problem is.

**Comment by jessemapel** [comment]
This is probably another de430 problem. de430 does not have MARS in it, instead it has MARS_BARYCENTER.

**Comment by connor-mac-leod** [comment]
I have ISIS 3.4.12.6662, but I don't think it's a problem related to the ISIS version. As far as I understood, the other user with the same issue has the latest ISIS version.

@jessemapel What is the de430 problem? 

Piero

**Comment by jessemapel** [comment]
@connor-mac-leod We updated the base planets SPK to de430 and it does not contain information for `MARS` but rather `MARS_BARYCENTER`. There are changes in 3.8.1 and later versions of ISIS that account for this, but if you use de430 with an older version of ISIS you may get errors like the one you are seeing when calibration programs attempt to find the position of MARS.

**Comment by rbeyer** [comment]
So either try temporarily removing de430.bsp from your $ISIS3DATA/base/kernels/spk/ area, or update to ISIS 3.8.1 or later.  If one of those works, we've figured it out.

This version mismatch problem between the ISIS codebase and the ISIS data area is something the devs are working on, so that you can get a 'data area' that is 'right' for whatever version of ISIS you are using, but for the moment, a problem like this can bite you.

**Comment by connor-mac-leod** [comment]
@jessemapel Thank you. Unfortunately, as I mentioned in the previous post ( https://github.com/USGS-Astrogeology/ISIS3/issues/3430 ) I had problems running the "stereo" both with ISIS 3.6 and 3.5.2 with both MacOSX Mojave and Ubuntu 19.04. I resolved by using ISIS 3.4.12.6662 installed on one mid 2010 iMac in our department. 

Is there a way I can solve this without upgrading ISIS?

Thank again.

Piero

**Comment by connor-mac-leod** [comment]
@rbeyer I deleted the de340.bsp. It looks like it's working properly now, thanks a lot! Will this not affect my final DEM?

Piero

**Comment by connor-mac-leod** [comment]
PS: I deleted the "de430.bsp", sorry for the typos

**Comment by rbeyer** [comment]
No, it won't impact the final DEM that you might make with ASP.
