### ISSUE TITLE
camdev "LOCAL" options unclear

### ISSUE THREAD

**Issue by lavalaz** [DOI-USGS/ISIS3#3483]
**Description**

I, and most users, will not know what the difference between "EMISSION" and "LOCALEMISSION" is.  Similarly with INCIDENCE and LOCALINCIDENCE.  

**Suggested Edit**

I suspect the difference is easy to explain (one used a DEM and the other doesn't is my guess, but its just a guess).  There is some text related to 90 degrees, but it does not clarify the difference between these options.  Please add a few words to explain what these are, perhaps next to the text describing the 90 emission/incidence limits.  I *think* the other keywords will be understood.  

Thanks!

**Comment by jlaura** [comment]
@lavalaz Have you checked out the [glossary](https://isis.astrogeology.usgs.gov/documents/Glossary/Glossary.html) provided by the documentation?

[Here](https://github.com/USGS-Astrogeology/ISIS3/blob/58710a4359deadee3f8d406daa0e37696f0f62f0/isis/src/dev/apps/camdev/camdev.xml) is a link to the `camdev` documentation. If you would like some assistance opening a PR to help improve or clarify that documentation, please let us know and we will get someone to walk you through the process!

**Comment by lavalaz** [comment]
I was not aware of the glossary, but these terms are missing from the glossary too.  

I cannot help clarify the documentation because I have no knowledge of what these parameters actually are.  I can help verify that new documentation is clear, but I cannot explain what I do not know.  So I do not feel it is appropriate for me to be opening a PR where I suggest I will improve the documentation.  Please let me know how to proceed.  

Thank you!

**Comment by jlaura** [comment]
@lavalaz 

Thanks for the further feedback. A few questions:

1. Have you looked [here](https://isis.astrogeology.usgs.gov/Application/presentation/Tabbed/camdev/camdev.html)? I would draw your attention to the first line of the online documentation. Specifically:
> This application is for camera development and is not supported for general public use.

2. Have you looked at the parameters tab of the documentation? Specifically, the LOCALEMISSION and LOCALINCIDENCE keywords are linked and provide inline definitions. I am not linking those as they are pop-ups in our documentation. Please see [here](https://isis.astrogeology.usgs.gov/Application/presentation/Tabbed/camdev/camdev.html) and click on the `Parameters` tab.

The docs on the popups are explicit and use language consistent with the glossary, e.g., Local Incidence Angle.

3. Have you read through the high quality documentation that has been provided for an application that we explicitly identify as not supporting for general use? To further quote the above documentation (with inline links to the glossary): 

> There are instances where the [local emission angle](https://isis.astrogeology.usgs.gov/documents/Glossary/Glossary.html#LocalEmissionAngle) and the [local incidence angle](https://isis.astrogeology.usgs.gov/documents/Glossary/Glossary.html#LocalIncidenceAngle) will have values over 90 degrees.

In addition to the above instances where the terms are being defined, what additional documentation would you propose? Perhaps you are asking for an API breaking change whereby LOCALEMISSION (the argument to the command) is renamed to LOCALEMISSIONANGLE? I am just guessing though, because as far as I can tell, adequate (verbose) documentation is being provided on multiple different pages in both textual and tabular form that guides us to the fact that the parameter name (LOCALEMISSION) is the local emission angle.

Any help you can provide in being more explicit about what change you would like to see will help us support you in opening a PR to realize that change.

**Comment by jessemapel** [comment]
The camdev application and a handful of others are intended only for development on ISIS camera models. I'm hesitant to make changes to documentation for them as users should be using something like phocube instead.

**Comment by lavalaz** [comment]
I found _camdev_ instead of _phocube_ when searching for an ISIS3 application to create backplanes.  I revise my suggestion for the _camdev_ documentation.  Instead of *only* saying this application is for camera development, please add the very helpful comment that regular users should consider using _phocube_ instead of _camdev_.  No need to add any other documentation to _camdev_.  Thank you!

PS - yes, I did read every word of the camdev documentation...  implying that I did not is...

**Comment by jessemapel** [comment]
The docs on the website will get this change once we push the next public feature release.
