### ISSUE TITLE
Kaguya TC missing label keyword

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#3542]
**Description**  
Please add the keyword ILLUMINATION_CONDITION to the isis3 image label.  Either under Instrument group or Archive.  This is a very valuable keyword and although I can find it in the pds files and by running origcatlab it would be most useful to have it somewhere in the isis3 cube label.  It will likely be sought out frequently.

Also consider removing the geometry keywords from the Instrument group and putting them under the Archive group.  Instrument group is an unusual location to see these keywords (UpperLeftLatitude, UpperLeftLongitude, UpperRightLatitude, UpperRightLongitude, LowerLeftLatitude, LowerLeftLongitude, LowerRightLatitude, LowerRightLongitude).  Obviously keep these if code is using these keywords in some way.

There are two img's and the kaguyatc2isis cubes under /work/users/lweller/Isis3Tests/KaguyaTCCamera/.  One has illumination condition morning and the other evening.  I do not know if there are other illumination conditions to consider.

Note: I can not add labels for this post.

**Comment by lwellerastro** [comment]
@jessemapel could you add the products label as well?

**Comment by jessemapel** [comment]
@jlaura Can you give @lwellerastro and @blandoplanet permissions to tag things with labels? They are contributors under our new TC setup, so it makes sense for them to have the permissions for this.

**Comment by jessemapel** [comment]
Either triage or write level permissions should do.

**Comment by lwellerastro** [comment]
Note: I have made two request in my original post: add a new keyword (IlluminationCondition) and to consider moving imported geometry keywords to a different group (archive).  The first request is by far the most important and the second may be a separate post and is not critical.

**Comment by jlaura** [comment]
@lwellerastro Unless we have any dissenting opinions in this post, I would suggest that the acceptance criteria on getting this ticket closed is that both requests are fulfilled. We will be in working on the label anyway, so no reason not to take care of both.

**Comment by AustinSanders** [comment]
No **source** changes were made to satisfy the acceptance criteria for this ticket, so there's no PR that can be linked.  Relevant changes were made to the translation files (kaguyaTcInstrument.trn and kaguyaTcArchive.trn).  An example of the new label format can be found at /work/users/arsanders/kaguyatc/TC2S2B0_01_03043N107E3384_revised.cub .  Alternatively, since these changes were made to translation files rather than source, any cub generated by kaguyatc2isis will also be generated with the new label format.

In the event that these changes need to be rolled back, the old translation files can be found in /work/users/arsanders/kaguyatc/backup_translations .

Short list of changes:
- IlluminationCondition was added to the instruments group via edits to the translation file.
- Geometry keywords (UpperLeftLatitude, UpperLeftLongitude, UpperRightLatitude, UpperRightLongitude, LowerLeftLatitude, LowerLeftLongitude, LowerRightLatitude, LowerRightLongitude) were moved from instruments group to archive group via edits to the translation file.

**Comment by lwellerastro** [comment]
Looks great - thanks!
