### ISSUE TITLE
Cannot combine even and odd parts of LROC WAC

### ISSUE THREAD

**Issue by lavalaz** [DOI-USGS/ISIS3#3647]
**ISIS version(s) affected**: all (3.9.0)

**Description**  

The PDS archived LROC WAC data are split into even and odd framelets. To do anything scientific, these two parts need to be joined. The application to do this processing step is missing. 
**How to reproduce**  

take any PDS LROC WAC product
run lrocwac2isis
run spiceinit
run lrocwaccal
run cam2map
qview the output.
**Possible Solution**  

create an lrocwacevenodd application.  Or even better, an lrocwacproc application that runs lrocwac2isis, spiceinit, lrocwaccal, and lrocwacevenodd. 
**Additional context**  

Mosaicking the map projected even and odd halves does not work because the DNs computed along the edges of each framelet are using only half the actual data and are producing scientifically inaccurate values. So the mosaic ends up with stripes of scientifically garbage data. I debated whether to call this a new feature request of a bug. The fact that we claim ISIS3 allows users to process LROC WAC data but we are missing an essential step seems to be more like a bug than a new feature request.

**Comment by jessemapel** [comment]
@victoronline How do you guys combine the odd and even data at ASU?

**Comment by AaronBoyd** [comment]
Nothing new needs to be developed, just mosaic the left and right together after you have the map projected cubes. 

The PDS files are not split into even and odd frames, but that is done when they are brought into isis so that they can be map projected correctly. Otherwise there are non-unique solutions for what the mapped pixel values should be.

If you want the even frames on top of the odd frames, create a list of the cubes. 

IMAGE.vis.even.map.cub
IMAGE.vis.odd.map.cub

Run **automos** using the list with the option priority=beneath.
If you want the odd frames on top, use the option priority=ontop

**Comment by jlaura** [comment]
@lavalaz Just wanted to ping you to make sure you saw this. I am going to close, but please reopen if this is still an issue.

@AaronBoyd Thanks for the solution!
