### ISSUE TITLE
ISIS is not propagating apriori covars correctly 

### ISSUE THREAD

**Issue by Kelvinrr** [DOI-USGS/ISIS3#3654]
**ISIS version(s) affected**: 3.9.x (only tested on 3.9, earlier versions most likely affected)

**Description**  

It seems like a fair assumption that a control network with preset apriori covariance matrices would have their covar matrices used in the solution. This doesn't seem to happen by default and instead requires `errorpropagation=yes` to be set. 
Additionally, the sigmas computed by ISIS do not match the apriori covars set directly (using plio.utils.covariance.compute_covariance).   

**How to reproduce**  

on astrovm4:
```
cd /scratch/krodriguez/errorprop_issue/
jigsaw radius=yes update=no camsolve=accelerations twist=yes overexisting=yes spsolve=no camera_angles_sigma=.25 camera_angular_velocity_sigma=.1 overhermite=yes spsolve=velocities camera_angular_acceleration_sigma=.01 fromlist=wTestingGround.fixed.bundle.lis point_radius_sigma=3 errorpropagation=no cnet=wTestingGround.covar.net fromlist=wTestingGround.lis onet=wTestingGround.cover.nopropagation.net
```

the cnet wTestingGround.covar.net has apriori covariance matrices set for constrained points, yet looking at bundout.txt, you find:

```
           11860    CONSTRAINED    5 of 5  2.56    -16.76330175    175.90325921   3394.15537776             N/A             N/A             N/A
           11861    CONSTRAINED    2 of 2  0.84    -15.87137426    177.07546406   3394.82141017             N/A             N/A             N/A
            9021           FREE    3 of 3  1.76    -14.18539703    173.68860729   3393.48872384             N/A             N/A             N/A
            9022           FREE    2 of 2  0.77    -12.13274821    175.49347329   3392.92034199             N/A             N/A             N/A
```

Where the N/A's should be lat lon radius sigmas. 

running with error propagation on:

```
cd /scratch/krodriguez/errorprop_issue/
jigsaw radius=yes update=no camsolve=accelerations twist=yes overexisting=yes spsolve=no camera_angles_sigma=.25 camera_angular_velocity_sigma=.1 overhermite=yes spsolve=velocities camera_angular_acceleration_sigma=.01 fromlist=wTestingGround.fixed.bundle.lis point_radius_sigma=3 errorpropagation=yes cnet=wTestingGround.covar.net fromlist=wTestingGround.lis onet=wTestingGround.cover.nopropagation.net
```

and we can see the covars for constrained points are actually set 

```
         11860    CONSTRAINED    5 of 5  2.56    -16.76330175    175.90325921   3394.15537776      0.13773962      0.12487745      5.65114812
           11861    CONSTRAINED    2 of 2  0.84    -15.87137426    177.07546406   3394.82141017      0.13064246      0.11954124      5.65646668
            9021           FREE    3 of 3  1.76    -14.18539703    173.68860729   3393.48872384     42.70802437     54.27227979      5.67749143
            9022           FREE    2 of 2  0.77    -12.13274821    175.49347329   3392.92034199     17.03932564     17.84729682      5.67493760
            9023           FREE    3 of 3  1.60    -15.26765453    173.82379793   3393.94539657     38.49051148     45.20810275      5.67750334
```

But these sigmas do not match what was used in computing the covariance matrix (.25 lat/lon, 3 radius). This gives me the impression that ISIS is simply ignoring the covars and computing its own sigmas.  

**Possible Solution**  

This could be a bug in ISIS requiring a fix. Additionally, it could be user error in attempting to determine what ISIS is using as the priori sigmas.  

**Additional context**  

covariance matrices were compited and written out using `plio.utils.covariance.compute_covariance` and `plio.io.io_controlnetwork.to_isis` respectively.

**Comment by lwellerastro** [comment]
Kelvin - I think I understand why you are seeing differences between errorprop on/off.  You are looking at the wrong section.  Those are the calculated uncertainties for the points and will be be different than the input accuracy/weights on a point.  Those are ONLY calculated when errorprop=yes, otherwise it should be NA.  

Jump down to POINTS DETAIL in the bundleout.txt and you will see your apriori sigmas/weights recorded under INITIAL ACCURACY.  There should be a value there whether errorprop=yes or =no.  

That being said, I am also seeing problems with how jigsaw is reporting constrained point apriroi sigmas - not what I am expecting.

I confirmed this by bundling an old Themis IR network today under isis3.9.1 and comparing it against an older version of isis.  The sigmas were set years ago and are properly reflected under the older version (circa June 2018) but not under the current version.  Qnet similarly reports the sigmas inaccurately, which says to me this is not a jigsaw problem, it's something else handling/interpreting the contents of the network, sigmas in particular.

This problem seems to go back for a while.  I have test runs on a small themis ir network with ground and it exists back to isis3.8.0 (as well as isis3.6.2...just tested that version):

Here is point detail output using isis3beta2018-06-05:
```
 Label: h2913_0000_6
Status: CONSTRAINED
  Rays: 2 of 2

     Point         Initial               Total               Total              Final             Initial             Final
Coordinate          Value             Correction          Correction            Value             Accuracy          Accuracy
                 (dd/dd/km)           (dd/dd/km)           (Meters)           (dd/dd/km)          (Meters)          (Meters)
  LATITUDE      40.09727511           0.00000157          0.09325511         40.09727668        3.00000000        0.55782887
 LONGITUDE     280.70698001           0.00000008          0.00346002        280.70698009        3.00000000        0.32647506
    RADIUS    3389.71506943           0.00003342          0.03342487       3389.71510286       12.00000000        2.23194542
```
The Initial Accuracy values are as expected.

```
> Same network, isis3.8.0 (and isis3.9.1) output:
>  Label: h2913_0000_6
> Status: CONSTRAINED
>   Rays: 2 of 2
> 
>      Point         Initial               Total               Total              Final             Initial             Final
> Coordinate          Value             Correction          Correction            Value             Accuracy          Accuracy
>                  (dd/dd/km)           (dd/dd/km)           (Meters)           (dd/dd/km)          (Meters)          (Meters)
>   LATITUDE      40.09727511           0.00000157          0.09307731         40.09727668        2.99428042        0.55676536
>  LONGITUDE     280.70698001           0.00000008          0.00345343        280.70698009        1.75210802        0.32585263
>     RADIUS    3389.71506943           0.00003342          0.03342487       3389.71510286       12.00000000        2.23194542
> 
```
The sigmas on radius have managed to stick.

As a test, I opened up a test Kaguya network in qnet, manually created a ground point and set the sigmas, saved and closed the app.  I reopened the saved network in qnet, loaded up the ground point and it reported the previously saved sigma values.  This is good news for current ground work. At least in my case the problem is with an older network, but that is not true Kelvin's case.  So it's not so clear what is going on.

If you want different data to test on see /work/users/lweller/Isis3Tests/Jigsaw/Sigmas, themis_dayir_ground.lis and themis_dayir_ground.net.

**Comment by jessemapel** [comment]
I am tentatively labeling this as a bug. There's something here that isn't quite lining up correctly. We should spend sometime examining the control networks Lynn and Kelvin tested with before we decide how to handle this.

**Comment by lwellerastro** [comment]
I have been going through bundleout.txt files for a number of projects covering 2018 and 2019.  Sigmas are handled properly right up until fall of 2018 using isis3beta2018-xx-xx.  Unfortunately I can not say with certainty when in 2019 this came undone as I was predominately working on projects that had no ground to tie to.  I know LROCNAC data with ground was being bundled during 2019, however the user was using a much older version of isis (like isis3production version) to do so and their sigmas are ok.

I was just trying to help home in on when a change occurred to help isolate where you all should look, but I don't have the data to support the search.

**Comment by lwellerastro** [comment]
@Kelvinrr, error propagation will not execute if the bundle does not converge.  That may also be why you are seeing it in your bundleout.txt.

**Comment by Kelvinrr** [comment]
@lwellerastro Possibly? It's been a while since I have looked at these but I am fairly confident the bundle adjustment converged.

**Comment by jessemapel** [comment]
As part of the BundleXYZ change, we switched from using global radii values to using local radius to convert between rectangular and latitudinal sigmas. The point sigmas in CNet files are stored as rectangular.

@lwellerastro Since the cnet file you were testing with was generated prior to the BundleXYZ change, you are seeing a difference because the original sigmas were set as latitudinal and then converted to rectangular using global radii. When, you open the file up with a post BundleXYZ version the rectangular sigmas are converted to latitudinal sigmas using the local radii.

@Kelvinrr Looking at the PLIO code, it uses a single global radius value to do the conversion, so it's coming out slightly different there.

I am going to do some math to check that everything is still converting correctly, but I think these differences are expected.

**Comment by lwellerastro** [comment]
@jessemapel, does this mean that in order to get the desired sigmas, pre-BundleXYZ networks already having sigmas need to have their sigmas adjusted/reset under a current (post-BundleXYZ) version of isis?

**Comment by jessemapel** [comment]
@lwellerastro Yes. It would also be possible to write a script that takes the rectangular sigmas in the files, converts them back to latitudinal using the old global radii and then back to rectangular using the local radius. This seems like a step too far unless someone has such a network right now.

So, in the meantime I am going to add some code to plio to help if we decide we need to do that.

**Comment by jessemapel** [comment]
For reference, this change was made in #378 and the change was motivated by #2612

**Comment by jessemapel** [comment]
The plot thickens:

Looking back at the [old SurfacePoint code](https://github.com/USGS-Astrogeology/ISIS3/blame/2d1238d48768d8fb154e51cae3b1fe5abe0fe226/isis/src/base/objs/SurfacePoint/SurfacePoint.cpp#L555) and comparing it against the [new SurfacePoint code](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/base/objs/SurfacePoint/SurfacePoint.cpp#L1242), there was a bug in the old code that go fixed which is also impacting this.

To convert the longitude sigma from meters to radians you use the following equation:

`sigma_radians = sigma_meters / (cos(lat) * radius)`

The old ISIS code unfortunately used the following:

`sigma_radians = sigma_meters * cos(lat) / radius`


This same bug is also present in the [current PLIO conversion code](https://github.com/USGS-Astrogeology/plio/blob/master/plio/utils/covariance.py#L45) too. This is why the latitude sigmas look very close what was previously set, but the longitude sigmas are far off.
