### ISSUE TITLE
mappt report DN values for all bands (or at least the band for the DN value)

### ISSUE THREAD

**Issue by lavalaz** [DOI-USGS/ISIS3#3875]
**Description**  

Currently mappt only reports the DN value for a single band. To get the values for different bands at the same location you need to run mappt repeatedly for each band.  But then there is no record of which band the DN value came from in the output file.  This greatly reduces the usability of mappt.  It would be nice if the band was labeled not just with the band number but also the name so one did not need to retain the original .cub file to know what the numbers in the output file mean. 
**Example**

**Comment by jessemapel** [comment]
Good candidate for work alongside #3872

**Comment by Kelvinrr** [comment]
PR is up for this change: https://github.com/USGS-Astrogeology/ISIS3/pull/3890

This adds band and filter info as part of the output. 

Some questions:

1. I am not sure whether multiple band output is part of the requirements? The first half of the post implies it is but the rest implies you only want the band info to be part of the output? 
2. PR adds physical band number and filter name as part of the output. I understand some cubes will not have filter names and simply have filter number, is the current behavior in the PR of only reporting filter name if available otherwise default to "Null" the desired behavior?

**Comment by lavalaz** [comment]
1. Just recording which band the DN value corresponds to is acceptable.  Being able to output the values of multiple bands would be nice but may be impractical given how varied (and large) the number of bands can be.  
2. "Null" if there is no name for the band is fine.  Thanks!
