### ISSUE TITLE
kaguyasp2isis is listed under "utility" instead of "mission specific programs" and update docs to indicate kaguyasp2ascii should be used instead.

### ISSUE THREAD

**Issue by lavalaz** [DOI-USGS/ISIS3#3876]
**Description**

This application is listed under the wrong heading on the website https://isis.astrogeology.usgs.gov/Application/index.html#Utility
**Suggested Edit**

List it under Kaguya under Missions.  
Thanks!

**Comment by krlberry** [comment]
I actually think that the solution to this ticket is to remove the `kaguyasp2isis` program from ISIS. It was announced that this program was being updated and renamed to `kaguyasp2ascii` in 2015 (See: https://isis.astrogeology.usgs.gov/Application/presentation/Tabbed/kaguyasp2ascii/kaguyasp2ascii.html) but it looks like the old version (`kaguyasp2isis`) was never actually removed. 

That being said, since it wasn't removed in 2015, would we need to give more warning about removing it now? Right now, looking at it, `kaguyasp2isis` is just an old version of `kaguyasp2ascii` that won't work on newer formats of input files.

**Comment by thareUSGS** [comment]
Are you recommending moving this to somewhere like: https://github.com/USGS-Astrogeology/ISIS_contrib ? I think that is reasonable especially since you don't think it works on newer files.

**Comment by krlberry** [comment]
Talked about this during the stand up. Since `kaguyasp2ascii` is just a newer version of `kaguyasp2isis` this ticket now contains the following work:

(1) Still update this so it is listed under the Kaguya mission instead of under utilities 
(2) Update the `kaguyasp2isis` documentation to link to the `kaguyasp2ascii` documentation and say something along the lines of: "Use kaguaysp2ascii -- it's a newer version of kaguyasp2isis that was renamed since it doesn't actually import cubes into ISIS" with a warning about a future deprecation date.

**Comment by lavalaz** [comment]
FWIW, I think this is a perfect solution.  Thank you!

**Comment by jlaura** [comment]
@kberryUSGS Did this get updated? Can we close?

**Comment by krlberry** [comment]
@jlaura It didn't get updated. I only updated the ticket with more information.

**Comment by Kelvinrr** [comment]
closed by #3996
