### ISSUE TITLE
phocube, in source=projection should be able to accept a multi-band cube as input

### ISSUE THREAD

**Issue by lavalaz** [DOI-USGS/ISIS3#3877]
**Description**  

Adding lat/lon backplanes to a color mosaic would be easier if phocube would accept a multiband input.  I think it is reasonable to assume that if the user wants to propagate DNs to the output, they will want to propagate DNs for all the bands. Yes, one can run phocube on a single band and then run cubeit, but, for large mosaics, that adds another slow step.  A nice-to-have, not something essential! 
**Example**  

enter the following command:
_phocube from=some-color-mosaic.cub to=mosaic-with-backplanes.cub source=projection_
and you get an output instead on an error message.

**Comment by scsides** [comment]
@lavalaz phocube currently requires a single band input (defaults to band 1 if not specified using a cube attribute) because some multi-band images are not spatially registered (e.g., Themis IR). line=1, samp=1, band=1 has a different lat/lon then line=1, samp=1, band=2. In your example it is a projected mosaic, so all the bands are spatially registered by definition.

Option:
Add a parameter to phocube to force it to include all DN bands in the output cube and put a big red warning in the documentation to warn users of the possibility the DN bands are not properly represented by the pho bands. Have the default behavior be identical to the way is now, so we don't break existing scripts (backward compatibility). 
Additionally, it may be **easy or not** to add in enough upfront checks to allow this when the output would be correct and fail if not.

**Comment by scsides** [comment]
@lavalaz, What do you think of the solution above?

**Comment by lavalaz** [comment]
I had not considered the case where phocube might be run on non-map-projected data when I suggested this enhancement.  It seems to be a bad idea for cases when the different bands are not spatially registered.  But, as a user with a specific need, your solution would work great for me.  I am trying hard to imagine the trouble other users might get themselves into if this option exists and I am inclined to feel that the warning in the documentation should suffice.  A lot of words to say I like the idea!

**Comment by jessemapel** [comment]
This is on the current support backlog
