### ISSUE TITLE
ISIS 4.1.0

### ISSUE THREAD

**Issue by Fscipioni** [DOI-USGS/ISIS3#3925]
Hallo,

I'm trying to install ISIS 4.1.0 on my machine, MacBook Pro with Catalina 10.15.5.
I run the command conda install -c usgs-astrogeology isis=4.1.0 on a terminal, but the installation is stuck on the "Solving environment:" part.

Should I wait for a release more compatible with Catalina?

Thanks,
Francesca

**Comment by jessemapel** [comment]
Hi Francesca,

Sometimes it can take quite a long time (even hours) for the Anaconda solvers to figure out the environment. I would recommend cleaning your anaconda cache by running `conda clean --all` prior to installation.

We also do not have a lot of 10.15 support right now because the Department of the Interior hasn't cleared it for the USGS developers to work on yet. We have some non-USGS folks working in 10.15 and it is something people are interested in so we hope to have better support for it soon.

**Comment by jessemapel** [comment]
I am closing this as 10.15 is not officially supported and I haven't had egregious wait times for 4.1.1
