### ISSUE TITLE
Spiceinit error in processing Chandrayaan-1 Mini-SAR data

### ISSUE THREAD

**Issue by sriramsaran** [DOI-USGS/ISIS3#3967]
**ISIS version(s) affected**: 4.1.1

**Description**  
Hi all, I am trying to process a level-1 Chandayaan-1 Mini-SAR (aka Forerunner) data and got this error while running SPICEINIT. Here is the description: 
_File name :_ fsb_01339_1cd_xiu_88s311_v1.lbl .img
mrf2isis from=fsb_01339_1cd_xiu_88s311_v1.lbl to= fsb_01339_1cd_xiu_88s311_v1.cub
spiceinit from=fsb_01339_1cd_xiu_88s311_v1.cub
_prompt error:_ No Camera Kernel found for the image.

Then I tried using SPICE Web Service, got a similar response :
mrf2isis from=fsb_01339_1cd_xiu_88s311_v1.lbl to= fsb_01339_1cd_xiu_88s311_v1.cub
spiceinit from=fsb_01339_1cd_xiu_88s311_v1.cub web=yes
_prompt error:_ “The Spice Server was unable to initialize the cube.  The error reported was: No Camera Kernel found for the image”

I have downloaded the mission data prior to doing this (using: rsync -azv --delete --partial isisdist.astrogeology.usgs.gov::isisdata/data/chandrayaan1 .)

Are some of those mission kernels updated and/or do I need to download any other kernels for running spiceinit here? 
 
Thanks in advance !

**Comment by jessemapel** [comment]
If you want to run spiceinit locally, you will need to download the entire Chandrayaam data area. That said, the web server should work for you. Can you post the label for the ingested cube?

**Comment by sriramsaran** [comment]
Hi, attched the label for the cube here, thanks. 
[label_from_mrf2isis.txt](https://github.com/USGS-Astrogeology/ISIS3/files/5047728/label_from_mrf2isis.txt)

**Comment by jessemapel** [comment]
This image was captured on February 27th and the ISIS Chandrayaan CKs only go up to February 14th and then skip to April. I assume this is because the PDS archive for M3 does that. I'm not sure where the kernels came from originally. @scsides I know you've been involved in some of this, any insight as to where the rest of the kernels could be? Do we even need a CK for MiniRF, I would assume not?

**Comment by scsides** [comment]
As Jesse wrote, the sensor model for MiniRF doesn't actually require a CK. It is "spiceinit" that is requiring the CK. The model does not use the CK in any way. I'm not sure if this will work, but try this using your local (i.e., not using the web service) data area: Run spiceinit and add the parameter: 
`CK=$Chandrayaan1/kernels/ckM3G20081118T222604_V03_L1B_nadir-jig_2016-04-29.bc`
The CK here is just to satisfy spiceinit, and doesn't really matter which one you pick. Please let us know if this works for you.

**Comment by BerginJay** [comment]
Hi everyone! I have the same problem here. I tried @scsides your method but sadly it seems not work. I'm now using ISIS 4.2.0 and I have downloaded isis base data and chandrayaan1 data (including kernels) via `rsync`. After adding CK parameter, command line window prompt:
```
spiceinit from=/Volumes/Earth/MiniSAR/cube/fsb_01918_1cd_xhu_88s110_v1.cub ck=/usr/local/anaconda3/envs/isis/data/chandrayaan1/kernels/ck/M3G20090415T222023_V03_L1B_nadir-jig_2016-04-29.bc
Group = Kernels
  NaifFrameCode             = -86001
  LeapSecond                = $base/kernels/lsk/naif0012.tls
  TargetAttitudeShape       = ($base/kernels/pck/pck00009.tpc,
                               $chandrayaan1/kernels/pck/moon_080317.tf,
                               $chandrayaan1/kernels/pck/moon_assoc_me.tf)
  TargetPosition            = ($Chandrayaan1/kernels/tspk/moon_pa_de421_1900--
                               2050.bpc, $Chandrayaan1/kernels/tspk/de421.bsp)
  InstrumentPointing        = /usr/local/anaconda3/envs/isis/data/chandrayaan-
                              1/kernels/ck/M3G20090415T222023_V03_L1B_nadir-j-
                              ig_2016-04-29.bc
  Instrument                = Null
  SpacecraftClock           = Null
  InstrumentPosition        = Null
  InstrumentAddendum        = $chandrayaan1/kernels/iak/mrffrAddendum002.ti
  ShapeModel                = $base/dems/ldem_128ppd_Mar2011_clon180_radius_p-
                              ad.cub
  InstrumentPositionQuality = Unknown
  InstrumentPointingQuality = Unknown
  CameraVersion             = 1
  Error                     = "No instrument position available"
End_Group
**ERROR** Unable to initialize camera model.
```
and these wouldn't be attached to cube file, while simply runing `spiceinit` locally without `CK` would only prompt `No Camera Kernel found for the image.` like Saran said. I assume this is understandable because we did not use the proper camera kernel (CK). So routines like cam2map are still not available. 

I tried to process images before Feb. and after Apr., like file fsb_01918_1cd_xhu_88s110_v1.cub, which is captured on 2009-04-15, and use corresponding ck files M3G20090415T222023_V03_L1B_nadir-jig_2016-04-29.bc, M3G20090415T202222_V03_L1B_nadir-jig_2016-04-29.bc. Still, Unable to initialize camera model. 

So, I'm still confused. Do we need some extra CKs to process MiniSAR data or how to avoid this?

Thank you!

**Comment by jessemapel** [comment]
@BerginJay It looks like there's no spacecraft ephemerides in the data area for Chandrayaan-1 between february 15th and April 14th. @scsides Any thoughts on where we would even find this? I looked around a little bit, but all I found was the kernels that we already have.

**Comment by krlberry** [comment]
Hi @sriramsaran and @BerginJay, 

It looks like ISIS was indeed missing spacecraft ephemerides (an SPK kernel) for the time associated with the image in this issue. A new SPK kernel has now been added to the ISIS data area which should fix this problem. Please update your data area using the following:

```
cd $ISISDATA
rsync -azv --delete --partial isisdist.astrogeology.usgs.gov::isisdata/data/chandrayaan1 .
```

Additionally, since the Mini-SAR data doesn't require a CK for calculations, you can run `spiceinit` with `cknadir=true` to assume a nadir-pointing spacecraft and avoid needing to supply a specific, but unused ck.

After updating your data area, could you try re-running `spiceinit` as below and let us know if that works? 

 ```
spiceinit from=fsb_01339_1cd_xiu_88s311_v1.cub cknadir=true
```

**Comment by BerginJay** [comment]
@kberryUSGS Thank you! I tested a lot of images, and so far so good. Thanks everyone!

**Comment by krlberry** [comment]
@BerginJay Glad to hear it's working!

**Comment by jessemapel** [comment]
I am closing this off as it seems to be resolved. @BerginJay If you find any issues please post and re-open.

**Comment by jessetarnas** [comment]
Hello, I am running into this same issue with ISIS 3.10.0. Did the kernels for ISIS3 get updated, or do I need to use ISIS4 to make this work? Thanks for your time.
