### ISSUE TITLE
Bit depth in lronac2isis, maybe other sensors

### ISSUE THREAD

**Issue by foobarbecue** [DOI-USGS/ISIS3#4003]
**Description**  
The LRO NAC image sensors are 12-bit, and data is companded and recorded onboard as 8-bit. When you download a NAC PDS .img, it's still 8-bit. However, when you convert to .cub using lronac2isis, the output is 32-bit. 

I understand that you may want to re-expand the data from 8 to 12 bits, and that means you probably need to use 16 bits. But can someone explain why we go all the way to 32? It kind of looks like it's just a waste of disk space, network bandwith, etc.

Here's where it happens: https://github.com/USGS-Astrogeology/ISIS3/blob/deb005172097415cd7651eebdd08b9a9f891646d/isis/src/lro/apps/lronac2isis/main.cpp#L95

If there's no reason for it, then can we modify this and have lronac2isis produce 16 bit output cubes, or at least add an option which causes it to output 16 bit?

**Comment by jessemapel** [comment]
I can't think of a good reason to keep the 32-bit output. It would be decent savings for users that are not going to be calibrating the data. For users that want calibrated data, though, the data will get converted to 32-bit during that step.

**Comment by astrostu** [comment]
I was wondering about this, too.  When is 16-bit useful vs 32-bit?  Seems like if you're doing careful calibration, you'd want to use the highest bit-depth and then down-sample to your final output, but that'll save you just maybe 1 or 2 greyscale values or rounding error, right?  So for most people, would not 16-bit even during calibration be more than enough, especially given the original image bit-depth?

**Comment by rbeyer** [comment]
@jessemapel: I agree, I can't think of a reason to have the output of lronac2isis be 32-bit, 16-bit should be fine, given the circumstances, but someone more involved in the process from LROC should probably weigh in, too (maybe @victoronline ?).

@astrostu: I think the output of the calibration should be 32-bit.  You're right, the sophisticated user might recognize and accept that downsampling to 16-bit is completely reasonable, and if they were doing a massive amount of processing, that would probably be prudent.  However, the generic output of the calibration process should be 32-bit, as this provides the least amount of surprises and pitfalls for the average user that is not constantly thinking about bit-depth.

Your comment also seemed to be about what bit-depth to use *during* calibration (which is a slightly different question).  Due to the fact that a lot of calibration math is already based on some equation that incorporates floating point numbers (as a constant of some kind, or even a predictable variable like the distance to the Sun, etc.), you're going to have to do floating point math in that code, so you will need to perform a conversion at some point in that algorithm.  And my point is that at the end, it should be written out that way (as 32-bit), and then the sophisticated user can convert, if they wish.

**Comment by jessemapel** [comment]
@astrostu That's a rather complex question. Most calibration is the result of some analysis done with completely separate software. For example, a mission scientist may load a bunch of star images and generate differences between expected and actual brightness values, then load that data into Matlab or R and perform some sort of regression analysis. That process likely involved several pieces of software and a fair amount of I/O. So much so, that attempting to determine a "best bit-type" to use that matches it is pointless.

So, we generally perform caibration in 64-bit doubles. This is broadly true for all ISIS programs. The default way to access image data in ISIS is through an API that abstracts away the bit-type and converts to and from 64-bit doubles. Because you can represent the exact same 32 bit float as a 64 bit double, this isn't really an issue. The only place were you really do need to operate in the appropriate bit-type is during ingestion and export (such as this issue).

I agree with @rbeyer's comments. Default to the "safest" option and then more familiar users can convert to 16-bit on their own using [Cube Attributes](https://isis.astrogeology.usgs.gov/documents/CommandLine/CommandLine.html#Pixel%20Type).

**Comment by foobarbecue** [comment]
Thanks for the discussion, all. Very educational for me. Sounds like not something the ISIS team is going to add, but if somebody super keen wants to write a PR to add a low-bit-depth option to the 2isis programs, it might be a nice addition.
