### ISSUE TITLE
TGO failures on MacOS

### ISSUE THREAD

**Issue by Kelvinrr** [DOI-USGS/ISIS3#4067]
**ISIS version(s) affected**: dev

We have several TGO module tests failing on MacOS: 

```shell
The following tests FAILED:
	1499 - tgo_module_test_coloredMosaic (Failed)
	1501 - tgo_module_test_mapProjectedReingested (Failed)
	1503 - tgo_module_test_singleColorMosaicReingest (Failed)
	1504 - tgo_module_test_singleFrameletProjection (Failed)
	1506 - tgo_module_test_uncontrolledSingleColorMosaic (Failed)
```

**Description**  

Link to Jenkins build: https://astroservices.usgs.gov/jenkins/job/ISIS-Nightly-Builds/job/dev/323/execution/node/101/log/

**How to reproduce**  

Any build running on MacOS Jenkins machines (igswzawgas-bmac).

**Possible Solution**  

This is most likely a data problem as the Mac has it's data area updated separately from Linux. 

**Additional context**

**Comment by krlberry** [comment]
The error I see when testing this on prog26 (for all tests) is: 
```
[libprotobuf ERROR google/protobuf/descriptor_database.cc:118] File already exists in database: ControlNetFileHeaderV0002.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:1379] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
Abort trap: 6
```
I'm not sure if this is a prog26 issue or _the issue_ described here because this error does not show up on Jenkins.

**Comment by scsides** [comment]
NOTE: Unable to reproduce the libprotobuf error from Nov 6 on Mac 10.14 or 10.15 with fresh environments.

The TGO mission tests, not specific app tests, are currently producing slightly different results for the min/max lat/lon, resolution, ... mapping keywords for all version of Mac OS (13,14,15), requiring OS specific truth data for each one. This is concerning because the same is not true for other instruments.

Note: There have been updates to the bandbin wavelength and width keywords that have not been propagated to the current Makefile based truth data because of the current failures on Jenkins.

Another error that showed up while investigating this issue is that the TGO camera model failed to instantiate for some of the mission tests on Mac OS 10.14 and 10.15; contributing to the failures and thus not allowing truth data to be updated.

**Comment by Kelvinrr** [comment]
TGO seems to be failing on all platforms as of NOV 14th: https://astroservices.usgs.gov/jenkins/job/ISIS-Nightly-Builds/job/dev/356/

**Comment by lifeiteng** [comment]
same error in https://github.com/deepmind/reverb/pull/24

**Comment by scsides** [comment]
It has been suggested that these module tests be changed to be not so sensitive to minor changes in ground to image and/or image to ground (causing the DN to change). One way to do this is to remove the offending output cubes at the end of the test, so that DNs are not compared. To better test the results, we can add a campt run to the end of the test. The campt run should take a list of points scattered over the image, maybe 15 or so. I suggest we add a pvl diff file for this output that ignores most of the campt output, so it can focus on the lat/lons.

**Comment by acpaquette** [comment]
As fair as I can tell the failing tests issue has been solved. However, we should probably talk about how we plan to update the module tests in the future. In the mean time this can probably be closed
