### ISSUE TITLE
Missing coverage for Jigsaw 

### ISSUE THREAD

**Issue by Kelvinrr** [DOI-USGS/ISIS3#4123]
**ISIS version(s) affected**: dev

**Description**  

Some test coverage is missing from jigsaw: 

1. Radar: Needs radar data, there might be some questions about how to ingest Radar data from an ISD into ISIS properly 
2. Overhermite: Same issue as radar
3. Scconfig/ScconfigHeld: Instructions in the [test document](https://doimspp-my.sharepoint.com/:w:/g/personal/jmapel_usgs_gov/EWIb85aKSRtHrrlV8UYXOewBXmJT0TPRu6c5MQXhcv2oSA?e=Bmy3cg) seems to be unclear about the best way to test this (descriptions on how to solve this seem incomplete)

**How to reproduce**  

Any dev test will have these four missing. 

**Possible Solution**  

Radar data will need an ALE drivers for Isis labels + lsis data

**Additional context**

**Comment by lwellerastro** [comment]
Sorry if I'm taking anything out of context.

In regard to bullet 2, if you already have a test involving line scan images and a solution including spsolve=position (or other values), then you can set overhermite=yes.  Ideally you would have a network that has some ground points in it when solving for spacecraft.  If you have a Themis IR or CTX network for testing you might be able to satisfy 2.  I can help with a very small themis network with ground if you need something.

Tammy primarily worked with Radar data for the LROC mission (mini-rf).  Jac was involved and might be able to help get a small set of data together.  Or you might want to troll Ken's directories for mini-rf references.  This might not be a quick throw together net.  And from what I recall, Tammy almost never was ever able to use the system version of jigsaw to bundle radar.  Ken always had her point to a special area.  Maybe that was resolved and checked in and I'm just unaware.

**Comment by jessemapel** [comment]
We already have a radar dataset for the current radar test. I think the issue is how do we convert it into the format we are using for the new test images where we have an ISD and a cube label.

I agree with Lynn on overhermite, the radar dataset would be the best usecase for overhermite, but all it requires is a time dependent dataset that solves for position. We can use the existing LRO NAC dataset for this.

I can also sit down sometime and go over the scconfig stuff it is not terribly complex and the data to use for it is just the apollo data set and the lronac data set together.

**Comment by jessemapel** [comment]
Fixed in #4463
