### ISSUE TITLE
Question about pvl implementation in notebooks

### ISSUE THREAD

**Issue by rbeyer** [DOI-USGS/ISIS3#4178]
Hey, @AustinSanders and @kaitlyndlee I noticed #4159 the other day, and read through the notebooks, and had some questions.

I noticed that you implement a `RealIsisCubeLabelEncoder()` class which provides an override of the `encode_time()` function, but I cannot figure out what that does differently from the default `pvl.encoder.PVLEncoder()` that `pvl.encoder.ISISEncoder()` inherits from, so I'm clearly missing something.  And whatever it does, if that's how "ISIS" should encode Python `datetime`s into strings, then we should probably change it in `pvl`.

I also note that later on in the notebooks, when `pvl.dump()` is called, you add octothorpe(#)-comments (`pvl` 1.1.0, coming soon, will have that included).  However, while the `pvl` library properly "reads" comments on a `pvl.load()` it does not "keep" or "manage" them in the dict-like that is returned.  Thus, when "dumping" there are no comments to write out, so I'm not sure why you bothered with instantiating a grammar object to add octothorpe-comments, when the encoder doesn't do anything with them.  So again, I'm very likely missing something.

**Comment by AustinSanders** [comment]
@rbeyer I've messed around with it a little more this morning, and we can definitely just remove the "RealIsisCubeLabelEncoder" in favor of pvl's implementation of ISISEncoder().

The code was originally written ~1 year ago, and I remember running into an error (which I can neither remember nor replicate) that was _seemingly_ resolved with the implementation of the "RealIsisCubeLabelEncoder."  I think it had to do with the inclusion of utc_offset being encoded into the strings as part of the PVLEncoder class's implementation of encode_time, but this functionality has since been moved to the ODLEncoder.

**Comment by rbeyer** [comment]
Ah, yes, I was in the middle of the `pvl` re-write a year ago, who knows what was going on then?  Alright, I just wanted to check and see if there was anything else that needed adjusting in the `pvl` codebase.  Thanks!
