### ISSUE TITLE
Evaluate OpenJPEG 2.3/2.4 replacement for kakadu

### ISSUE THREAD

**Issue by AndrewAnnex** [DOI-USGS/ISIS3#4237]
**Description**  
In the past 2 years, JP2 support has improved in the open source OpenJPEG project, with a _very_ recent [2.4.0 release](https://www.openjpeg.org/2020/12/28/OpenJPEG-2.4.0-released) further improvements were made thanks to funding from ESA for Copernicus Sentinel-2. Since OpenJpeg is already a dependency, maybe kakadu/the JP2 support in ISIS could be refactored to use OpenJpeg instead. Without deep understanding of either API or how ISIS uses Kakadu, I am not sure if this is what happens already if Kakadu is not available during isis compilation or not, or what ramifications there are for this change. 

If this has been considered for less recent versions of this library, maybe it is time for a new look to see if it can work/what issues remain with openjpeg. 

Switching would simplify some licensing considerations

**Comment by jessemapel** [comment]
We have to have some extra stuff in our build system and the development environment to support Kakadu, so if openjpeg provides a good (read fast) replacement then I am all for this.

**Comment by jessemapel** [comment]
Currently, ISIS falls back to the QT default of Jasper for JPEG2000 support when Kakadu is not supported. We could add a QT plugin for OpenJPEG if we want to use it instead.

**Comment by jlaura** [comment]
@thareUSGS Have you done any recent testing of JP2K support in these OS libraries? Any thoughts on this request?

@audiefen @artmathgirl Have you all tried any other libraries for non-proprietary jp2k support of HiRISE data?

**Comment by audiefen** [comment]
@jlaura I asked around with our developers. It's been a few years since anyone has investigated other libraries here at HiRISE.

**Comment by AndrewAnnex** [comment]
mostly an anecdote, but I was able to run `gdalinfo -hist` on a file I had laying around (ESP_062584_2030_RED.NOMAP.JP2) on a mbp laptop with gdal 3.2.1 (openjpeg 2.3.1), and it was able to run and finished in 220 seconds, but Jasper for a older version of gdal just printed an error saying it couldn't even read the file at all. I don't believe openjpeg will be faster than kakadu, but at least it works. It looks like the gdal on conda forge hasn't been updated to use openjpeg 2.4.0 yet or I just wasn't having luck with the SAT solver today

**Comment by thareUSGS** [comment]
@AndrewAnnex time aside, was the histogram the same across OpenJpeg and Kakadu? We should run some tests like that using each driver to make sure they are numerically the same (before changing). I have used OpenJpeg quite a bit, but not for a critical workflow yet.

**Comment by AndrewAnnex** [comment]
@thareUSGS I don't think I know of a way of directly using the kdu utils to calculate a histogram, or I don't the ability to compile gdal with kakadu to test the jp2kak driver directly, I could use the utils to convert to geotiff then compare the histograms directly that way?

**Comment by thareUSGS** [comment]
@AndrewAnnex I have an older build of GDAL with kakadu we can use. Actually if you have an older 64bit linux OS sitting around, this old build (w/ Kakadu) should still work: ftp://pdsimage2.wr.usgs.gov/pub/pigpen/GDAL/

What we use to do before Anaconda...

**Comment by thareUSGS** [comment]
related to this topic, there is a 2016 forked version of OpenJpeg, called Grok, which has started making its way into GDAL. As it has a AGPL license (not "friendly" for commercial use), it may only become optional as a external library (if at all). Long thread to read about it here: https://github.com/OSGeo/gdal/pull/3449

Funny to see HiRISE Jp2s used for their benchmark testing. :-). 

summary benchmarks:

**Compress**
Test image lossless- compressed with many small tiles.
Kakadu is 2X faster than Grok, which is 5X faster than OpenJPEG.

**Decompress**
Test image: single-tiled image of Mars
Kakadu is 60% faster than Grok, which is 2.5x faster than OpenJPEG. And memory usage for Grok and OpenJPEG
is ~ 500X higher than Kakadu.

**Decompress region** : {1000,1000,5000,5000}
Kakadu is only 40% faster than Grok, which is 5X faster than OpenJPEG

**Comment by jessemapel** [comment]
It sounds like OpenJPEG is going to be significantly slower then :(

**Comment by AndrewAnnex** [comment]
maybe it's just me, but depending on the exact situation, 2x slower for grok (the worst case from above) isn't that bad. The memory usage is more concerning but it also depends on the exact numbers again. I guess the question is where is jpeg2000 used in ISIS currently? It seems like only 3 tools mention it directly (isis2std, std2isis, apollopaninit), so I imagine the slowdowns would occur in those spots alone.

**Comment by thareUSGS** [comment]
If they had implemented the 32bit floating point support (which is part of the JP2 spec), I might be much more interested in continuing to support the use of JP2. But there is enough stuff happening under the hood for GeoTiff (COG, WebP, LERC, Sparse tiles) and other formats for me to allow JP2 to slowly go away. When HiRISE is migrated to PDS4 (which currently doesn't allow JP2), that might be JP2's nail in the coffin (for me). Again for me, supporting JP2 really starting going downhill when Kakadu pulled back allowing open source projects free use of their driver.

I am going to "backwards" answer the next question. Yes to slowly dropping JP2 support all together. But also yes to weaning ourselves from Kakadu and eventually transition to openjpeg in one form or another in ISIS.

**Comment by AndrewAnnex** [comment]
that's important context @thareUSGS, are you also saying that rather than using openjpeg you are open to dropping JP2 entirely rather than supporting it through a slower library?

**Comment by rbeyer** [comment]
The decision for HiRISE to use jp2k was made more than 15 years ago, when the possibilities for what JP2K could become were still unknown.  I'd have to agree with Trent that they are largely unrealized, and that there are other reasonable file format options that don't have the software development hurdles that jp2k does.

One of the advantages of jp2k to the HiRISE team was its ability to "stream" well to compliant clients.  Downloading a whole HiRISE image just to look at it is still complicated, but it was a nightmare 15 years ago.  I think that improvements in web-mapping technologies have largely rendered that advantage of the jp2k ecosystem less valuable, too.

JP2K is *only* used as a file format by HiRISE at the very end of the processing pipeline for derived, typically (but not always) map-projected data.  As Trent says, if and when HiRISE moves to PDS4, there will simply be no jp2k files in the HiRISE PDS4 archive.  Some other choice will need to be made for the format of those derived images which are currently archived as jp2k under PDS3.

**Comment by AndrewAnnex** [comment]
@rbeyer so it sounds like the impact of this change (for hirise) would be pretty much limited to people running std2isis on derived products from hirise? From what I can tell, it sounds like openjpeg (or grok, license permitting) could be used to retain compatibility with pds3 hirise products, albeit with a speed reduction. 

Do you have a sense for how deleterious this could be, beyond the slowdowns listed above?

**Comment by rbeyer** [comment]
From time to time, HiRISE learns something new about the instrument, and we adjust the calibration process.  Typically when this happens, HiRISE engages its computing cluster to "reprocess" all (yes, all) of the PDS-delivered derived data products.  Since there is a conversion to jp2k at the end of every one of those pipelines, for every HiRISE derived product (which is some multiplier against the number of observations), this slowdown could have a real impact on that process.

HiRISE has a requirement to archive to PDS3.  Changing libraries to make "licensing considerations" easier could have a real, financial impact on HiRISE PDS processing.

Don't get me wrong, I am all on board with the spirit of the change, but it has some real consequences.  Since I don't think any other operation within ISIS really depends on jp2k other than HiRISE (to my knowledge no other instrument or mission archives in jp2k, but I could be wrong), seems like we should just let things lie.

If there is a way to add this new jp2k library as an option, while still preserving the speedier kakadu functionality, that would be fine, but given the very low use case of the jp2k library for anything other than HiRISE, I'm not sure that there is a big reason to change.

**Comment by thareUSGS** [comment]
@rbeyer sorry this is getting to be a long thread. Correct me if I am wrong, doesn't HiRISE use an external program to convert the "final" cube to JP2? So if this proposed update only impacts ISIS's use of Kakadu, I don't see the impact to the HiRISE pipeline? Maybe if you are coming back from JP2K to ISIS?

I recall this was a separate application (maybe even in JAVA), since that is how the use of a GIS header was added to the map projected HiRISE JP2 files. ISIS has never supported embedded GIS headers for export. It has supported external worldfiles during export (but never the map projection and never an embedded GIS header -- that is why we started supporting GDAL :-).

**Comment by rbeyer** [comment]
Look at me assuming things.

You are right.  Whew, the real answer is messier than I thought (see below--if you dare!), but the upshot is that no, no HiRISE pipelines actually do run std2isis which would use the jp2 library in ISIS.  So my objection is moot!

For products that are not map-projected that need to be converted to jp2, HiRISE runs a Perl program which runs `isis2raw` and then `kdu_compress`.

For the DTMs, there does appear to be a Java program that's used for conversion, and there's also some C++ conversion code, maybe that's used for the orthos and other stuff, but I can't quite tell how everything is related without spending much, much more time sifting through things.

Anyway, internal-to-the-team HiRISE processing does not rely on the jp2 library in ISIS, so change away, I guess.

**Comment by jlaura** [comment]
This has been a fun conversation to watch evolve. Thanks to everyone that has participated! Here are my thoughts on what I would like to see before a PR came in for a change (or alongside a PR understanding that the PR would not be merged until the below was completed and discussed broadly).

Given the potential impact of this change (outside of the discussion about the HiRISE processing pipeline), I would like to see an RFC with recent timing benchmarks using HiRISE data. I would also like to hear from a broader swath of our user community about the impact of a change like this given that the current setup 'works as intended'. Concrete examples are going to be critical here. (I have appreciated the discussion about PDS4 and HiRISE's eventual transition.)

The RFC could and should address what the pros/cons of the decision are, what the impact will be on users, what happens if nothing changes, and, in this case, what the revert plan would be if the change is impactful in ways that we did not anticipate.

**Comment by boxerab** [comment]
Hello, Grok developer here. Interesting discussion!
I'm not familiar with PDS4 format, but are you all saying that JP2 is not yet supported, or will never be supported ?
If so, what compression format will be used ?
Also the comment about floating point, may I ask what is the use case for floating point data? It's going to be much slower to process than 10 bit, of course.

Finally, if everything works out this year, Grok should reach or exceed Kakadu performance, as well as dramatically reduce its memory usage.

**Comment by rbeyer** [comment]
I'll let someone else comment on the PDS4 standards (PDS4 isn't a "format" but a system with requirements for how NASA missions must archive data, don't worry, people often use the term "PDS4 format," even people that should know better).

As far as the use case goes, instruments like HiRISE fundamentally capture data in an integer type, and "raw" data are certainly archived in that mode.  After the image is on the ground, scientists want to understand how those integers (which represent an electron count from the detector) relate to a real physical quantity as independent of the instrument as possible.  For images, this is typically the ratio of the reflected flux from the planetary surface over the incident flux.  As you can imagine, this is a real type between zero and one, and images with pixels of this quantity need to be archived with the PDS.

Now, you could successfully argue that since the original image was in integer values, that surely, any math that you apply to them to "convert" them to a real value is really just a kind of mathematical illusion, since that information could still be represented by an integer value by applying a single scale and offset, and you'd be right.  Unfortunately we then also typically make derived products from those products. We need to map-project those images together, or blend them together into a mosaic, or do other operations. These operations and more disrupt the nice, orderly relation to original integers.  Could you take that data at the end of whatever is done to it, and represent that data as high-bit integers in some clever way minimizing the loss of precision?  You probably could, but then we go down the rabbit-hole of what's the easiest format to use for planetary scientists and others that aren't as conversant about the details of the bits and bytes.  Sometimes, it is better to accept slower operations or larger file sizes if those files can be used by a wider swath of folks.

Ultimately, for a variety of reasons, we end up with an image with pixels that are of a real value, and they must be archived.

**Comment by boxerab** [comment]
@rbeyer thanks. So, currently, floating point values in range [0,1] are converted to pixels just before conversion to jp2, I guess by simply multiplying by (2^precision-1) for specified number of precision bits. If the compression were applied to the original floating point values, then there should be less loss of precision vs just chopping off all values at 1/2^(precision) . Is there any floating point compression used in the wild at the moment?  FP is in Part 2 of the JPEG 2000 standard, and both Grok and OpenJPEG are currently limited to Part 1. But Kakadu would handle it.

**Comment by AndrewAnnex** [comment]
The geotiff format makes a variety of floating point compression options available just as an example https://gdal.org/drivers/raster/gtiff.html. Although I don't know if there are any examples of floating point compression within PDS3/4 standards.

**Comment by boxerab** [comment]
Thanks, @AndrewAnnex. As long as it's possible to decode a subset of the data, which I believe is possible through tiff tiling, then it could be a workable solution.

**Comment by AndrewAnnex** [comment]
@jlaura is the procedure for opening an RFC to use the template from the wiki in this repo to make a post in astrodiscuss? I don't really have the bandwidth to collect benchmarking data for these libraries at the moment even if someone hands me a list of docker containers to use, but I can at least open the RFC

**Comment by jlaura** [comment]
@AndrewAnnex Yup - go ahead and open the RFC using the template. Please feel empowered to ask for help testing in the RFC.

**Comment by AndrewAnnex** [comment]
done! https://astrodiscuss.usgs.gov/t/rfc-7-evaluate-use-of-jpeg2000-in-isis/713

**Comment by jlaura** [comment]
The PR has been open for > 1 month and discussion seems to have come to a natural conclusion. Therefore, I am going to motion that this RFC be adopted as written and that a PR be opened to remove Kakadu and use the OpenJPEG library. The AGPL license on Grok, I believe, precludes us from being able to link because we are not in a position to adopt the AGPL license.

See: https://www.gnu.org/licenses/gpl-faq.en.html#GPLStaticVsDynamic for a discussion on linking and why I am suggesting OpenJPEG (due purely to licensing issues).

**Comment by jlaura** [comment]
@acpaquette Can we get this change pulled in under the dependency management work? The RFC has been accepted, so we can remove Kakadu an replace it with OpenJPEG. I do not have a good feel for the overall scope of work.

@Kelvinrr Did you do some work on this too?
