### ISSUE TITLE
Make new Galileo and Voyager SPICE kernels for Europa available

### ISSUE THREAD

**Issue by blandoplanet** [DOI-USGS/ISIS3#4254]
**Description**  
The USGS has generated new ck for Galileo, Voyager 1, and Voyager 2 images of Europa as well as an accompanying pck. It would be great to include these such that a user could simply use the cksmithed=true flag in spiceinit. The requirement that the proper (i.e., new) pck is also picked up may complicate this. 

An additional question is timing. We are still working on the metadata and publication that describes how the kernels were generated. Do we need to wait until those become public before the kernels are made available?

The kernels can be found here /archive/projects/europa/Kernels/

**Comment by lwellerastro** [comment]
More specifically:

Galileo SSI:
/archive/projects/europa/Kernels/Galileo/galssi_eur_usgs2020.bc
/archive/projects/europa/Kernels/Galileo/pck00010_msgr_v23_europa2020.tpc

Voyager 1:
/archive/projects/europa/Kernels/Voyager1/vg1_eur_usgs2020.bc
/archive/projects/europa/Kernels/Voyager1/pck00010_msgr_v23_europa2020.tpc

Voyager 2:
/archive/projects/europa/Kernels/Voyager2/vg2_eur_usgs2020.bc
/archive/projects/europa/Kernels/Voyager2/pck00010_msgr_v23_europa2020.tpc

The pck file in each directory is identical.

Each directory also includes the pds file location (local) for images covered by the respective kernel and has the format local_pds_edrs_*.lis.  All listed files will be covered by the kernel, but there is one galileo file that will fail ingestion because it has a bad label (/pds_san/PDS_Archive/Galileo/SSI/go_0018/e4/europa/c037468/5452r).

Please let me know if there are any problems with initializing data using these kernels when/if someone has the opportunity to test the new kernels.  I will be glad to test things, but I thought I would offer the pds data since developers in the past have asked for data to test on.  Thanks!

**Comment by jlaura** [comment]
I used the thumbs up, but also want to post that this would be of high value to me.

**Comment by lwellerastro** [comment]
Hi - I have to add some images to the network and will be re-writing the kernels sometime later this week.  I won't touch what is currently in the directories mentioned so feel free to see what's there and think out the process if you need to, but know that what's there will be replaced.  Sorry for any inconvenience.  I'll update this post when I have replaced the kernels.

**Comment by jlaura** [comment]
@lwellerastro Thanks for the info and congrats on the product! I would anticipate that we get these into the system during the next mission/product support sprint to be scheduled sometime in March. So absolutely no timeline pressure on our side.

**Comment by blandoplanet** [comment]
Any chance these can be put into the system sooner under the continuous support task?

**Comment by lwellerastro** [comment]
FYI - the kernels have recently been updated and sync'd to locations specified above.  All set for ingestion into the data area when that happens.

**Comment by lwellerastro** [comment]
@kberryUSGS, each mission kernel directory also contains a local_pds_edrs*lis file pointing to raw data.  Feel free to use those for tests.  There are a couple images that won't ingest because of bad labels that require editing, otherwise they should all work.  I don't expect you to run all the data - I can/will do that, just let me know.  Thank you and hopefully this are easy to slurp in!

**Comment by krlberry** [comment]
These kernels have now been added internally and are available for use or testing. I ended up needing to add a small amount of padding and a time offset present in the camera model to the ISIS kernel db time ranges to get this working. The kernels will be released publicly with the next ISIS release.

**Comment by lwellerastro** [comment]
All images pick up smithed ck kernels under isis4.4.0.  Thank you and sorry @kberryUSGS my "local" galileo pds files were missing part of the path!

**Comment by acpaquette** [comment]
@blandoplanet Can this be closed?

**Comment by blandoplanet** [comment]
@lwellerastro has confirmed that the kernels are working as expected. I believe this can be close.
