### ISSUE TITLE
defunct `convert` in ISIS environment?

### ISSUE THREAD

**Issue by michaelaye** [DOI-USGS/ISIS3#4287]
**ISIS version(s) affected**: 4.3.0

**Description**  

Trying to use ImageMagick's `convert` a seamingly defunct convert popped up on my ISIS path:

```bash
$ which convert                                                              
$HOME/miniconda3/envs/isis/bin/convert
```
and I think it's broken, because the standard `convert` spits back its docs when called naked?

**How to reproduce**  

* install isis conda env
* activate isis env (or add its bin to path)
* find the convert on above path

**Possible Solution**  

Not sure. If it's a different thing, could it be renamed? Or, if nobody uses it, removed?

**Comment by jessemapel** [comment]
This isn't an ISIS application, it seems to be coming from a dependency somewhere. I'd say it's probably safe to delete.

I'm leaving this open as a question about if it's safe to delete, but this is likely an issue with an upstream package.

**Comment by michaelaye** [comment]
Not sure I understand upstream? Is this not the right place to create an issue with the Isis conda env?  Do you have an extra repo for that?

**Comment by jessemapel** [comment]
By upstream I mean a package that is a dependency of ISIS. One of the packages that ISIS depends on is adding that to the conda environment bin. It would be reasonable to figure out how to work around it here, but we can't fix it here because it's coming from another package.

If we can figure out what package is adding it then we should post an issue over on their feedstock/repo/bug tracker.

**Comment by michaelaye** [comment]
Got it. You think it’s part of some package you actually need so you can’t just kick out that whole dependency.

--
Michael Aye
LASP / CU Boulder

**Comment by jessemapel** [comment]
Okay, I did some searching and discovered you can figure out what package a file belongs to by searching `$CONDA_PREFIX/conda-meta/*.json` for the file path.

So, grepping for `bin/convert` in there indicated that it's coming from the embree package.

I dug a little more into that and it turns out it's just a tutorial executable. You can safely delete it. I'll also make an issue over on the feedstock to have it not build the tutorials.

**Comment by michaelaye** [comment]
Cool thanks!

--
Michael Aye
LASP / CU Boulder

**Comment by michaelaye** [comment]
I still (again?) have the defunct convert in 5.0.2. As usual it clashes with ImageMagick's convert in my PATHs.

**Comment by jlaura** [comment]
Quoting @jessemapel's previous reply.

> Okay, I did some searching and discovered you can figure out what package a file belongs to by searching $CONDA_PREFIX/conda-meta/*.json for the file path.

> So, grepping for bin/convert in there indicated that it's coming from the embree package.

> I dug a little more into that and it turns out it's just a tutorial executable. You can safely delete it. I'll also make an issue over on the feedstock to have it not build the tutorials.

@michaelaye If this is a package that ISIS is requiring, we should have an issue here. If this is a dependency that one of our dependencies is installing, please open an issue on the appropriate feedstock.

**Comment by jessemapel** [comment]
Embree is a dependency of ISIS. The move to conda-forge Embree will fix this. For right now, the work around is just delete the `convert` in the conda bin.

**Comment by michaelaye** [comment]
> I'll also make an issue over on the feedstock to have it not build the tutorials.

I was referring to this statement that was presumably fixing this issue.

**Comment by jessemapel** [comment]
@michaelaye Sorry, tagged it over there now.
