### ISSUE TITLE
Kaguya TC - problems projecting pole crossing images

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#4420]
**ISIS version(s) affected**: 4.1.0 also seen in isis4.4.0 and isis5

**Description**  
cam2map makes no progress when polar projecting Kaguya TC images that cross the poles and are initialized with a global DEM. I am working with a subset of the available data, but 168 of 807 images could not be projected.

Images within 0.1 degree of the south pole having the same DEM project as expected, but those that contain the pole do not or take >24 hours to do so (about 2 dozen in this bin).  There are a couple of random images that are not near the pole that also result in no progress but the majority of failures/no projection contain the south pole.  I allowed the images to project over the weekend with no time limit and had to kill the process when I saw they will still running after 2 days.  After some testing I confirmed the problem.

These image were initially spiced using a special global merged DEM (kaguya sldem overlaid on global LOLA dem to fill in the poles) so I did some tests allowing spiceinit to default to system global DEM.  cam2map would not work in that case either. It just sits and does nothing.

All site images had previously been processed and projected while using a LOLA polar DEM (extends from 60S to 90S).  Each image took only minutes to project.  Defaulting to the ellipsoid works as well.  Only global DEMs fail for the specified images.

**How to reproduce**  
See data under /work/users/lweller/Isis3Tests/Cam2Map/KaguyaTC/
TC1S2B0_01_04808S893E0479.lev1.defaultDEM.cub
TC1S2B0_01_04808S893E0479.lev1.PolarDEM.cub

*defaultDEM.cub points to default global DEM and PolarDEM.cub points to a polar projected LOLA DEM.

```
This one goes nowhere
cam2map from=TC1S2B0_01_04808S893E0479.lev1.defaultDEM.cub to=TC1S2B0_01_04808S893E0479.lev2.defaultDEM.cub map=spole_clon0_20m.map pixres=map 

This one succeeds
cam2map from=TC1S2B0_01_04808S893E0479.lev1.PolarDEM.cub to=TC1S2B0_01_04808S893E0479.lev2.PolarDEM.cub map=spole_clon0_20m.map pixres=map 
```
I'm using a lower resolution for these data for quick analysis.

**Additional context**  
I map projected the default LOLA DEM to pull out the south pole to see if there were any issues there and it looks fine to me.

I can successfully project LROC NAC north and south pole images (containing their respective poles) using the default global dem.
There are other lunar datasets I have worked that have used the LOLA and ULCN global DEMs that did not have projection problems.
 
The successful LROC data are under /work/users/lweller/Isis3Tests/Cam2Map/KaguyaTC/LROCNAC/ as a comparison, including the print.prt for a record of what was run.

**Comment by acpaquette** [comment]
After examination of the camera model and relevant code in both ISIS and [ALE](https://github.com/USGS-Astrogeology/ale) it looks like this is not inherently an issue with the KaguyaTC camera model. These images take a long time to project as some pixels are unable to intersect the DEM. To handle this would likely require a look into how ISIS intersects a DEM and potentially devise a new algorithm to do so. Currently ISIS uses a convergent method to solve for radius where we intersect the target, get the radius from that intersection, then intersect the target again with the new radius, and this repeats until we converge to a single surface point. The KaguyaTC pointing/position combine with the ldem DEM seem to result in the algorithm being unable to converge, hopping around between some number of points on the DEM. 

So far it appears to be an issue with resolutions of the image and DEM along with the pointing of the KaguyaTC model not playing nice with the convergent DEM intersection algorithm. It also may be an issue with the DEM projection, trying to intersect a polar image against a simple cylindrical DEM but this is unlikely.

So far I have exhausted my search into this problem and don't know a good way to progress this issue. The main work-around currently is to project the DEM used with some of the erroneous polar KaguyaTC images into a `polarstereographic` projection. The reason this works is not due to the projection but due to the DEM itself being resampled to smooth out the seem that is created near the pole. 

This is still an issue and should be explored further by someone who has a better feeling/understanding of terrain intersection.

**Comment by jessemapel** [comment]
I did some more digging on this and it appears that the radius in the DEM varies dramatically near the south pole. What's happening is that the algorithm cannot converge because the radius changes so rapidly in a small area. Here are some plots I made of the local radius as the algorithm attempts to converge for a single intersection at -89.99 latitude.

First here's the local radius (in Km) at each of the 100 iterations

![Screen Shot 2021-08-17 at 2 05 40 PM](https://user-images.githubusercontent.com/22942817/129800570-8649a6a2-d0a3-4193-aadb-4ddc1aca8fcd.png)

The next plot is a 3D plot of DEM projection x/y with local radius.

![Screen Shot 2021-08-17 at 1 44 44 PM](https://user-images.githubusercontent.com/22942817/129800313-51fb7d7e-0783-4dcd-9f59-50fa98c0f8ee.png)

The last plot is a polar projection of the ground points (I took 90+lat as radius and lon as theta) with points colored by their local radius.

![Screen Shot 2021-08-17 at 2 00 50 PM](https://user-images.githubusercontent.com/22942817/129800396-22c226ef-b9b5-4ba7-aa55-c7b378195bda.png)

This seems like the DEM varies quite drastically near the poles. I'd expect the radius to "converge" as we get close to the poles, but that isn't happening here.

@thareUSGS @lwellerastro what's the origin of the polar data in the DEM? I tried running cathist but didn't get much from it.

**Comment by jessemapel** [comment]
I should also add that I used a median filter to smooth out the very edges of the DEM and it resolved this problem. That seems like a very brute force may to handle this so I'm curious if there's a better way to handle it.

**Comment by lwellerastro** [comment]
I tried various global DEMs and they all had problems, but they are all different products.  Which file were you working with?  It looks like in my post I kept with what's in the system.
The isis system default (lola): $base/dems/ldem_128ppd_Mar2011_clon180_radius_pad.cub

Another version of the above but newer/better resolution (lola): /archive/projects/TOPO/LOLA_MAR2014/LRO_LOLA_Global_LDEM_118m_mar2014_radius.cub

Tammy/Ken special product (merge of lola polar dem and kaguya dem): /work/projects/Apollo/DEM/LRO_LOLA-KaguyaLPF3-mrg_Global_512ppd_radius-demprep.cub

I can't tell you anything about the system version or the 2014 global version I have used extensively over the years for multiple projects, but give me a minute to get you the details of the Tammy/Ken DEM which is my preference to use.

**Comment by jessemapel** [comment]
I tested using the system default one, let me test out the one in archive.

**Comment by lwellerastro** [comment]
My first choice for a global DEM was a merged product that Tammy and Ken created back in 2015 after we received a copy of a new DEM based on Kaguya TC stereo data.  The version they received directly from @thareUSGS (I have old emails for all of this) is identical to what's under /archive/projects/TOPO/LOLA_Kaguaya_Merge_Feb2015/LRO_LrocKaguya_radiusDEMmerge_60N60S_512ppd.cub.

The Kaguya DEM only extends to +/-60 latitude so they made a global DEM by merging it (mosaicking) with one of the global LOLA DEMs. They preferred the Kaguya over LOLA because it is of higher resolution - Kaguya's 512ppd / 59.2m/pix versus 2014 LOLA's 256ppd/ 118.4m/pix.

Below is what I have pieced together from some notes in their /work/projects/Apollo/DEM/ directory and histdump against various files in that directory, and what was recommended I use via an email from around 2015:

- 3x3 lowpass filter on Kaguya DEM to smooth out obvious tracks
- enlarge (lscale=2 sscale=2) the 2014 global LOLA DEM (mentioned above) to match the Kaguya DEM scale
- copy enlarged LOLA DEM to global DEM filename
- mapmos 3x3LPF Kaguya DEM on top of copy of enlarged LOLA DEM
- demprep this final merged mosaic to get the merged shape model statistics information written to the label

I started with this product and had problems so I tried the system default global LOLA DEM and had problems there as well (and then the 2014 LOLA DEM), so I reported on that because I thought Kaguya was the real problem.  I thought these were different DEMs but maybe when it comes to the poles, the LOLA DEM global products aren't fundamentally different.  I honestly don't know those details.

Astro lunar projects have been using the 2014 global LOLA DEM for quite some time now because it has better resolution (118 m/pix) than the system default (236.9 m/pix) so it is surprising to me that it's now an issue.  This includes data that has crossed the poles.

What does seem to work is if I use one of the polar projected LOLA DEMs for these problem images - /archive/projects/TOPO/LOLA_MAR2014/LRO_LOLA_SPole60S_LDEM_60m_mar2014_radius.cub.  However I really need a global DEM for a global dataset with hundreds of thousands of images, which is why I started working with TB/KE dem.

`I should also add that I used a median filter to smooth out the very edges of the DEM and it resolved this problem. `
Hmm, wouldn't running enlarge on the LOLA DEM smooth things out some as well?  Are the edges jagged in some way?

Any idea why I can use these same DEMs and project LROC polar data fine?  Maybe not hitting precisely the same locations and the Kaguya example?

**Comment by thareUSGS** [comment]
Since these LOLA DEMs interpolate the original shot data in this output projection (Simple Cylindrical), polar areas are going to get messy (even though they are using a anisotropy setting in GMT of 0.5 to help minimize latitude distortion). Ideally for polar areas, a polar DEM should be used.  The latest global file at 128ppd (236.9 m/p) at the PDS is from 2017 which we should switch to at a minimum. The PDS "img" versions at 128ppd is 2GB which is 16bit signed (w/ offset and scaler to get to radius).
https://pds-geosciences.wustl.edu/lro/lro-l-lola-3-rdr-v1/lrolol_1xxx/data/lola_gdr/cylindrical/img/ldem_128.lbl
https://pds-geosciences.wustl.edu/lro/lro-l-lola-3-rdr-v1/lrolol_1xxx/data/lola_gdr/cylindrical/img/ldem_128.img

LOLA supports higher resolution (sort-of up to 512ppd [~60m/p] globally - but 256ppd [118m/p] feels safer globally (not as many pixels interpolated over the gaps). And LOLA supports 5m/pixel at the poles. 

How much can/should we support for ISISDATA?  Should we support the much better polar DEMs too?

So the 128ppd will be about 2GB, the 256ppd will be ~8GB (good compromise?), The LOLA 512ppd will be ~32GB (which is also the size of the "hybrid" Kaguya [-60 to 60 lat] merged with LOLA).

**Comment by lwellerastro** [comment]
`I should also add that I used a median filter to smooth out the very edges of the DEM and it resolved this problem. That seems like a very brute force may to handle this so I'm curious if there's a better way to handle it.`

@jessemapel, can you be more specific, this is not working for me.  I ran a median filter (isis median program) on my global merged dem (TB/KE version) using a 3x3 boxcar, initialized TC1S2B0_01_04808S893E0479 with it and am now attempting to project.  It's been nearly 10 minutes with 0% progress on cam2map - it's not working.  Did you do something different?

There was virtually no difference between the input and output median DEMs files.  The only places I saw anything dramatic (on the level of 2-3 meters diff) was in some crater bottoms and rims when comparing the two in qview and using the 2d tool.  Running stats on a ratio of the two shows they are essentially identical.  Maybe you smoothed using a larger boxcar?

@thareUSGS I agree that at the very least we should replace the system 128ppd ldem with the latest version (2017) at the same scale.  I think the latest (2014 I think) at 256ppd would be better, but there seemed to be some controversy long ago about doing this and there is a post out there (at least there used be under old support) with there being some objections from outside of Astro.  I never understood the issue and we never made any move on putting anything better out as the default.  I understand why we don't necessarily offer ALL of the LOLA dems - the data area is bloated as is and downloading it is cumbersome for those outside of astro.  We should at the very least provide a better global version though.

**Comment by jessemapel** [comment]
@lwellerastro I used GDAL to open up the cube and manually apply a very wide, 100s of samples, median filter to the top and bottom 5 lines of the image. I didn't apply a median filter to the whole thing as we don't want to touch the non-polar data.

**Comment by lwellerastro** [comment]
After additional conversation, I am going to close this post.  

It seems the combination of the Kaguya TC look angles (off nadir) and the "roughness" of the extreme poles in the available global dems is not a good match for the algorithms.  Other datasets I have successfully worked with tend to consist of a nadir pointing camera(s) likely resulting in an intersection area that is less varied allowing the algorithm to converge with a lat/lon for a point.

@jessemapel please feel free to correct, clarify and add to my comments.  Thanks for helping me better understand the problem.

**Comment by jessemapel** [comment]
@lwellerastro Your explanation is spot on. I'll open a new enhancement request about allowing for multiple DEMs to help deal with situations like this one.
