### ISSUE TITLE
cnetpvl2bin fails when some keywords are in all caps

### ISSUE THREAD

**Issue by jeanlucmargot** [DOI-USGS/ISIS3#4440]
**ISIS version(s) affected**: x.y.z

  IsisVersion       = "4.4.0  | 2021-02-04"
  ProgramVersion    = 2011-04-05

**Description**  

cnetpvl2bin correctly translates a PVL file with keywords in all caps, except for three keywords: 
GoodnessOfFit, MinimumPixelZScore, MaximumPixelZScore.
If these keywords are present in all caps, cnetpvl2bin fails with:
```
**I/O ERROR** Reading the control network [bugreportallcaps.pvl] failed.
**I/O ERROR** Failed to initialize control point at index [0].
**PROGRAMMER ERROR** Unhandled or duplicate keywords in control measure [GOODNESSOFFIT].
```
**How to reproduce**  
Start with sample PVL file ('bugreport.pvl')
```
Object = ControlNetwork
  NetworkId    = Null
  TargetName   = Null
  UserName     = Null
  Created      = 2021-03-25T10:49:02
  LastModified = 2021-03-25T10:49:02
  Description  = Null
  Version      = 5

  Object = ControlPoint
    PointType   = Free
    PointId     = 1001
    ChooserName = jlm
    DateTime    = 2021-03-25T10:52:32

    Group = ControlMeasure
      SerialNumber       = second.cub
      MeasureType        = RegisteredSubPixel
      ChooserName        = Unknown
      DateTime           = 2021-03-25T10:52:32
      Sample             = 229.5178605141
      Line               = 419.63950219981
      AprioriSample      = 231.71084337349
      AprioriLine        = 420.44578313253
      GoodnessOfFit      = 0.81135752710818
      MinimumPixelZScore = -1.8473730903338
      MaximumPixelZScore = 2.6775119776801
    End_Group

    Group = ControlMeasure
      SerialNumber = first.cub
      MeasureType  = Manual
      ChooserName  = Unknown
      DateTime     = 2021-03-25T10:52:32
      Sample       = 376.90361445783
      Line         = 293.38554216867
      Reference    = True
    End_Group
  End_Object
End_Object
End
```

Create an all caps PVL file:
```
$ python
>>> import pvl
>>> label = pvl.load('bugreport.pvl')
>>> pvl.dump(label, 'bugreportallcaps.pvl')
```

$ cnetpvl2bin from=bugreportallcaps.pvl to=bugreportallcaps.net
**I/O ERROR** Reading the control network [bugreportallcaps.pvl] failed.
**I/O ERROR** Failed to initialize control point at index [0].
**PROGRAMMER ERROR** Unhandled or duplicate keywords in control measure [GOODNESSOFFIT].

Modify three all-caps keywords:

```
cat bugreportallcaps.pvl |  sed -e s/GOODNESSOFFIT/GoodnessOfFit/g | sed -e s/MINIMUMPIXELZSCORE/MinimumPixelZScore/g | sed -e s/MAXIMUMPIXELZSCORE/MaximumPixelZScore/g > bugreportmostcaps.pvl
```

$ diff bugreportmostcaps.pvl bugreportallcaps.pvl
```
23,25c23,25
<       GoodnessOfFit      = 0.81135752710818
<       MinimumPixelZScore = -1.8473730903338
<       MaximumPixelZScore = 2.6775119776801
---
>       GOODNESSOFFIT      = 0.81135752710818
>       MINIMUMPIXELZSCORE = -1.8473730903338
>       MAXIMUMPIXELZSCORE = 2.6775119776801
```

$ cnetpvl2bin from=bugreportmostcaps.pvl to=bugreportmostcaps.net
[success!]

**Possible Solution**  

Apply same logic to the three offending keywords as all other keywords.  It's important to fix this bug because the PVL Python library changes all keywords to all caps.  Thank you.

**Additional context**

**Comment by jessemapel** [comment]
The reason those three keywords are different is because they are converted in the ControlMeasureLogData instead of the ControlNetVersioner classes.

An easy fix is to do a case-insensitive comparison in the ControlMeasureLogData: https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/control/objs/ControlMeasureLogData/ControlMeasureLogData.cpp#L187

Thank you for the great bug report!

**Comment by rbeyer** [comment]
Whoops, how did I miss this Pyhon *pvl*-related Issue?

@jeanlucmargot, you can get *pvl* to produce a lot of different output.  I think it is good to get ISIS to conform to the (admittedly poor) standard, and I'm glad that they're addressing this, but in the mean time you can do this:
```python
>>> import pvl
>>> label = pvl.load('bugreport.pvl')
>>> pvl.dump(label, 'bugreport_out.pvl', encoder=pvl.encoder.ISISEncoder())
```
Then the `bugreport_out.pvl` will happily be consumed by the existing ISIS cnetpvl2bin.

I also find it useful to use the new `pvl_validate` tool that comes with your install of Python *pvl*:
```
> pvl_validate bugreport.pvl
PDS3 | does NOT load |
ODL  | does NOT load |
PVL  |     Loads     |     Encodes
ISIS |     Loads     |     Encodes
Omni |     Loads     |     Encodes
```
This is also a reminder of the various "dialects" of PVL that *pvl* supports.  This shows that the file cannot be loaded by the strict rules of PDS3 PVL or ODL, but can be loaded by the more generic plain PVL, ISIS (no surprise, since it looks like ISIS created this PVL-text), and our "Omni" parser (which should be able to deal with most things).

The deal is that *pvl* uses the Omni decoder on `pvl.load()` and then, by default, the PDS3 encoder on `pvl.dump()` (which auto-caps the keywords, among other things), but it can be told to use other encoders.

You can find more info [here](https://pvl.readthedocs.io/en/stable/encoding.html#pvl-text-for-isis-program-consumption).

**Comment by jeanlucmargot** [comment]
Thank you both!  @rbeyer the ISISEncoder() did indeed provide a good solution until I upgrade ISIS.
