### ISSUE TITLE
map2map output adds a line of bad pixels at 0/360

### ISSUE THREAD

**Issue by blandoplanet** [DOI-USGS/ISIS3#4557]
**ISIS version(s) affected**: 5.0.1 and 4.4.0, probably more

**Description**  
I have a set of number of low-resolution mosaics of Europa that cross the 0/360 boundary. These are hard to look at in qview so I tried reprojecting them with map2map to put the center latitude at 0 (thanks @lwellerastro for the assist). The resulting output has a line of bad pixels at the 0/360 boundary. An example is shown below.

![image](https://user-images.githubusercontent.com/43620629/125868653-3cc499ee-9b97-45e8-b67f-0a4485819047.png)

The farthest left image is the original mosaic. The middle image is the mosaic reprojected with map2map (notice the vertical slice). The third image is a single cube that went into the mosaic projected with cam2map using the same map file (putting zero at center). I've included it here to show that the problem is with map2map and not the data.

**How to reproduce**  
All files can be found in /work/users/mbland/Europa-Control/Center. Simply run 

map2map from=G2ESPHOTOM01_GalileoSSI_Equi.cub map=G2.map to=G2ESPHOTOM01_GalileoSSI_Equi_Clon0.cub minlat=-87.287254596771 maxlat=90 minlon=-180 maxlon=180

and look at the output. NOTE: map2map seems to require maxlon and minlon to be specified on the command line. It's not reading it from the *.map file. I'll put in a second issue for this.

**Possible Solution**  

**Additional context**

**Comment by AustinSanders** [comment]
This issue has been a bit of an adventure.  I've looked into the map2map side of things, and map2map appears to be doing exactly what it's supposed to do.  The images coming out of cam2map are missing a pixel on the right side, so they only extend out to ~359.915º longitude.  Since there technically isn't data associated with 360º on these images, it's getting a strip of null values at the lon seam.

Taking this a step back to cam2map, and specifically the ProjectionFactory used in cam2map, the issue of the lost pixel appears to be a matter of resolution.  Since the cam2map call specified resolution in meters per pixel, there wasn't a "clean" mapping between the number of pixels and the data in the image, i.e. there was a partial pixel worth of data left over.  In the current version of ProjectionFactory, we calculate the number of pixels in the output image, then round the number of output pixels.  This means that we're dropping any pixel for which less than half of the data are valid.

I see a few ways of addressing this issue.  First, for edge cases like this, we can specify the resolution in pixels per degree.  In this way, we can choose a number of pixels such that the image divides up evenly and we are not left with any partial pixel data.  I used ppd = 4 (where the original ppd value calculated from the given mpp was ~3.97).  I've verified that this eliminates the strip of null pixels, and it is likely the solution that is "most correct," although I'm unsure of the ramifications of using ppd.

The second way of potentially solving the issue is to use a ceiling calculation rather than rounding the number of output pixels.  This ensures that we're getting all of the valid data, but several developers and scientists have raised concerns about altering this mechanic, as it would potentially warp / invalidate the longitude information associated with the image.  Additionally, we would be adding a full pixel to every projected image with a partial pixel, so this seemingly simple change could cause a huge ripple effect.  If using ppd is not a viable workaround, then we may be able to dig deeper into this.

Finally, we can project the image directly to [-180, 180] from cam2map.  This still leaves a strip of missing lat/lon data on the right side due to the issue described above.

@lwellerastro @blandoplanet what are your thoughts on the proposed workarounds?  I'm not sure how this can be resolved on the software side without causing some nasty changes for users.

**Comment by KrisBecker** [comment]
The easiest way to work around this problem is to expand your global map longitude extents to MinimumLongitude=-2.5 and MaximumLongitude=362.5 (or any other arbitrary extent beyond the exact 0/360 limits) of your source and then reproject using this map. You can also do this for 180 domain using -182.5, 182.5.

To retrofit this to an existing source map you cannot reproduce otherwise, you might try and run map2map on it using the new longitude extents and (important) also use INTERP=NEARESTNEIGHBOR. This prevents resampling. You may need to filter the result to fill only missing data. That would be the best option without the means to reproduce the map.

**Comment by lwellerastro** [comment]
Thanks @KrisBecker, you just reminded of past projects where data were projected (or reprojected?) from -0.5 to 360.5 longitude (or something along those lines) and I never understood why.  I guess that was the solution for this particular issue.  

This particular file that is being worked with has a camrange of lat +/-90 and lon 0-360 which is what cam2map used to project the file (and what's in the labels).  Are you suggesting cam2map should be run using minlon=-2.5 maxlon=362.5 to avoid this map2map problem or were you only suggesting running map2map that way?

**Comment by KrisBecker** [comment]
Yes, this can be applied in cam2map as well. automos does a good job with this technique, too. You can do these tricks with most projections, just don't change other parameters in your map file (i.e., resolution!) that could result in undesirable resampling until you are satisfied with the results. 

Just wanted to add that this is essentially a roundoff problem so some very small tolerance tweaks in projection faculties might work out just fine.

**Comment by lwellerastro** [comment]
Can confirm that @KrisBecker method works using @blandoplanet command line above with tweaks below: 

map2map from=G2ESPHOTOM01_GalileoSSI_Equi.cub map=G2.map to=G2ESPHOTOM01_GalileoSSI_Equi_Clon0.cub minlat=-87.287254596771 maxlat=90.0 **minlon=-180.5 maxlon=180.5 interp=nearestneighbor**
