### ISSUE TITLE
map2map does not read minlon/maxlon from the map file pvl

### ISSUE THREAD

**Issue by blandoplanet** [DOI-USGS/ISIS3#4558]
**ISIS version(s) affected**: 5.0.1 and 4.4.0 at least

**Description**  
When running map2map with a pvl that specifies the 'MinimumLongitude = ' and 'MaximumLongitude = ' the user receives the following error  
**ERROR** Unable to determine the correct [MinimumLongitude,MaximumLongitude]. Please specify these values in the [MINLON,MAXLON] parameters.

map2map runs successfully if 'minlon=' and 'maxlon=' are specified on the command line.  

**How to reproduce**  
Run map2map on a lev2 cube with a valid pvl map file that includes MinimumLongitude and MaximumLongitude. You can find examples to work with in /work/users/mbland/Europa-Control/center/

**Possible Solution**  

**Additional context**  
This is a minor inconvenience, but it would be nice to have our software correctly parse the pvl. Seems (naively) like it should be a quick fix.

**Comment by lwellerastro** [comment]
I encountered the same error in the case where both the latitude and longitude information were omitted from the map the file and was not entered on the command line.  I was expecting the program to do the math. 

One of the mosaics Mike and I were working with has a longitude range of 0-360 (data are split) and we were re-mapping it to +/-180.

**Comment by amystamile-usgs** [comment]
I did some digging into map2map and determined what may be happening. I used a map pvl with longitude domain = 180 and a cube with longitude domain = 360 with Minlon = 0.0 and Maxlon = 360. When running map2map with default parameters, it uses the cubes mapping group as the default range. That is, map2map uses the minlon and maxlon from the cube's mapping group rather than the map pvl. This does not include the longitude domain, so what ever domain is specified in the map pvl is what will be used. In this case, longitude domain = 180. Therefore map2map then converts minlon maxlon to this specified domain.
 
In Isis, the function used to convert these longitudes only converts if the longitude is outside the domain of -180 and 180. So in our situation minlon does not get converted due to 0 being within the -180 to 180 domain but maxlon is converted from 360 to 0. Thus we arrive at the error  `Unable to determine the correct [MinimumLongitude,MaximumLongitude]. Please specify these values in the [MINLON,MAXLON] parameters.` because it failed the if statement that min and max lons are equal. 

So the options are, if you want to instead use the map pvl's minlon and maxlon, to instead specify the default range to be MAP or as mentioned to manually specify the minlon and maxlon in the parameters. Also another option is to set matchmap = true which forces all the mapping keywords in the map pvl to be used. 

My question is, do we consider this a bug or is this expected output by the fact that map2map is trying to convert minlon and maxlon from the cubes mapping group while still trying to use the map pvl's longitude domain?

**Comment by amystamile-usgs** [comment]
The short explanation/solution is to say that by default, map2map grabs minlon/maxlon from the cube's mapping group rather than the provided map pvl. In order for map2map to use the map pvl minlon/maxlon, add the following command line parameters: `defaultrange=map`.

**Comment by blandoplanet** [comment]
Hmm. Okay, I think I understand (maybe). This does not appear to be a bug, just a misunderstanding of what the default behavior is. It does seem odd to me that if you provide a map pvl with minlon/maxlon specified ISIS doesn't actually use that unless you explicitly tell it to by using defaultrange=map. I wouldn't bother including it in the pvl if I didn't want ISIS to use it.

**Comment by jlaura** [comment]
Is this something that we should reopen and tag for a documentation change / improvement? Or should the default behavior change?

**Comment by lwellerastro** [comment]
For my test, I had a super minimal map file necessary and did not include a lat/lon range since we were just changing the longitude domain.  The longitude range was 0-360, clon180 and I too naively thought (and have experienced this in the past, at least I think I have) the program would simply change the longitude range to +/-180 when londomain=180, clon=0 and everything else the same in the pvl file. I wouldn't necessarily expect that if my longitude extents where something other than the entire globe.

Using matchmap=true is very common as is explicitly entering the min/max range, but in this very simplistic example I would assume ISIS would know what to do without explicitly having to be told.  There must be a reason for the current behavior we are not thinking about that would make changing it a bad thing.  So maybe clearer documentation would help.

`In Isis, the function used to convert these longitudes only converts if the longitude is outside the domain of -180 and 180.`

Curious - why is this the case?
