### ISSUE TITLE
Qnet - Point Editor Measure Search

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#4581]
**Description**  
It would be great if there was a way to search for an image name in the Measure drop down menus in the Qnet Point Editor Tool.  Due to the ever growing, redundant amount of data collected during missions, a point may have many hundreds of measures associated with it.  My current Titan global network often has points with well over 400 measures associated with it, and when I evaluate the network for high residual measures after a jigsaw run, I often spend an enormous amount of time looking for filenames in the drop down list (Right Measure in particular) or simply give up.  It would be great if I could start to type the filename in window and have it search/highlight filenames, or alternatively, copy and paste a filename into an adjacent box to do the searching (maybe like qmos's filename search).  Having a search function would be most beneficial for the Right Measure but it would get use for the Left Measure as well.

Even better would be if filenames/measures were ordered such that the highest residuals were at the top (in the case of having a jigsaw output network loaded), but I think that might be quite time consuming, but I honestly don't know.

**Comment by amystamile-usgs** [comment]
I was able to implement a way to search filenames within the drop down box that will auto fill upon search for both left and right measures. 

I could not find a feasible way to sort the filenames based on highest residuals. In the Qt API, there are only a few ways of implementing sorting which are mainly for alphabetizing the items in the drop down box. This means, if we want to try to sort based on residuals, we would have to implement a sorting algorithm in ISIS that may cause slow downs in the app's runtime especially if there are hundreds of measures. 

If it is helpful, I can at least sort the filenames alphabetically since this is currently not done. But this may not be necessary if you are mainly searching for the filenames. Let me know what you prefer. 

@blandoplanet since Lynn may be out this week.

**Comment by astrostu** [comment]
I'm interested in better drop-down list, too ... I would prefer that if you can't sort by a custom method (such as residual), that at the very least the measures be alphabetized, as they are when you go to create a point.

**Comment by lwellerastro** [comment]
`I was able to implement a way to search filenames within the drop down box that will auto fill upon search for both left and right measures.`

This is great! Sorting alphabetically sounds like it could be useful as well.  Is that automatic?  I'm not sure I would want it to be auto since new measures added while editing the point might get lost in the shuffle.  Currently they all go to the bottom of the list making it somewhat easy to find them.  So it depends on the situation whether one would want to sort or not. 

Could you please clarify something - are there two separate filename searches available, one for the right and one for the left measure? A user would typically spend most of their time actively parsing through the right measure drop down menu once a reference is set in the left measure window.  I would not necessarily want a search for a filename under the right measure drop down to be applied to the left measure window as well.  This might not be what was implemented, but I could not tell from your description.

Is there somewhere I can test this before it gets released?

**Comment by amystamile-usgs** [comment]
@lwellerastro In regards to the searching filenames, they are separated. So you can search for a filename on the right measure and the left measure will stay as is and vice versa. 

In regards to the alphabetical sorting, it is automatically sorting after the measures have been added to the drop down boxes. So when you do go to add a measure to a point, it will automatically sort those filenames once added. So this sounds like something you do not want. If you'd like, I can revert the alphabetical sorting and just have the searching capabilities added for this issue. 

These changes have already been pushed to the Github dev, so they can be pulled from there for testing before the release.

**Comment by lwellerastro** [comment]
Hi @amystamile-usgs - thanks for the clarification - sounds perfect! I think we the auto-alphabetizing might need to be reverted.  Too hard to make it an option?  I can definitely see the usefulness of having that, but not when new measures are added, especially if there are already many measures.  Maybe adding an option to alphabetize needs to be a new post.

I don't "pull" anything from git to get my work done.  I just hop on our astrovm machines and activate a version of isis. Since I understand better how the search works, I think I can wait until this shows up in an RC to check it out.  Thanks again!

**Comment by amystamile-usgs** [comment]
It may be a good idea to have a new post for the alphabetizing because I do not know of a good solution right off hand to make it an option rather than auto alphabetizing. So for this ticket, I will go ahead and just revert those changes for the upcoming RC.

**Comment by lwellerastro** [comment]
I am trying to use the new functionality that is available via isis7.0.0-RC1, but I'm not seeing how to do so.

Additionally, when I have tried to search for a filename on the right measure by typing where the current loaded filename is, the program seg faults.

Possibly related to https://github.com/USGS-Astrogeology/ISIS3/issues/4818 and https://github.com/USGS-Astrogeology/ISIS3/issues/4819

**Comment by jessemapel** [comment]
I poked at this a bit this morning. Unfortunately, it's still present after #4869 

I think the issue is that we didn't disable inserts into the measure selection combo box. We need to use [QComboBoxx::InsertPolicy](https://doc.qt.io/qt-5/qcombobox.html#insertPolicy-prop) to set NoInsert. This should prevent adding a new object to the combo box.

To get the auto-complete/filter feature we can try adding a [QCompleter](https://doc.qt.io/qt-5/qcompleter.html#details) to the combo boxes via [QComboBox::setCOmpleter](https://doc.qt.io/qt-5/qcombobox.html#setCompleter)
