### ISSUE TITLE
Data missing from S-band lunar radar images after changing projection using map2map

### ISSUE THREAD

**Issue by ashkathaker** [DOI-USGS/ISIS3#4585]
**Description**  
I have a set of S-band (12.6 cm) earth-based radar images of the Tycho crater of the Moon.  I need them to be in a simple cylindrical projection and so I tried to change their projection using the map2map command. Although it's not showing an error when I run the command, when I try to import the images in ArcMap, all the data is missing. Before running the command, I was able to import the .cub images to ArcMap but they were slightly shifted to the right.

![Screenshot 2021-08-09 100457](https://user-images.githubusercontent.com/88555132/128719701-c90bd375-7201-4277-8b2b-82e206ba3eba.jpg)
![Screenshot 2021-08-09 101328](https://user-images.githubusercontent.com/88555132/128720917-b900da9f-5d89-49f2-a29b-d93ffb8f3afb.jpg)

The first image is how it looked before I ran the command. The second image is what happened to the image (or lack thereof) after running the command. Also, see how wonky the high and low values look.

**How to reproduce**
All files can be downloaded from https://pds-geosciences.wustl.edu/lunar/arcb_nrao-l-rtls_gbt-5-12.6cm-v1/slrm_90xx/data/
The images I'm using are: 
1) sband_39s342_cpr.img
2) sband_45s355_cpr.img
3) sband_50s348_cpr.img

**Possible solution**

**Comment by jessemapel** [comment]
Can you provide the command line you used to process the images and the map files you used. You can get the command lines from the `cathist` command.

**Comment by ashkathaker** [comment]
> Can you provide the command line you used to process the images and the map files you used. You can get the command lines from the `cathist` command.

This is the **command line** I used:  _map2map from=sband_50s348_cpr.cub map=test.map to=sband_50s348_cpr_new.cub_

These are the details of the **map file**: 
Group = Mapping
  ProjectionName     = SimpleCylindrical
  CenterLongitude    = 0.0
  TargetName         = Moon
  EquatorialRadius   = 1737400.0 <meters>
  PolarRadius        = 1737400.0 <meters>
  LatitudeType       = Planetocentric
  LongitudeDirection = PositiveEast
  LongitudeDomain    = 360
End_Group
End

Below is the result from 'cathist' command.

Object = pds2isis
  IsisVersion       = "3.5.2.0 stable | 2018-04-06"
  ProgramVersion    = 2017-06-27
  ProgramPath       = /home/cneish/Documents/isis3/isis/bin
  ExecutionDateTime = 2021-08-05T19:06:57
  HostName          = Unknown
  UserName          = cneish
  Description       = "Import PDS or ISIS2 image into ISIS3 cube format"

  Group = UserParameters
    FROM         = sband_50s348_cpr.lbl
    IMAGE        = sband_50s348_cpr.img
    TO           = sband_50s348_cpr.cub
    SETNULLRANGE = NO
    SETHRSRANGE  = NO
    SETHISRANGE  = NO
    SETLRSRANGE  = NO
    SETLISRANGE  = NO
  End_Group
End_Object

Object = map2map
  IsisVersion       = "3.5.2.0 stable | 2018-04-06"
  ProgramVersion    = 2015-08-10
  ProgramPath       = /home/cneish/Documents/isis3/isis/bin
  ExecutionDateTime = 2021-08-06T12:50:10
  HostName          = Unknown
  UserName          = cneish
  Description       = "Modify a cube's map projection"

  Group = UserParameters
    FROM         = sband_50s348_cpr.cub
    MAP          = test.map
    TO           = sband_50s348_cpr_new.cub
    MATCHMAP     = FALSE
    PIXRES       = FROM
    DEFAULTRANGE = FROM
    TRIM         = FALSE
    INTERP       = CUBICCONVOLUTION
  End_Group
End_Object
End

**Comment by AustinSanders** [comment]
I was able to reproduce this on both Mac and Ubuntu, but I'm struggling to find the cause of this error.  Some notes:

Longitude values are significantly different between the original and the map projected cub -- somewhere around 20 degrees offset.  I suspect that the nulls are due to the projection, not the actual DNs, i.e. if we are able to adjust the projection such that the lat/lons are nearer to the original image, then we'll get "real" data in the resulting image.

Upper left x pixel is "flipped" such that the original image is negative, and the map2map output is positive (with a ~200 pixel offset).  I'm on a different workstation, so I can't access the data, but it was something like original upper left X = -149000 and map2map upper left x is 149250.

**Comment by cgallinger** [comment]
I have also run into this same issue, and noticed a difference between the output of `catlab` and `gdalinfo` on the same file (sband_50s348_cpr.cub) after running `pds2isis` but without running `map2map`:

'catlab':
```
Object = IsisCube
  Object = Core
    StartByte   = 65537
    Format      = Tile
    TileSamples = 128
    TileLines   = 128

    Group = Dimensions
      Samples = 8458
      Lines   = 7356
      Bands   = 1
    End_Group

    Group = Pixels
      Type       = Real
      ByteOrder  = Lsb
      Base       = 0.0
      Multiplier = 1.0
    End_Group
  End_Object

  Group = Archive
    DataSetId               = ARCB/NRAO-L-RTLS/GBT-5-12.6CM-V1.0
    ProducerInstitutionName = "SMITHSONIAN INSTITUTION"
    ProducerFullName        = "BRUCE CAMPBELL"
    ProductId               = SBAND_50S348_CPR
    InstrumentHostName      = ("ARECIBO OBSERVATORY",
                               "NATIONAL RADIO ASTRONOMY OBSERVATORY")
    InstrumentName          = ("RADIO TELESCOPE",
                               "ROBERT C. BYRD GREEN BANK TELESCOPE")
    TargetName              = MOON
  End_Group

  Group = Mapping
    ProjectionName     = SimpleCylindrical
    CenterLongitude    = 0.0
    TargetName         = Moon
    EquatorialRadius   = 1738000.0 <meters>
    PolarRadius        = 1738000.0 <meters>
    LatitudeType       = Planetocentric
    LongitudeDirection = PositiveEast
    LongitudeDomain    = 180
    MinimumLatitude    = -59.9757
    MaximumLatitude    = -40.5755
    MinimumLongitude   = -24.6261
    MaximumLongitude   = -2.31968
    UpperLeftCornerX   = 746964.1772 <meters>
    UpperLeftCornerY   = -1230770.7248 <meters>
    PixelResolution    = 80.0 <meters/pixel>
    Scale              = 379.173 <pixels/degree>
  End_Group
End_Object

Object = Label
  Bytes = 65536
End_Object

Object = History
  Name      = IsisCube
  StartByte = 254738433
  Bytes     = 587
End_Object

Object = OriginalLabel
  Name      = IsisCube
  StartByte = 254739020
  Bytes     = 2717
End_Object
End
```

'gdalinfo':
```
  Driver: ISIS3/USGS Astrogeology ISIS cube (Version 3)
  Files: sband_50s348_cpr.cub
  Size is 8458, 7356
  Coordinate System is:
  PROJCS["SimpleCylindrical Moon",
      GEOGCS["GCS_Moon",
          DATUM["D_Moon",
              SPHEROID["Moon",1738000,0]],
          PRIMEM["Reference_Meridian",0],
          UNIT["degree",0.0174532925199433]],
      PROJECTION["Equirectangular"],
      PARAMETER["latitude_of_origin",0],
      PARAMETER["central_meridian",0],
      PARAMETER["standard_parallel_1",0],
      PARAMETER["false_easting",0],
      PARAMETER["false_northing",0]]
  Origin = (746964.177200000034645,-1230770.724799999967217)
  Pixel Size = (80.000000000000000,-80.000000000000000)
  Corner Coordinates:
  Upper Left  (  746964.177,-1230770.725) ( 24d37'29.26"E, 40d34'27.14"S)
  Lower Left  (  746964.177,-1819250.725) ( 24d37'29.26"E, 59d58'27.59"S)
  Upper Right ( 1423604.177,-1230770.725) ( 46d55'52.50"E, 40d34'27.14"S)
  Lower Right ( 1423604.177,-1819250.725) ( 46d55'52.50"E, 59d58'27.59"S)
  Center      ( 1085284.177,-1525010.725) ( 35d46'40.88"E, 50d16'27.37"S)
  Band 1 Block=128x128 Type=Float32, ColorInterp=Undefined
    NoData Value=-3.40282265508890445e+38
    Mask Flags: 

```
Additional info: macOS 10.13.6, isis version 5.0.0, GDAL version  2.3.2.

It seems like the "flipped" orientation exists in the original file, where the westernmost longitude is treated as positive instead of negative in GDAL, but then the longitude domain extends the correct amount in the positive-east direction from there. (Annoying that GDAL specifies the lat-lon coordinates in arcminutes and arcseconds, but when converted to decimal degrees the two almost match: -24.6261 vs. 24.6248. EDIT: or in meters, 746964.1772 vs 746964.177 - so looks like it's just a rounding error)

I've manually fixed this for now by running `gdal_translate` and updating with the flipped version of the upper left x-coordinate, and manually adding the image width in meters to get the position of the lower right coordinate. There's still some offset after this, but it's sufficient to bring it into a GIS environment and georeference it from there.
