### ISSUE TITLE
Administrative Code Review

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ISIS3#4592]
In order to release the ISIS software via the USGS software release process, we need to do an administrative review. The review needs to check the software for the following:

- Personally identifiable information (PII)
- Absolute file system paths
- Internal server host names or IP Addresses
- Username/Passwords

Is it possible for devs / contributors on this repository to provide an affirmative (with associated independent review or expert knowledge of the codebase) that the repository does not contain any of these prohibited items.

**Comment by jlaura** [comment]
Running a grep over the code base looking for ip addresses that can then be identified as internal or external, I am not seeing any results. 
`grep -r "'\b((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.|$)){4}\b'" .`

**Comment by AustinSanders** [comment]
I searched for file paths within ISIS, but I had to manually determine which were absolute and which were relative.  There was roughly 6000 strings that matched the regex, so I may have missed some.

There are some full paths specified in files like docker/ubuntu.dockerfile, but they don’t seem concerning because they are common paths like /opt/conda/etc/profile.d

There are quite a few templates in isis/appdata/templates/photometry/* that point to /usgs/isisd/data

The following list includes the locations of absolute paths as well as the paths themselves: 

-----

**isis/appdata/templates/photometry/mars_mdim2.blu_hapken_albat_h2.pvl:**
     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/home/tbecker/moc/photom.mars_blue.sav

**isis/tests/HistoryTests.cpp:**
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FROM    = /Users/acpaquette/Desktop/J03_045994_1986_XN_18N282W_isis.cub
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TO      = /Users/acpaquette/Desktop/J03_045994_1986_XN_18N282W_isis.cal.cub

**isis/notebooks/crop_[chandrayaan, crism_trdr, crism, marci, mimap].ipynb**
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crism_file = /home/arsanders/testdata/crism ….

**isis/notebooks/crop_lo.ipynb :**
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/home/arsanders … 
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/uscgs/cpkgs/isis2…. 
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/farm/proc1/lo/isislodata …

**isis/src/base/apps/equalizer/assets/firstRunStats.pvl**
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/usgs/cpkgs/isis3/isis_testData …

**isis/src/base/apps/errors/assets/run.log**
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/usgs/cpkgs/isis3/data/mro …

**isis/src/base/apps/isisminer/isisminer.xml**
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/scratch/kbecker/MESSENGER …

**isis/src/base/apps/spechighpass/spechighpass.xml**
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/work1/salley/CM ….

**isis/src/base/apps/speclowpass/speclopass.xml**
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/work1/mboyd/CM …

**isis/src/base/apps/stats/assets/peaks[0,1,2]_stats.log**
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/work/users/jcrough/peaks.cub

**/isis/src/base/objs/FileName/FileName.h**
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/usgs/pkgs/isis3/isis/tmp/Peaks.cub

**/isis/src/base/objs/Gruen/Gruen.cpp**
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/work1/kbecker/subchip …

**isis/src/cassini/apps/cisscal/assets/dataFiles/idlcisscalStatsEx[1,2].pvl**
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/work1/jwalldren/cisscal …

**isis/src/base/objs/Kernels/Kernels.cpp**
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/usgs/cpkgs/isis3/data/base/kernels/lsk/naif0009.tls

**isis/src/base/objs/ProcessImportPds/unitTest.cpp**
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/usgs/cpkgs/clementine1 …

**isis/src/base/objs/PvlKeyword/unitTest.cpp**
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/archive/projects/cassini/…

**isis/src/cassini/objs/VimsCamera/unitTest.cpp**
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/usgs/cpkgs/isis3/data/cassini/testData/C…

**isis/src/controlnet/unittest.cpp**
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/work1/tsucharski/protobuf/isis/nets/*

**isis/tests/FileListTests.cpp**
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/usgs/pkgs/isis3/isis/src/base/objs/FileList/*
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/Users/acpaquette/…

**isis/src/docsys/documents/CommandLine/CommandLine.xml**
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/work2/eribelin/viking/f3*

**isis/tests/data/threeImageNetwork/cube[1,3]map.pvl**
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/usgs/cpkgs/isis3/data/mgs/calibration/ …

**isis/tests/data/threeImageNetwork/cube[1,2].pvl**
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/usgs/cpkgs/isis3/data/mgs/calibration/ …

**Comment by jlaura** [comment]
@AustinSanders :+1: Looks good. Question for the rest of the dev team - why are these paths in here and do they need to be maintained for any reason?

**Comment by AustinSanders** [comment]
I looked for instances of "password" "passwd" "pwd" "pswd" and "pswrd."  The only things that I found were instances of a password set to "public," which doesn't appear to be an actual password.  I also looked through all the "likely" spots that I could think of (things like config files) and wasn't able to find any references to passwords.

**Comment by AustinSanders** [comment]
Regarding PII, the low hanging fruit is the zenodo.json file, which lists personal information.  https://www.dol.gov/general/ppii provides a list of items that qualify as PII, and a lot of the things in zenodo.json are technically PII.  It makes sense to have a list of developers along with their email addresses and orcids, so I'm not sure how important this is.

**Comment by rbeyer** [comment]
The contents of the `zenodo.json` file are no different than the information available via an author list for papers or abstracts.  I do not think that authorship information constitutes PII that needs to be protected under your organization's rules.  Otherwise your organization would be regularly violating it every time that someone attended a conference or submitted a paper.

**Comment by AustinSanders** [comment]
I'll do my best to classify each of the file paths as "trivially removable," "replaceable," "significant," or "documentation."

Trivially Removable  indicates that the filepath can be removed without replacement, and may be due to its existence solely in commented out code.  Other instances exist in the cropping notebooks in which full paths to data were specified to test the notebook, but the path no longer points to real data.

Replaceable indicates that the path is used in live code, but it can be prefixed with a relative path e.g. $ISISROOT

Significant indicates that the full path provides meaningful context that may not be carried over if the path is changed.  These may be resolvable by moving them to a common location and referencing them with a prefix.

Documentation indicates that the path points to real data, but it is not in an executable state, and trimming it is a viable option, e.g. /full/path/to/real.data could be changed to /.../real.data 

-------
# Trivially Removable
isis/notebooks/crop_[chandrayaan, crism_trdr, crism, marci, mimap].ipynb
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crism_file = /home/arsanders/testdata/crism ….

/isis/src/base/objs/Gruen/Gruen.cpp
     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; /work1/kbecker/subchip …

(Many of these are trivially removable, with the exception of a single instance of a basemap.cub file in the user's personal directory.  This basemap appears to be used in live tests and should be moved / replaced with data in a shared directory)
isis/src/controlnet/unittest.cpp
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  /work1/tsucharski/protobuf/isis/nets/*


# Replaceable

isis/tests/HistoryTests.cpp:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FROM = /Users/acpaquette/Desktop/J03_045994_1986_XN_18N282W_isis.cub
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/Users/acpaquette/Desktop/J03_045994_1986_XN_18N282W_isis.cal.cub

isis/src/cassini/objs/VimsCamera/unitTest.cpp
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/usgs/cpkgs/isis3/data/cassini/testData/C…

isis/src/base/apps/equalizer/assets/firstRunStats.pvl
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/usgs/cpkgs/isis3/isis_testData …

isis/src/base/apps/errors/assets/run.log
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/usgs/cpkgs/isis3/data/mro …

isis/src/base/objs/Kernels/Kernels.cpp
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/usgs/cpkgs/isis3/data/base/kernels/lsk/naif0009.tls

isis/tests/FileListTests.cpp
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/usgs/pkgs/isis3/isis/src/base/objs/FileList/*
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/Users/acpaquette/…

isis/tests/data/threeImageNetwork/cube[1,3]map.pvl
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  /usgs/cpkgs/isis3/data/mgs/calibration/ …

isis/tests/data/threeImageNetwork/cube[1,2].pvl
     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; /usgs/cpkgs/isis3/data/mgs/calibration/ …

# Significant
isis/appdata/templates/photometry/mars_mdim2.blu_hapken_albat_h2.pvl:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/home/tbecker/moc/photom.mars_blue.sav

isis/src/base/apps/stats/assets/peaks[0,1,2]_stats.log
     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; /work/users/jcrough/peaks.cub

isis/src/cassini/apps/cisscal/assets/dataFiles/idlcisscalStatsEx[1,2].pvl
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   /work1/jwalldren/cisscal …

isis/src/base/objs/ProcessImportPds/unitTest.cpp
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  /usgs/cpkgs/clementine1 …

isis/src/base/objs/PvlKeyword/unitTest.cpp
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  /archive/projects/cassini/…

# Documentation

isis/src/base/apps/spechighpass/spechighpass.xml
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/work1/salley/CM ….

isis/src/base/apps/speclowpass/speclopass.xml
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/work1/mboyd/CM …

isis/src/docsys/documents/CommandLine/CommandLine.xml
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  /work2/eribelin/viking/f3*

isis/src/base/apps/isisminer/isisminer.xml
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/scratch/kbecker/MESSENGER …

/isis/src/base/objs/FileName/FileName.h
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  /usgs/pkgs/isis3/isis/tmp/Peaks.cub

**Comment by jessemapel** [comment]
> # Significant
> 
> isis/appdata/templates/photometry/mars_mdim2.blu_hapken_albat_h2.pvl:
>       /home/tbecker/moc/photom.mars_blue.sav
> 
> isis/src/base/apps/stats/assets/peaks[0,1,2]_stats.log
>        /work/users/jcrough/peaks.cub
> 
> isis/src/cassini/apps/cisscal/assets/dataFiles/idlcisscalStatsEx[1,2].pvl
>        /work1/jwalldren/cisscal …
> 
> isis/src/base/objs/ProcessImportPds/unitTest.cpp
>        /usgs/cpkgs/clementine1 …
> 
> isis/src/base/objs/PvlKeyword/unitTest.cpp
>        /archive/projects/cassini/…

The files that point into old ASC employee home and work directories are likely defunct. There's a good chance that the files that use them don't even work right now.

The ProcessImportPds unit test is in a history comment. We can just change the history comment to just say that the files were move and scrub the paths.

The PvlKeyword unit test just uses a dummy file path. As far as I can tell, it doesn't actually need to be real and can be swapped for some dummy path.
