### ISSUE TITLE
MARCI UV Pointing Bands are Misaligned

### ISSUE THREAD

**Issue by astrostu** [DOI-USGS/ISIS3#4621]
**ISIS version(s) affected**: 4.x+

**Description**  
After map-projecting MARCI UV bands 1 and 2, and clipping to a specific latitude/longitude range, there are offsets between the images in latitude.

**How to reproduce**  
On a UV MARCI image where you can actually see a feature, run MARCI2ISIS, SPICEINIT, MARCICAL, CAM2MAP and make sure you set a cropped/trimmed range for CAM2MAP.  Then, look at them and you will see a several-pixel offset.

**Possible Solution**  
I have no idea ...

**Additional context**  
I thought initially that there might be an issue a few months ago when things weren't overlaying correctly, but the very low-S/N of the data just prevented any real comparison.  In the last few weeks, I've greatly improved my MARCI processing skills and I've been making mosaics (though there are still some artifacts).  The UV in particular is extremely hard to see features because of numerous issues that result in a noisy image.

The VIS bands align with each other very well, but UV not.  Attached is an average mosaic of the two UV bands for a large area of Tharsis, and if you overlay them, you will see they are shifted in latitude relative to each other.  When I overlay them on a VIS mosaic, it's the second band (UV-long) that is shifted up relative to the others.  It looks like it's about 7 pixels, and these are at 12ppd, so that's 7/12° of latitude.  And before you ask, no, this isn't due to how I process the data because I process VIS exactly the same way and all the bands align to within a pixel, except at large emission angles.

![band0002_weightedaverage](https://user-images.githubusercontent.com/50773625/132132224-941cb6ce-2d5b-482a-88e0-4ca53fe86674.jpg)
![band0001_weightedaverage](https://user-images.githubusercontent.com/50773625/132132226-ae859d1e-ffb2-4c7e-b3c0-94b3c773cdc5.jpg)

**Comment by AsterAphelion** [comment]
I suspect the issue here is SPICE kernel accuracy. In the visible bands, the slight offset you see at high emission angles is created by small inaccuracies in the MRO pointing information contained within the SPICE kernel. This inaccuracy causes the difference between the predicted and actual pixel map coordinates to vary in a systematic way across the filter set. 

To relate this to your issue and why you're seeing a much larger offset in UV bands and visible bands, have a look at [the MARCI instrument description](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2008JE003315). The areas of the CCD chip filtered for visible light images are small and close together. This means the systematic difference in angle between predicted and actual pointing will be relatively small. However, the areas of the chip filtered for UV light are much larger because they need to be binned down for S/N purposes, so the systematic offset is larger.

The solution to the offset problem would be a method to detect the angle of the pointing inaccuracy from the image and update the SPICE kernel to correct it. Although this might be a nice-to-have feature, it is assuredly outside the scope of an ISIS bugfix.

**Comment by astrostu** [comment]
Are you sure that's SPICE?  Or would that be the camera model?  Or is that one and the same thing?
