### ISSUE TITLE
Spiceinit history entry missing custom SPICE file parameters

### ISSUE THREAD

**Issue by rvwagner** [DOI-USGS/ISIS3#4647]
**ISIS version(s) affected**: 5.0.2

**Description**  
`spiceinit` does not save all input parameters in cube history.  It is missing the paths to manually-defined SPICE files (CK=, SPK=, IAK=, EXTRA=, etc.).  This makes it impossible to determine from the cube history whether a file was processed using non-standard SPICE information, e.g. post-jigsaw CKs.

**Comment by lwellerastro** [comment]
I can't quite reproduce this problem, but I do not have a scenario to test some of the parameters mentioned above.

Under isis5.0.2 I ran the following:
`spiceinit from=s0484889825.lev0.cub attach=true ck=/archive/projects/europa/Kernels/Galileo/galssi_eur_usgs2020.bc pck=/archive/projects/europa/Kernels/Galileo/pck00010_msgr_v23_europa2020.tpc`

I confirmed the full paths are contained in the image label by using more/less on the image (getkey would work as well):
```
  Group = Kernels
    NaifFrameCode             = -77001
    LeapSecond                = $base/kernels/lsk/naif0012.tls
    TargetAttitudeShape       = /archive/projects/europa/Kernels/Galileo/pck0-
                                0010_msgr_v23_europa2020.tpc
    TargetPosition            = (Table, $base/kernels/spk/de430.bsp,
                                 $base/kernels/spk/jup310.bsp)
    InstrumentPointing        = (Table,
                                 /archive/projects/europa/Kernels/Galileo/gals-
                                 si_eur_usgs2020.bc)
    Instrument                = Null
    SpacecraftClock           = $galileo/kernels/sclk/mk00062b.tsc
    InstrumentPosition        = (Table, $galileo/kernels/spk/s990114a.bsp,
                                 $galileo/kernels/spk/jup310.bsp)
    InstrumentAddendum        = $galileo/kernels/iak/ssiAddendum004.ti
    ShapeModel                = Null
    InstrumentPositionQuality = Reconstructed
    InstrumentPointingQuality = Unknown
    CameraVersion             = 1
    Source                    = isis
  End_Group
```
And also confirmed by running cathist with mode=full:
```
Object = spiceinit
  IsisVersion       = "5.0.2  | 2021-07-31"
  ProgramVersion    = 2020-12-22
  ProgramPath       = /usgs/cpkgs/anaconda3_linux/envs/isis5.0.2/bin
  ExecutionDateTime = 2021-10-01T10:10:45
  HostName          = igswzawgvsiplw
  UserName          = lweller
  Description       = "Update SPICE data (kernels, pointing, and position) for
                       a camera cube"

  Group = UserParameters
    FROM         = s0484889825.lev0.cub
    WEB          = false
    ATTACH       = true
    CKSMITHED    = FALSE
    CKRECON      = TRUE
    CKPREDICTED  = FALSE
    CKNADIR      = FALSE
    SPKSMITHED   = FALSE
    SPKRECON     = TRUE
    SPKPREDICTED = FALSE
    PCK          = /archive/projects/europa/Kernels/Galileo/pck00010_msgr_v23-
                   _europa2020.tpc
    CK           = /archive/projects/europa/Kernels/Galileo/galssi_eur_usgs20-
                   20.bc
    SHAPE        = SYSTEM
    STARTPAD     = 0.0
    ENDPAD       = 0.0
    URL          = https://services.isis.astrogeology.usgs.gov/cgi-bin/spicei-
                   nit.cgi
    PORT         = 443
  End_Group
End_Object
End
```
Since I did not use the IAK or EXTRA parameters they are not present in the history (which I agree is odd considering other parameters that defaulted are there), but they are available in the labels.

Maybe you can share some output for your case so we can better understand the problem you are seeing.

**Comment by rvwagner** [comment]
Huh.  I retract my bug report.  I just tested it again, and I am getting an IAK history entry on my standard LROC processing that uses an IAK file- I must have overlooked it, since it's a short path, and I was expecting there to be additional empty lines for CK, etc.

Sorry about the false alarm.
