### ISSUE TITLE
Error using spiceinit with Dawn mission images

### ISSUE THREAD

**Issue by jlrizos** [DOI-USGS/ISIS3#4684]
ISIS VERSION
6.0.0 # Public version number
2021-08-31 # Release date
stable # Release stage (alpha, beta, stable)

**Description**  

I have downloaded the latest ISIS version from this repository. Then, I downloaded Dawn mission kernels. Finally, I am trying to spiceinit one random image from Dawn mission running the following commands:

dawnfc2isis from=FC21B0036778_15125195001F1F.IMG to=FC21B0036778_15125195001F1F.cub
spiceinit from=FC21B0036778_15125195001F1F.cub

But I got an error:

Group = Kernels
  NaifFrameCode             = -203121
  LeapSecond                = $base/kernels/lsk/naif0012.tls
  TargetAttitudeShape       = $base/kernels/pck/pck00009.tpc
  TargetPosition            = $dawn/kernels/tspk/de421.bsp
  InstrumentPointing        = ($dawn/kernels/ck/dawn_sc_150504_150510.bc,
                               $dawn/kernels/fk/dawn_v15.tf,
                               $dawn/kernels/fk/dawn_fc_v3.bc)
  Instrument                = $dawn/kernels/ik/dawn_fc_v10.ti
  SpacecraftClock           = $dawn/kernels/sclk/DAWN_203_SCLKSCET.00091.tsc
  InstrumentPosition        = $dawn/kernels/spk/dawn_rec_141230-150509_150603-
                              _v1.bsp
  InstrumentAddendum        = $dawn/kernels/iak/dawnfcAddendum002.ti
  ShapeModel                = Null
  InstrumentPositionQuality = Reconstructed
  InstrumentPointingQuality = Reconstructed
  CameraVersion             = 2
  Error                     = "No pointing available at requested time
                               [484127469.19564] for frame code [10101]"
End_Group

I have tried in Ubuntu 18.04 and Ubuntu 20.04. I checked my kernels: they are the same we can find in the repository. No missing kernel.

**Comment by AustinSanders** [comment]
Hi @jlrizos , this appears to be the same issue described in #4638. We have an open PR that will address this issue.

I'm closing this as a duplicate issue, but if you have reason to believe that this is not the same error, feel free to reopen with additional context.

**Comment by AustinSanders** [comment]
Reopening as per [user feedback](https://github.com/USGS-Astrogeology/ISIS3/issues/4638#issuecomment-972286334). I still suspect that this is similar to #4638, and we may just need to edit another translation file to get ensure that we're picking up the right kernels.

**Comment by acpaquette** [comment]
@jlrizos This has been fixed as of #4670 but an ISIS release with the fix has yet to be released. The fix was introduced in our 6.2.0 sprint but a release wasn't made with the fix. We are working on getting a 7.0.0 release candidate out at the end of our current sprint (this Friday) so that release candidate should contain the fix. 

There is a work around for versions of ISIS < 7.0.0, mainly specifying a target for dawnfc2isis. So it should look something like this:
`dawnfc2isis from=/Path/to/dawnfc/image.img to=/Path/to/dawnfc/cube.cub target=VESTA`

This should get the appropriate target for the image mentioned above, and thus spiceinit should not fail
