### ISSUE TITLE
ISIS application GUIs will not display after build on MacOSX 10.15 Catalina 

### ISSUE THREAD

**Issue by KrisBecker** [DOI-USGS/ISIS3#4773]
**ISIS version(s) affected**: Unknown

**Description**  

After building ISIS on a MacOSX 10.15 Catalina system, none of the ISIS application GUIs would display anything. Every ISIS application ran would show the `exec` window in the dock but nothing would display. Meanwhile, the app would run at 100% and start consuming memory. Had to abort them after running for several minutes as this usage of CPU and memory would continue.

After some searching, I found a solution that worked for the me. It appears to be a [bug](https://bugreports.qt.io/browse/QTBUG-87014) in Qt, specifically [5.12.9,](https://forum.qt.io/topic/119316/mac-application-built-with-5-12-9-lts-hangs-on-launch-under-big-sur) but seems to only affect Big Sur. I think this shows that it also affects Catalina under certain conditions.

Running `conda list` shows the following version of Qt installed on my system in the environment that was used to build ISIS:
```
qt                        5.12.9               h2a607e2_5    conda-forge
```
The fix is to add `export  QT_MAC_WANTS_LAYER=1` to your shell environment prior to running ISIS applications. Doing that appears to have solved my problem. 

Note that ISIS applications appear to run fine in batch mode and are apparently unaffected by this problem.

It looks like the problem has been fixed in version Qt 5.12.11 according to the Qt bug linked above. So I would suggest upgrading to a newer version of Qt.

**How to reproduce**  

Build ISIS on MacOSX 10.15 and run any program in GUI mode. 

Not sure if this can be consistently reproduced.

**Possible Solution**  

Upgrade to `qt>=5.12.11`.

**Additional context**

**Comment by acpaquette** [comment]
@KrisBecker Thank you for mentioning this. Some of the devs have known about this for a little while and it has been on our radar since updating to Big Sur. We were waiting for an updated version of qt to be pushed to conda-forge and it looks like 5.15 was pushed about two months ago:

https://anaconda.org/conda-forge/qt-main

You are correct that this is also an issue on Big Sur being a little more pronounced, resulting in Illegal Instruction errors when running apps like qview. This is something I have fought with for a while now, so thank you for bring it back to our attention!

**Comment by afrigeri** [comment]
Same behavior when building  `IsisVersion       = "7.2.0  | 2023-07-03"` on:

```
ProductName:		macOS
ProductVersion:		13.4.1
BuildVersion:		22F82
```

confirm `export  QT_MAC_WANTS_LAYER=1` fixes it
