### ISSUE TITLE
Python requires openssl package that I already have installed. 

### ISSUE THREAD

**Issue by SRL-UGA** [DOI-USGS/ISIS3#4778]
Hello! I have been at this for hours and am wondering if anyone can help me resolve the issue. 

I am trying to install isis on my mac, but I am running into the following error: 
Command line: 
$ mamba install -c usgs-astrogeology isis

Output: 
Looking for: ['isis']

Encountered problems while solving.
Problem: package python-3.6.13-h88f2d9e_0 requires openssl >=1.1.1j,<1.1.2a, but none of the providers can be installed

I have checked my current openssl version and it is 1.1.1m, so clearly something else is wrong. Has anyone else run into this issue, and if so what have you done to resolve it? Any help would be greatly appreciated!

**Comment by acpaquette** [comment]
Hello! This has been an issue with the ISIS installation process for a variety of ISIS versions going back. It has to do with the ISIS dependencies not being pinned quite right so dependency resolution can be an issue. 

My two immediate recommendations with your install command are to specify the version of ISIS that you want to install like so:
`mamba install -c usgs-astrogeology isis=X.Y.Z`

Than I would also add the conda-forge channel to your install command. Order matters in the channel specification since the usgs-astro channel holds some old dependencies of ISIS that should likely be removed. 

So the full mamba install command will look like:
`mamba install -c conda-forge -c usgs-astrogeology isis=X.Y.Z`

Where X.Y.Z is the version of ISIS you are looking to install. Hopefully this helps some and keep us updated on your installation troubles!

**Comment by SRL-UGA** [comment]
Thank you for the help. I actually installed it using conda instead of mamba, and the installation process went by pretty quickly, and everything seems to work so far!

**Comment by jlaura** [comment]
@SRL-UGA Terrific to hear. Please reopen if you have any issues with installation or open a new issue if something else crops up!
