### ISSUE TITLE
Create Lunar Reconnaissance Orbiter Overview Page

### ISSUE THREAD

**Issue by ladoramkershner** [DOI-USGS/ISIS3#4855]
**Description**

We have great overview documentation for the [Mars Recon Orbiter](https://github.com/USGS-Astrogeology/ISIS3/wiki/Working_with_Mars_Reconnaissance_Orbiter_(MRO)_Data), [Mars Global Surveyor](https://github.com/USGS-Astrogeology/ISIS3/wiki/Mars_Global_Surveyor_Mission), [Mars Viking Orbiter](https://github.com/USGS-Astrogeology/ISIS3/wiki/Viking_Orbiter_Mission), and the [Cassini-Huygens](https://github.com/USGS-Astrogeology/ISIS3/wiki/CSS) missions, but nothing for LRO. LRO is a really popular dataset and an overview of the mission would complete the set.

Thanks!

**Comment by oleg-alexandrov** [comment]
In particular, documentation for how to process LRO WAC is needed, stating with where to get the data, and all the other steps. What we have so far is the list of tools here: https://isis.astrogeology.usgs.gov/Application/index.html

There is also a writeup here: https://www.lpi.usra.edu/lunar/tools/dems/Ohman_mono-WAC_ISIS_procedure_v1-1.pdf, but that one is not detailed enough.

In particular, the photometric correction does not work as explained there. And there does not seem to exist a tool which could combine the even and odd WAC cubes into a seamless cube without doing cam2map on it first. Running cam2map is fine if you want a mosaic, but some applications call for raw cub files. 

BTW, ASP has a doc for NAC data, maybe it could be of some use. It is at: https://stereopipeline.readthedocs.io/en/latest/examples.html#lunar-reconnaissance-orbiter-lro-nac

**Comment by oleg-alexandrov** [comment]
I added a doc here: https://github.com/USGS-Astrogeology/ISIS3/wiki/Working_with_Lunar_Reconnaissance_Orbiter_(LRO)_Data

There's more to write, but this already has some basic info and examples of data processing. More edits and additions from more knowledgeable folks are welcome.

**Comment by rvwagner** [comment]
There's a very complete guide to working with LROC NAC data here: http://lroc.sese.asu.edu/files/DOCS/LROC_NAC_Processing_Guide.pdf
(I can provide the Markdown source file for that if someone wants to turn that into a page on the ISIS wiki.)

I was working on a WAC version as well, but ran out of free time before finishing, and also some important steps for making mosaics were (are?) still not available in the public version of ISIS (lrowacphomap, which is our preferred photometric correction method). 

Regarding mosaicking even and odd frames without map-projecting, what process are you thinking of that requires the actual pixel data to all be in one file?  For making backplanes, etc., either the even or odd file will work fine- the SPICE data is present for all pixels, it's just that half of them are nulled out; you can process backplanes for the even frames and copy them to the odd frames' file.  If you truly need all the frames' image data in one file, handmos will work fine (likely with just the default parameters, only specifying from and mosaic), but that file will not work well for map-projection, and will very much not have a "seamless" appearance due to how the camera functions.

**Comment by jessemapel** [comment]
We're testing out some stereo work with WAC data in ASP using our USGSCSM sensor model. It requires that all of the frames be in a single file to do dense stereo matching.

Also, lrowacphomap was just added to the public version in #4961 and will go out in the next release.

**Comment by jessemapel** [comment]
I think it's sufficient for us to just link your documentation, no need to duplicate it here.
