### ISSUE TITLE
qview pointer move with keyboard

### ISSUE THREAD

**Issue by scsides** [DOI-USGS/ISIS3#4902]
**ISIS version(s) affected**: 6.0.0 and 7.0.0 RC1 and before. Not sure when it stopped working.

**Description**  

The pointer movement of 1 line by 1 sample using the numeric keypad does not work on Mac. It may not work on Linux either

**How to reproduce**  

Load an image into qview
Using the mouse put the pointer in the middle of the image where there are valid line,samp positions
Using the numeric keypad press any key 1-9. The pointer should move one pixel in the relative direction
There may be a modifier key (shift, ctrl, ...) that allows movement of 10 pixels at a time, not sure though

**Possible Solution**  

**Additional context**  

Moving the pointer one pixel at a time with the mouse is nearly impossible, this broken feature was designed to overcome that.

**Comment by lwellerastro** [comment]
I can confirm that I can still move the pointer using the numeric keypad via a linux OS.
That being said, my number pad has short cuts for arrows using the 8, 6, 2 and 4 keys which allow for the fine movement.  The other keys do nothing.  I'm not sure what to expect since I don't use this functionality, but the keys noted worked as did simply using my keyboards arrow keys.
