### ISSUE TITLE
Add application to stitch LRO WAC even and odd images together

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#4924]
**Description**  

In order to properly work with LRO WAC, and likely other push frame sensor, images in stereo matchers we need a tool that merges the even and odd framelet images back into a single image. The program will also need have the option to flip the framelets similar to how MRO MARCI images can be flipped.

In order to prevent complicating processing, the app will also need to strip the camera information off of the cube.

**Comment by astrostu** [comment]
I'm certainly not opposed to a separate program to do this "correctly," but I'll note that I've been using AUTOMOS with no problems, at least for MARCI.

**Comment by jessemapel** [comment]
We can use one of the *mos programs to stitch the images back together, but I don't think we can have them also do the flipping.

**Comment by astrostu** [comment]
I guess it hasn't been an issue for me (in the last few years) because I use marci2isis with flip=yes.  So, you might investigate whether it makes more sense to do the flipping at the odd/even reconstruction phase, or at the initial ingestion phase.  And if the former, then certainly you'd need to check if flippage has occurred since you don't want to flip it back and have it be wrong when you're trying to right it.

**Comment by jessemapel** [comment]
Marci is the only one of our push frame sensors that supports the flipping on ingestion. So, you don't need this really for MARCI, but we're currently working on LRO WAC and we do need it for stereo work.

**Comment by astrostu** [comment]
Ah! That makes sense.
