### ISSUE TITLE
Couldn't find how to start from scratch

### ISSUE THREAD

**Issue by manueltorrs** [DOI-USGS/ISIS3#4951]
**Description**
I'm new to ISIS, and I'm really struggling with how to start the program. I can see in the tutorial several screenshots showing how to use it, but I even hadn't the opportunity of run it, because I even don't know how and its not explicit that how to.

**Suggested Edit**
I would recommend add more explicit documentation where shows how to do everything from zero, for people like me.

Thanks!

**Comment by AustinSanders** [comment]
Hi @manueltorrs, the Astrogeology Science Center development team is in the process of adding and improving documentation throughout our software portfolio, so this issue is somewhat timely.

If you've already reviewed the [installation process](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/README.md#Installation), please let me know which step you're stuck on, and I'll do my best to assist and/or revamp that portion of the documentation.  Alternatively, if you've gotten ISIS installed properly, the [ISIS3 Documentation](https://isis.astrogeology.usgs.gov/Application/index.html) is a good place to start learning how to use specific programs.

Unfortunately, given the scope of ISIS and the number of programs in the ISIS suite, adding additional tutorials on how to do "everything" is not a tractable issue.  For this issue to move forward, I'll need a little more information about 1. what you want to do 2. what you've tried and 3. where in particular you're stuck.

We also maintain an active [discussion board](https://astrodiscuss.usgs.gov/) where users are welcome to submit questions regarding usage of ISIS in a less development-oriented context.  If you have specific questions regarding the usage of ISIS programs, that may be a useful resource as well.

**Comment by manueltorrs** [comment]
Hello, thanks for responding,

1. Basically, I want to open .img files and convert it to .jpg or .png images. Of course, I also would like to manipulate its layers, bands, etc.
2. I have installed it as the tutorial with anaconda says.
3. I can't open anything, I don't know how to initiate anything.

I couldn't find anything about how can launch ISIS, maybe I'm wrong, but I just found only screenshots with the program already running, but not how to start it, and that is so frustrating.

Thank you in advance.

**Comment by jessemapel** [comment]
As Austin said, ISIS is a collection of applications that you can combine together to do specific tasks. It is not like photoshop or GIMP where there is a single program with many tools.

First of all, you will need to get your images into a Cube file. You can do this with std2isis.

Then what you do next depends on how you want to manipulate the bands. ISIS does not use layers like photoshop or gimp does.

Finally to get it out to a jpg or png you can use isis2std.

**Comment by oleg-alexandrov** [comment]
The current README spends a lot of time on installation and ISIS data, and not enough on documenting the tools. 

I guess the entry point is the README section called "ISIS Tutorials". From there, if one fumbles around there some pointers to things. Particularly, there are "Mission Specific ISIS3 Processing" tutorials. There is text on "Locating and Ingesting Image Data". 

I hope you can read around and offer suggestions about how things could be further streamlined.

**Comment by manueltorrs** [comment]
Thanks for responding, you are a very kind community,

Despite of several efforts on learning how to use this program, I just simply couldn't, and I have noticed that there was an error on the installation because when I try to run anything, it shows me this message:

`qview: error while loading shared libraries: libavresample.so.3: cannot open shared object file: No such file or directory`

And the solution looks not so easy and I can't afford more time trying to fix it and then learn how to use it. I preferred to find another one easier to install and use and I already could.

However, thanks for try to help me so much, I am so thanksful with you all.

**Comment by oleg-alexandrov** [comment]
Glad you found an alternative solution. 

If all you need is to convert .img to another format then given its simple nature it appears that even Photoshop can do it (https://www.planetary.org/articles/0307-image-processing-trick-raw-photoshop). And some datasets are also available as .tif or .jp2 which don't need ISIS. 

But ISIS can manipulate images which won't fit in computer's memory and it can't be avoided if desired to do image orthorectification or work with cameras. 

Speaking about your specific problem though, I ran into this ``libavresample.so.3`` problem as well. This seems to be an issue not with ISIS itself but with some of its dependencies. This is part of the ffmpeg package, which ISIS specifies in its requirements and should have been downloaded properly but somehow it was not.

One can either reinstall it in the same conda environment you installed ISIS in, which I assume is called ``isis``, as

    conda activate isis
    conda install -c conda-forge ffmpeg --force-reinstall

Otherwise, one can just create a standalone environment having ffmpeg, then copy from it that missing library to your isis environment. This approach should not be necessary but it is a good sanity check that the offending library exists and can be fetched independently of ISIS. This can happen as follows:

    conda create -c conda-forge -n tmptestenv ffmpeg=3.4.1
