### ISSUE TITLE
Spice fail on version 4

### ISSUE THREAD

**Issue by ndhverma** [DOI-USGS/ISIS3#5005]
ISIS 4.4.0 version fail on web server for spice 

I am processing the MiniRF data set id: lsz_03737_1cd_xku_88s276_v1_cub.cub

**ERROR** The SPICE server returned incompatible SPICE data.
**ERROR** Unable to find PVL group [Plugins].

Kindly suggest how I can correct this error.

Thanks

**Comment by jessemapel** [comment]
Can you provide the command line you ran and any processing you did to the cube file before running spiceinit?

**Comment by ndhverma** [comment]
Hi,

I have first convert the Mini-RF data into cub using mr2isis command.
Then run the web spice command 
![image](https://user-images.githubusercontent.com/43364419/179565526-c2d3c09c-c82a-486e-822f-441e2ae23b9d.png)
after run the above command, following error I am getting
ERROR The SPICE server returned incompatible SPICE data.
ERROR Unable to find PVL group [Plugins].

**Comment by ndhverma** [comment]
> Can you provide the command line you ran and any processing you did to the cube file before running spiceinit?

Hi,

I have first convert the Mini-RF data into cub using mr2isis command.
Then run the web spice command
![image](https://user-images.githubusercontent.com/43364419/179933727-e0cb7abf-c145-41a1-97c4-06725bfbac29.png)

**Comment by jessemapel** [comment]
It looks like this is being caused by #4930 I was able to ingest and then successfully spiceinit the image, but then if I ran it again it would fail. Looking at your terminal output it looks like it successfully ran at least once. Can you check that there is proper camera information attached by running the campt application on the image, just specify the image as `from`?
