### ISSUE TITLE
Using StereoPair Strategy with Caminfo output

### ISSUE THREAD

**Issue by Toldbo** [DOI-USGS/ISIS3#5010]
Hi 

I have been reading the documentation on isisminer and the example provided. However, I am simply unable to progress. The examples pull resources from a database and I can see that there is an option for csv and pvl but somehow I need more guidance on this. When I run caminfo with append=true I get at csv or pvl file with all the information but not in the right format (I understand each resource has to be one row with keywords?). I can't find any documentation on how to get from caminfo's output to a valid isisminer input? I am trying to get a ranked list of optimal image pairs for stereo in a specific lat/lon region using FC2 on Dawn.

I hope you can help me. Best Christina

**Comment by lwellerastro** [comment]
Hi @Toldbo, I have some experience with isisminer, but not for producing stereo pairs, but I think getting you some information to start working will be helpful.

When I run caminfo for isisminer input I generate pvl files, one per image.  I have queried a databse in the past from within an isisminer config file, but it is not necessary and csv's are too messy particularly if you require more than the basic information (I'm also using my pvl's as input information to a database so I ask for a lot).

I think the following caminfo run will get the information you need for the stereo example in the isisminer documentation, but no promises.  I have not used the stereo config example and can't guarantee you things will work once you get caminfo output that is easier to deal with.

`caminfo from=image.cub to=image.pvl isislabel=true geometry=true polygon=true polylinc=100 polysinc=100`

I believe the isislabel will supply basics like SourceProductId (or ProductId if that is the case for your data); the geometry information will contain the information at the center of the image including illumination, resolution and other stereo keywords; and the footprint/shape/polygon information is used to determine image overlaps. 

I usually run the program footprintinit to get the polygon information written to the image label ahead of time (as part of my basic processing, along with camstats as well), and in that case I would use _uselabel=true_ and drop _polygon=true polylinc=100 polysinc=100_.  Those footprint setting might not be appropriate for your data either - you will have to experiment to see what generally works for you.  This information is the most finicky and the thing that is likely to make caminfo fail (it can't create the polygon or has other problems), which is why I try and deal with it via footprintinit ahead of time.

Try running caminfo on a couple of images and look at the output keywords and see how they relate to what is being read and used in the stereo config file.  You might need to turn on some other options to get all the relevant keywords.

This is how my isisminer config file looks like to read in a pvl file:
```
  Object = Strategy
    Name = ReadCaminfoPvlFiles
    Type = PvlReader
    Description = "Read in caminfo Pvl files as resources."

    FromList = "%1"
    FromListArgs = "CaminfoList"

    Identity = "%1"
    IdentityArgs = "SourceProductId"

    GisGeometryKey = GisFootprint
    GisType        = WKT
    # GisSimplifyTolerance = 0.0005 <degrees>
    RemoveGisKeywordAfterImport = True
    Debug=true
  EndObject
```
You may need to set RemoveGisKeywordAfterImport=False to make the stereo config work properly. Also, it looks like in the example given that there are Messenger specific keywords being read from the database (in the overlap example) and read out to the output csv file (in the last Stereo example)  that will have to be removed for your config - YearDoyA, lYearDoyB, FocalPlaneTemperatureA ,FocalPlaneTemperatureB, TempDependentFocalLengthA, TempDependentFocalLengthB.  There might be others.  You might not want all of the keywords in the example in your output stereo pairs csv file.  Only keywords that available in the input pvls or created within the config file (like StereoStrengthRank) can be written to the output file. You might not want the fooprint/polygon information written out either (GisFootprint).  I think for this example the output was input to another step that required that information.

I tend to use isisminer to determine image overlaps which is then input to the program findfeatures.  My isisminer command is less complicated than the one in the documentation which is doing a lot:
`isisminer config=find_overlaps.conf parameters=CamInfoList:${pvls}@OutputDirectory:Overlaps`

Not gonna lie, this may only get you so for and still not what you need.  My isisminer success has mostly come by way of others who have shared working config files that I have had to wrestle with to get results. I'm looking for a more concrete, simple example to share with you and if I find something I will post here, but I am out of the office for the remainder of the week and may not have time to look before I go.

**Comment by Toldbo** [comment]
Thank you so much for taking your time to answer me :) I have 15 images that I know all observe the same crater (I hand picked them) and now I ran your suggested caminfo on them `"caminfo from=image.cub to=image.pvl isislabel=true geometry=true polygon=true polylinc=100 polysinc=100"` which results in 15 .pvl files. I collect these in a list (just a .txt. - is the format important?) and then run a modified example config file on them. It correctly makes a list of files but only evaluates 1 (the first one)

This is the output:

__________________________________________________
Creating strategies...
CandidateMiner Strategy algorithms loaded: 1.
OverlapMiner Strategy algorithms loaded: 4.
Finished creating 21 strategies...

Running PvlReader::ReadCaminfoPvlFiles (TimeIn:  16:16:19.253)
Description: Read in caminfo Pvl files as resources.
  PvlReader::Resource::Pvl0::Identity = Pvl0
  PvlReader:ReadCaminfoPvlFiles has a geometry with 45 points!
1 of 0 processed in PvlReader::ReadCaminfoPvlFiles (TimeOut: 16:16:19.268)
ElapsedTime(s): 0

Running Limit::SelectRegion (TimeIn:  16:16:19.268)
Description: Find all images with center image geometry in the defined region
Limit::Resource Pvl0 result = 1
1 of 1 processed in Limit::SelectRegion (TimeOut: 16:16:19.268)
ElapsedTime(s): 0

Running RunCommand::MakeOutputDirectory (TimeIn:  16:16:19.268)
Description: Ensure output directories exists
Running Mkdir1 PRE command: mkdir -p /Users/toldbo/workArea/imgFolder/cornelia_selected_1A/Images
Running Mkdir2 PRE command: mkdir -p /Users/toldbo/workArea/imgFolder/cornelia_selected_1A/Overlaps/Equi09S016ED20
2 of 0 processed in RunCommand::MakeOutputDirectory (TimeOut: 16:16:19.287)
ElapsedTime(s): 0

Running CsvWriter::WriteRegionImages (TimeIn:  16:16:19.287)
Description: Write images that are in the defined region to a file
CsvWriter::Filename = /Users/toldbo/workArea/imgFolder/cornelia_selected_1A/Images/Equi09S016ED20_images.csv
1 of 1 processed in CsvWriter::WriteRegionImages (TimeOut: 16:16:19.288)
ElapsedTime(s): 0

Running GisOverlap::ImageOverlap (TimeIn:  16:16:19.288)
Description: Find all overlaps images in specfied region

=== Running GisOverlap with 1 total.
  Total active resources: 1
Creating RTree for 1 candidates
Total Geoms: 2
Overlap query candidate count: 1

===> Running Overlap query for Pvl0
  Query returned 1 candidates.
  Valid overlaps returned for storage: 0
0 of 1 processed in GisOverlap::ImageOverlap (TimeOut: 16:16:19.288)
ElapsedTime(s): 0

Session complete in 00:00:00.035 of elapsed time
0
__________________________________________________

If you find a simpler example it would be very appreciated, but thank you already :)

**Comment by jessemapel** [comment]
@Toldbo can you share your isiminer config?

**Comment by Toldbo** [comment]
Yes it is attached below :) 

So two of the issues was that my list of pvl files was in mac format an not unix so it only read the first line, another problem was that I had not changed SourceProductId to ProductId. 

With these out of the way, now running this config file results in 15 csv files for each ProductId but it doesn't contain more than one line (itself) and the MatchedProductId, OverlapRatioSource and OverlapRatioMatch are all NULL

[isisminer.zip](https://github.com/USGS-Astrogeology/ISIS3/files/9154470/isisminer.zip)
[Pairing.zip](https://github.com/USGS-Astrogeology/ISIS3/files/9154490/Pairing.zip)
[output_pvl.zip](https://github.com/USGS-Astrogeology/ISIS3/files/9154491/output_pvl.zip)
