### ISSUE TITLE
marci2isis documentation to explain variable exposure duration

### ISSUE THREAD

**Issue by ladoramkershner** [DOI-USGS/ISIS3#5012]
**Description**
Currently, the following warning is output if you ingest  MRO MARCI data that does not contain multiple values for the "ExposureDuration" key. 

```
Group = NoExposureTimeDataFound
  Message                  = "No variable exposure information found in the
                              varexp file. Assuming exposure time is fixed for
                              [P04_002649_1863_MU_00N233W.IMG]"
  FileNotFoundInVarexpFile = P04_002649_1863_MU_00N233W
End_Group
```

As a more casual / beginner user of MARCI data this was confusing and slightly alarming. It made me wonder if I did something wrong to generate the warning. 

I am assuming that the mission team changed the operational procedure of MARCI at some point during the mission, causing some MARCI data to have multiple exposures and some to not, and therefore prompting this check in the code. (Please let me know if this is a correct assumption). If the mission team's change in operational parameters resulted in different exposure durations on the MARCI images, I am not sure a warning is the most effective way to communicate this information.

**Suggested Edit**

Instead of erring could we update the application documentation to make note of this peculiarity, why multiple exposures would or would not occur and what it means for the data. Then either output to standard out whether it has multiple durations or not OR output nothing at all. My suggestion around outputting nothing is, if it is expected behavior, do we need to warn the user about it?

Thanks!

**Comment by astrostu** [comment]
A couple notes:

1) I haven't not encountered this warning before, but taking a look at the ISIS data (/mro/calibration/marci/varexp.tab), it looks like there are quite a lot of images where the team changed the exposure duration during the image acquisition process.  *I suggest testing one of those to make sure that this warning is NOT given in those cases.*

2) It also looks like that varexp.tab file was last updated in June 2019.  As with some other files from MARCI, I think you should be pulling the latest (via some script) from the PDS releases to serve out with the latest kernels.  To be clear, a June 2019 update means that 3 Earth years, or >1.5 Mars Years will not calibrate properly in ISIS at this point.

3) Based on my use of the previous-generation instrument (MOC-WA), the team used variable exposure times during a single image swath to prevent over-exposing poles and under-exposing not-poles.  It looks like in the varexp.tab file, Earth months ≈6–13 of a given Mars Year have variable exposures, which correspond roughly with southern spring-to-summer with bright icy frost and then an ice-covered polar cap, so it would make sense.

4) YES!  I would say that since this is expected behavior, a warning should not be given.  I would say it should still go into the print.prt output but not as a warning, as a note.  That said, see above point 2 above on the file being out of date.

**Comment by jessemapel** [comment]
My understanding of why the warning was added is that there is no way to know if an image has variable exposure or not from just the image. So, just in case the varexp.tab file is out-of-date we issue the warning.

I can confirm that it works correctly with images that have variable exposure duration.

I can also confirm that it's the most up to date. It's tricky to keep the file updated as it comes out with new PDS releases and automating against that is cumbersome. See #4969 

This feels like an appropriate warning to me. Maybe it just needs better wording and a reference to the varexp.tab. I agree that the marci2isis docs could use some improvement.

**Comment by ladoramkershner** [comment]
Okay, I agree that the warning is reasonable. I changed the name to be more focused on the documentation side of things.

We could 
1.) Update 'varexp' in the warning to a more specific 'varexp.tab in the mro data area'. 
2.) Write an explanation for the reasoning behind this variable exposure duration in the marci2isis documentation and the [wiki](https://github.com/USGS-Astrogeology/ISIS3/wiki/Working_with_Mars_Reconnaissance_Orbiter_(MRO)_Data#Mars-Color-Imager-MARCI-), since we are moving towards a single ingest application.
