### ISSUE TITLE
downloadIsisData not working on Mac

### ISSUE THREAD

**Issue by cneish** [DOI-USGS/ISIS3#5181]
**ISIS version(s) affected**: 7

**Description**  
Hi all, It's me again, trying to install ISIS on my M2 Mac Mini. My husband helped me to install the software, but we didn't attempt to download the ISIS data files. I thought they were still available on the rsync server, but I see that they are not. When I tried the download command, it was not recognized.

>(isis) dyn172-30-147-169:~ cneish$ downloadIsisData base $ISISDATA
>-bash: downloadIsisData: command not found

Any idea what's going on? I installed rclone, but it didn't make any difference.

Thanks, Catherine

**Comment by cneish** [comment]
Addendum: I was able to download the ISIS test data using rclone:

>rclone sync S3:asc-isisdata/isis_testData/ $ISISDATA

Where can I access the "regular" ISIS data?

Thanks, Catherine

**Comment by astrostu** [comment]
@cneish — The default version of ISIS installed is still 7.0.0, not 7.1.0.  You'll need to delete the conda environment, make a new one, and explicitly set ISIS to install version 7.1.0.  It was only with 7.1.0 that the download script was included.  (I know this because I was in your situation just a month ago.  It's also not a Mac thing, this was on Mac and Linux.)

Additionally, you will need to run "conda install rclone" after the ISIS 7.1.0 install because USGS forgot(?—whatever the term is?) to include that in the install for 7.1.0 but it's required for the download script to work.

**Comment by cneish** [comment]
Hi @astrostu, Installing ISIS a few weeks ago was quite a saga, which I would prefer not to replicate (see issue #5164). I have thought of two alternatives:

1. Download the script "downloadIsisData" and just copy it to my current version of ISIS.
2. Download the data manually using rclone.

If the latter, where may I find the data? You provided the link to the "isis_testData", but not the "regular" data.

I really want to avoid installing ISIS again.

Thanks, Catherine

**Comment by AustinSanders** [comment]
@cneish This issue seems to be popping up lately, and there's a (brief) discussion posted at https://github.com/DOI-USGS/ISIS3/discussions/5174.

I believe that this can be resolved by using `./downloadIsisData` rather than `downloadIsisData`.  If you (or any user) can confirm that this fixes the error, I will update the documentation with the fix.

@astrostu We have chosen not to include rclone in the conda environment because it is not a requirement to run any ISIS programs.  The scripts directory is intended to capture ancillary programs that may offer support/convenience functionality to ISIS users, but it is not intended to capture "ISIS proper," and dependencies of these scripts are not guaranteed to be included in the environment.  If the directions or requirements to use any programs, scripts, etc. are unclear, I'd encourage you to submit an issue so that the ASC development team can clarify. You might also choose to submit a PR that provides instructions that better capture the user perspective.

**Comment by KrisBecker** [comment]
@AustinSanders...

 >@astrostu We have chosen not to include rclone in the conda environment because it is not a requirement to run any ISIS programs. The scripts directory is intended to capture ancillary programs that may offer support/convenience functionality to ISIS users, but it is not intended to capture "ISIS proper," and dependencies of these scripts are not guaranteed to be included in the environment. If the directions or requirements to use any programs, scripts, etc. are unclear, I'd encourage you to submit an issue so that the ASC development team can clarify. You might also choose to submit a PR that provides instructions that better capture the user perspective.

I am confused by this response. `rclone` is explicitiy included in the conda [environment](https://github.com/DOI-USGS/ISIS3/blob/ccdfc2ce47c9a4e1c60d536a10288773268dc4b9/environment.yml#L54). And there are [explicit instructions](https://github.com/DOI-USGS/ISIS3/blob/ccdfc2ce47c9a4e1c60d536a10288773268dc4b9/isis/CMakeLists.txt#L601-L602) in CMakeLists.txt that installs `downloadIsisData` in $ISISROOT/bin from the scripts directory making it appear as a formal ISIS application (regardless of the programming language used) that has `rclone` as a dependency. Does this not make `rclone` a required dependency to run an ISIS application?

**Comment by AustinSanders** [comment]
@KrisBecker You are correct!  I'm off base here and I apologize, especially to @astrostu .  My understanding of that directory (and my response) is based on a discussion previous years, so my information is outdated.  I will own this one, and I appreciate that correction.

I'll look into why this isn't be installed into $ISISROOT/bin.  In the meantime, I'd expect `./downloadIsisData ...` to serve as a temporary fix.

**Comment by KrisBecker** [comment]
FYI, installing scripts like this in $ISISROOT/bin is apparently the procedure being [recommended](https://github.com/DOI-USGS/ISIS3/pull/5163#issuecomment-1494944687).

**Comment by AustinSanders** [comment]
> Addendum: I was able to download the ISIS test data using rclone:
> 
> > rclone sync S3:asc-isisdata/isis_testData/ $ISISDATA
> 
> Where can I access the "regular" ISIS data?
> 
> Thanks, Catherine

@cneish If your config allows you to reach the test data at S3:asc-isisdata/isis_testData/, then you should be able to download the data using `rclone sync S3:asc-isisdata/isis_data/ $ISISDATA`

It may also be worth passing rclone the --dry-run flag to ensure that the data are going to the intended location(s)

**Comment by cneish** [comment]
Great! The download is looking good so far. Thanks.

![Screenshot 2023-04-13 at 9 35 16 AM](https://user-images.githubusercontent.com/44587348/231775790-f140c3ef-4b93-4fc6-b8a9-b357acb31714.png)

**Comment by AustinSanders** [comment]
Between c14a746ba and issue #5183, this issue appears to be resolved and tested in 8.0.0RC1.
