### ISSUE TITLE
spiceinit error when processing HRSC images

### ISSUE THREAD

**Issue by hard2namegit** [DOI-USGS/ISIS3#5223]
**ISIS version(s) affected: 7.2.0

**Description**  
When I used 'spiceinit' to initialize the HRSC images, the software reported an error to me: "The Server was unable to initialize the cube.The error reported was: Unable to initialize camera model." Spice data has 'use the isis spice web service' checked. CK has 'reconstructed pointing kernels' and 'predicted point kernels' checked. Strangely enough when I processed LROC images there was no such error.

**How to reproduce**  
See Description.

**Comment by acpaquette** [comment]
Hello! Could you provide the HRSC image you were running `spiceinit` against?

**Comment by hard2namegit** [comment]
> Hello! Could you provide the HRSC image you were running `spiceinit` against?

I have tried to process about ten HRSC images, such as HJ029_0000_P12.IMG. So I am considering if this is some problems with SPICE's support for HRSC, after all, there is no such error with LROC images.

**Comment by lwellerastro** [comment]
Hi @acpaquette, I downloaded a tested the above mentioned file to my work area under Isis3Tests/Spiceinit/MEX/.  Spiceinit runs successfully pointing to the local and efs data areas.  

When I tried `spiceinit from=HJ029_0000_P12.cub web=true` I got the following error:
```
  Group = Error
    Program = spiceinit
    Code    = 1
    Message = "The Spice Server was unable to initialize the cube.  The error
               reported was: Unable to initialize camera model"
    File    = SpiceClient.cpp
    Line    = 588
  End_Group
```

All tests were under isis8.0.0-RC1.

**Comment by amystamile-usgs** [comment]
HRSC is unique in that it requires reading line scan times. To access these times, the camera model must read from the cube's data. When using the spice server (web=true), we have the problem that the spice server only returns the label resulting in the camera model failing. 

A solution could be to pass in the times into the label but making this change could cause significant API breaking changes, especially since we are making modifications to the label. A somewhat simple fix is to not using web=true and disabling the use of the spice server for all HRSC images. The only frustrating part of this is having to download the MEX data locally.

We are in the process of changing how the spice server operates and this specific issue would be handled once this implementation is complete. So I am not sure it's worth making any changes to the HRSC label. 

Therefore my suggestion would be to download the data locally by running `./downloadIsisData mex $ISISDATA` and then run `spiceinit from=HJ029_0000_P12.cub`. I will also temporarily disable the option to use web=true for HRSC images.

_Update:_ If using GUI, uncheck "Use the ISIS Spice Web Service".
