### ISSUE TITLE
ISIS 8.0.0 cubeit attribute error

### ISSUE THREAD

**Issue by rleishirise** [DOI-USGS/ISIS3#5234]
**ISIS version(s) affected**: 8.0.0 RC1

**Description**  
HiRISE testing of 8.0.0 RC1.

The tool cubeit is returning the following error in our anaglyph production pipeline when attempting to stack the left and right image cubes. The cubeit command line with the appended attribute "UnsignedByte" works in ISIS 6.0.0, the version of ISIS we currently use in regular production. I removed information about our servers and replaced with "<>".

Object = cubeit
   IsisVersion       = "8.0.0  | 2023-04-24"
   ProgramVersion    = 2018-11-19
   ProgramPath       = /apps/opt/anaconda/Linux.x86_64/envs/isis800/bin
   ExecutionDateTime = 2023-06-20T18:04:37
<>
   Description       = "Stacks individual cubes into one cube"
 
  Group = UserParameters
     FROMLIST = /tmp/ESP_020242_0945_ESP_020241_0945_RED.<>.list.lis
     TO       = /tmp/ESP_020242_0945_ESP_020241_0945_RED.<>.cubeit.-
                cub+UnsignedByte+1:254
  End_Group
 
   Group = Error
     Program = cubeit
    Code    = 1
    Message = "Attribute [UnsignedByte] is not recognized"
     File    = CubeAttribute.h
    Line    = 207
   End_Group
 End_Object
 End

**How to reproduce**  

% cubeit fromlist= /tmp/ESP_020242_0945_ESP_020241_0945_RED.<>.list.lis to= /tmp/ESP_020242_0945_ESP_020241_0945_RED.<>.cubeit.cub+UnsignedByte+1:254

**Possible Solution**  

**Additional context**  

Thank you,

Richard Leis
Operations Specialist & Downlink Lead
HiRISE Operations Center
Lunar & Planetary Laboratory
University of Arizona

**Comment by AustinSanders** [comment]
Hey @rleishirise,

Thanks for bringing this issue to our attention.  I've verified on my end, and it looks like this problem is not unique to cubeit -- I'm not able to set any cube attributes for any program that I've tested (with the exception of cubeatt).

I'll begin looking into this.  Oddly, it looks like directly using cubeatt results in the proper behavior, and adding an explicit cubeatt call to your pipeline may serve as a workaround while we're fixing inline attribution specification for other apps.

This would look like
```
cubeit fromlist= /tmp/ESP_020242_0945_ESP_020241_0945_RED.<>.list.lis to= /tmp/ESP_020242_0945_ESP_020241_0945_RED.<>.cubeit.cub
cubeatt from=/tmp/ESP_020242_0945_ESP_020241_0945_RED.<>.cubeit.cub to= /tmp/ESP_020242_0945_ESP_020241_0945_RED.<>.cubeit.cub+UnsignedByte+1:254
```

I'll keep this thread updated as I make progress
