### ISSUE TITLE
Stuck on "Solving environment : \ " when Installing ISIS

### ISSUE THREAD

**Issue by alexwuttig** [DOI-USGS/ISIS3#5244]
I am having trouble installing ISIS on my M2 Macbook(Mac OS: Ventura 13.5) and on a separate Linux computer running CentOS(Version 7) Given that I am generally new to coding I am having issues troubleshooting. I can set up the isis environment with the correct channels, but when I attempt to run "conda install -c usgs-astrogeology isis" it gets stuck on "Solving environment: \". I even left the Linux computer running for at least 12 hours and it was still there when I came back. On my mac, the same thing happened, following the  MacOS ARM64 specific instructions. The following is a screenshot of when I tried to use Mamba instead of Conda. What am I doing wrong?

 <img width="407" alt="Mamba time" src="https://github.com/DOI-USGS/ISIS3/assets/140654207/1511b0e4-2d12-4804-80e4-83277c7a7d71">
</div>

This is with xQuartz:
<img width="573" alt="Screenshot 2023-07-27 at 12 51 16 PM" src="https://github.com/DOI-USGS/ISIS3/assets/140654207/13c6f5cc-e159-46b0-8e5f-85adba1156c5">

**Comment by djkurlander** [comment]
I have the exact same problem trying to install on Linux.

The "conda install -c usus-astrogeology isis" command first tries to solve the environment using the "current_repodata.json" repository, and it fails. Then it tries to solve the environment using "repodata.json" instead, and hangs on "Solving Environment". I have tried this multiple times, and it always fails at the same step. See the picture below. I followed the installation instructions from the github page very closely. This seems to be a problem that multiple people are currently having. Is there any solution? Please help!

Thank you!

![SolvingFrozen](https://github.com/DOI-USGS/ISIS3/assets/85320037/dc5f78f4-8522-404b-be0a-336286dfc2b1)

**Comment by volcanopele** [comment]
Adding that I am having the same issue on my MBP with Apple Silicon M2. Installation gets stuck at the same "Solving Environment: /" step. This seemed to be an issue late last week when I tried to update my installation on my old laptop.

**Comment by lwellerastro** [comment]
Hi - not an expert, just a user who normally doesn't need to install isis (I'm with Astro and we have it locally, but sometimes there are problems) but had success installing the latest version 8.0.0_RC2.  I've tried past versions (including the default 7.2.0) and have had similar problems to what you all document, but this latest version worked for me, so if you're willing you might give it a try.

I installed it on a linux using the following command:
`conda install -c "usgs-astrogeology/label/RC" isis=8.0.0_RC2`

One of local devs pointed out this [site](https://anaconda.org/usgs-astrogeology/isis/labels) and how they often started there to ask for installs in case documentation has differences or otherwise don't make mention of other version.

I hope this helps, but I understand why you might not want to work in a release candidate, however I do most of my work in the latest versions since that's where bugs that I often identify are addressed. Good luck!

**Comment by volcanopele** [comment]
thank you for the comment! this worked for me.

**Comment by AustinSanders** [comment]
I'm currently working on getting ISIS 8.0.0 out as a full release.  For now, users should use the syntax that @lwellerastro offered in the comment above.  Following the release, users should be able to use the simpler syntax referenced in the installation instructions.

**Comment by alexwuttig** [comment]
Thank you so much! I was able to get it installed on both my M2 Macbook and Linux computer.

**Comment by lwellerastro** [comment]
I'm really glad that command helped!  Thanks to @amystamile-usgs who helped me in the same way a few months ago when I was stuck.

**Comment by acpaquette** [comment]
@AlexBankss Seems like this issue can be closed?

**Comment by djkurlander** [comment]
@lwellerastro - Thank you as well. Your solution solved my installation problem too.

@AlexBankss - I think this can be closed.
