### ISSUE TITLE
Unable to configure environment variables

### ISSUE THREAD

**Issue by FlashRisk** [DOI-USGS/ISIS3#5251]
I just installed ISIS(version 8.0.0) on my Linux computer but I can't seem to get either method for configuring the environment variables to work. I tried it with conda env config vars(my conda version is 23.7.0) and with the provided isisVarInit.py script. Both resulted in the error "bash: export: 'ISISROOT+home/usr/miniconda3/envs/isis=': not a valid identifier". I got this error after I tried to reactivate isis. Any help would be greatly appreciated.

**Comment by acpaquette** [comment]
After some exploration this seems to be due to using the `conda env config vars set ISISROOT=$CONDA_PREFIX ISISDATA=/Path/to/data` but inserting a + between ISISROOT and the CONDA_PREFIX when setting the variable.

To correct the env state, remove the `$CONDA_PREFIX/conda-meta/state` file. Then you should be able to try set the variable again.

**Comment by FlashRisk** [comment]
This worked for me. I must have typed it incorrectly the first time which messed up the rest of my attempts. Thank you for the help!
