### ISSUE TITLE
Is there any way to get the metadata for "each row" of the LRO NAC image?

### ISSUE THREAD

**Issue by huigeonkim** [DOI-USGS/ISIS3#5286]
Hi, thanks for sharing and advancing your excellent work, and I have a question.

Is there any way to get the metadata for "each row" of the LRO NAC image?

I'm trying to get the metadata for each row of an LRO NAC pushbroom image.

Due to the nature of push broom imaging, it creates a long image from top to bottom and in the case of LRO NAC, requires an exposure time of about 30 seconds.

The relative positions of the spacecraft and the sun are constantly changing during these 30 seconds. I was wondering if there is any metadata that contains the exact position of the spacecraft and the sun when each row of pixels is taken, and if so, what function can be used to extract it.

The way I've envisioned it so far is to find the start and end time of the image acquisition, divide the time taken by the number of pixel rows, and multiply by the time interval per row, but that's an 'estimate' and not 'ground truth', so I'd like to know the exact 'ground truth' via metadata.

I appreciate the work you guys are doing to move the community forward, and I'd appreciate a response.

**Comment by acpaquette** [comment]
@huigeonkim It seems like your best bet might be accessing the spice data directly through something like [spiceypy](https://github.com/AndrewAnnex/SpiceyPy).

It's easier than the C library and can provide ground points, granted the C library still extrapolates if you request a time in between records. in the spice information.

Realistically this would be likely need to be an extra tool. In ISIS we get the exact instrument orientation at each record in the kernel. For instrument position we get each line in the image then, usually, we create a hermite spline over the positions. If you interrogate the `InstrumentPointing` Table on a given LRO NAC cube, that will get you exact times that spice records were recorded for the orientation information. To get that info use `TableDump from=/Path/to/LRONAC.cub name=InstrumentPointing to=output.txt`

Getting exact records is tricky because you have to subvert the C library and interrogate the kernels rigorously to find the exact records.

What are you trying to accomplish from getting the exact records?
