### ISSUE TITLE
QVIEW Does Not Report Cube's Full Dynamic Range

### ISSUE THREAD

**Issue by astrostu** [DOI-USGS/ISIS3#5289]
**ISIS version(s) affected**: all

**Description**  
Using QVIEW's Stretch tool, clicking the "Advanced" button, and then moving the sliders on the min to the far left and max to the far right, one would expect the entire dynamic range to be displayed and those values properly reported in the min/max boxes.  However, based on ISIS2STD output stretch (0–100) or looking at the raw values when using ISIS2ASCII, the QVIEW-reported values are clipped in some way by up to a few percent.

I can think of two possible reasons this might be:  (1) a bug; (2) could it be that when this functionality was first included, for CPU/RAM issues, only a certain percentage of the pixels are included in the histogram?  ArcMap used (might still?) to do this, but it explicitly said that it was only incorporating some and not all values in the histogram.

**How to reproduce**  
See above.

**Additional context**  
Individuals using QVIEW to try to understand the full dynamic range of their cubes must use it with caution and should use a secondary tool tool to verify.

**Comment by astrostu** [comment]
I will bump this given that it can be misleading to researchers and result in false data/results.  And because it looks like @chkim-usgs indicated it was added to a support sprint 5 months ago -- did it get solved?

**Comment by chkim-usgs** [comment]
Hi @astrostu, this issue was added to the previous support sprint but has not been addressed yet. We will bump this issue to the upcoming sprint and encourage anyone who would like to advocate for their issue to attend the upcoming sprint prioritization meeting on Monday, March 11. Thanks!

**Comment by astrostu** [comment]
I'd advocate for it to be investigated/fixed, but March 11 = LPSC so I can't.

**Comment by chkim-usgs** [comment]
Hi @astrostu, there is now a new feature in QVIEW's Stretch tool that allows min/max type selection, as per PR #5455. For now, you can check out the `dev` branch to try it out as this feature will be included in a future release later on. Let us know if you have further questions or comments. If not, we can close this issue.

**Comment by astrostu** [comment]
Thanks, @chkim-usgs .  I've been getting the updates via email and am glad that you've been able to address this.  I thought it interesting that QVIEW was using Chebyshev-based values.  Certainly explains why it was different from the absolute min/max.

**Comment by lwellerastro** [comment]
Hi - I'm testing the updates made to the qview stretch tool (isis8.2.0.-RC1, locally) and really like the drop down menu selection. Nice addition!

However, while toggling through the three options, I have found that I can't really go back to the "Best" min/max values via the menu after loading the other options. For instance, after opening an image, I can successfully get new/different min/max values when I select Absolute then Chebyshev, but once I've selected either one of those, Best always uses Absolute. I can get back to Best/default stretch values if I use the shortcut Ctrl-R (reset), but these may cause confusion because if Absolute or Chebyshev is loaded in the drop down menu, then the global/default values are displayed in the min/max boxes, not the actual min/max values associated with those menu options.

Please let me know if this should be a new post and if you need any data to use for refining. (I also don't have the option to re-open this post.)

**Comment by chkim-usgs** [comment]
Hi @lwellerastro, thanks for testing out the new addition and reporting this bug. Found that the default min/max values were different from the Best values since they are actually 0.5/99.5 percentile values, respectively, and added that preset as the `Default` option. There is a PR open with these changes if you would like to test out the fix: https://github.com/DOI-USGS/ISIS3/pull/5492. Let me know if there's anything else in regards to this issue!

**Comment by AustinSanders** [comment]
Closed via #5492
