### ISSUE TITLE
Dependency Updates - GEOS, then trickle on

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ISIS3#5336]
**Description**  

The ISIS dependencies are beginning to be out of date enough as to be problematic when installing ISIS with other planetary science applications (e.g., ASP).

Currently, we are working to get PDAL2.6+ integrated into ASP. ASP depends on ISIS. Therefore the older ISIS dependencies are causing issues.

Specifically, the following packages need an update:
- GEOS / GDAL to 3.12

Updating that then requires looser pinning or updates to (at least):
- Boost
- QT
- OpenCV
- Protobuf

**Comment by acpaquette** [comment]
Something to note is that this will fast forward our MacOS support to 10.9 (released October 22, 2013) and up, I don't think it will be a problem but something to note. We would also update glibc to 2.17 still supporting Ubuntu 14 but may drop other Linux systems

**Comment by jlaura** [comment]
@acpaquette That sounds like a net positive?

Here are the [EOL dates for OS X](https://endoflife.date/macos). 10.9 service updates ended 10/1/2016. I look at ubuntu, but I suspect most OSes are in a similar place.

**Comment by acpaquette** [comment]
I tried creating an environment to see what else may need to updated and it seems like we can just updated geos to 3.12 without having to update the rest. What version of the other dependencies would be useful to update to?

**Comment by jlaura** [comment]
@oleg-alexandrov  Are you able to weigh in here? I am not 100% sure what the dependency update tree looks like for PDAL beyond what I posted.

**Comment by oleg-alexandrov** [comment]
As I recall, PDAL also needs recent versions of libxml2, GDAL, and tiledb. GDAL seems to need a newer boost. Otherwise I was getting a lot of conflicts.

The sure way to avoid problems later is to create an environment with the conda PDAL 2.6 package and install all other dependencies around it. Especially tiledb is problematic, as PDAL 2.6 fails to compile with older versions of it.

**Comment by dshean** [comment]
https://pdal.io/en/2.6.0/development/compilation/dependencies.html

+1 for updating ASP/ISIS to more recent versions of GDAL and especially PROJ (hopefully 9+).  We need to the much improved coordinate reference system transformation support, which should improve planetary CRS support as well.

**Comment by oleg-alexandrov** [comment]
These are minimal dependencies, though. I've been using until now an approach where, due to ISIS being behind, I have to keep a handlful of custom-built conda packages that exist on conda-forge already, but are not compatible with ISIS.

With PDAL and tiledb, the list of custom packages I need to rebuild each time will just go up and and will get harder as other software moves forward.

I am not sure if it is feasible, but if ISIS has, by default, conda-level compatibility with PDAL and GDAL that will make it more convenient and easier for everybody.
