### ISSUE TITLE
Cnetthinner application aborts when computing point depth weight if point has no valid measures

### ISSUE THREAD

**Issue by kledmundson** [DOI-USGS/ISIS3#5354]
**Description**  

### Original description of the problem...

In OSIRIS-REx processing it was found that the cnetthinner application will abort when computing point depth weight if the point doesn't contain valid measures. This is caused by a BOOST ASSERT (abort) in the file CnetManager.cpp.

### A better description of the problem...

The calculateStrength method in CnetManager.cpp computes point strength as the sum of all the points' measures "goodness of fit" values divided by the number of measures with "goodness of fit" values.

Strength is not computed at all for points with less than two unignored measures, not including the reference measure.

If all unignored measures have no "goodness of fit" values, then  the strength computation results in a divide by zero. 
<br><br>
**Additional context**  

Possibly related to #4883?

**Comment by lwellerastro** [comment]
Yes, there is a very good chance that #4883 is failing because of problems in the network.  

Let's talk about what it means to be a valid measure. The network contains hundreds of single measure constrained points (based on lidar shots) that are not ignored, but I'm certain those are valid. However they do cause some problems when running cnetedit on the network forcing the user to safeguard them by running the program using preserve=true. If Free points end up with all measures set to ignore because they fail a ResidualMagnitude check after a run of jigsaw and preserve=true, then Free points may be left behind that only have a reference measure and one that is ignored (with valid safe guarded single measure constrained measures).

While trying to troubleshoot the particular network that caused the cnethinner failure I found there were numerous FREE points which only contained a reference image which happened to be ignored. Those points may be the cause of the cnetthinner failure.

I will identify those ignored single measure free points and remove them from the failing network and try rerunning cnetthinner again to see if works and report back here.

Thanks for post what you ran across @kledmundson

**Comment by kledmundson** [comment]
I'd love to take the credit, but actually it was @kbecker who discovered
this and implemented a fix in the UofA code. I should have put that in the
post.

I am simply the messenger.

**Comment by lwellerastro** [comment]
I simply ran cnetedit on the problem network to clean up ignored measures and points and cnetthinner now runs on it successfully (74G, 8.5 hours under isis8.0.1).

I'll add remarks to my original post. Not sure where the fix will come from though (internal or request for external to submit PR). Either way, mystery solved. Thanks!

**Comment by kledmundson** [comment]
@lwellerastro I am preparing to submit a PR for this with the app converted to a callable function and old Makefile tests converted to gtests as well.

**Comment by kledmundson** [comment]
@lwellerastro Based on my better understanding of the problem and the modified description above, now wondering if your success  after removing ignored points and measures is truly related to this or is a fluke. Probably the easiest way to sort it is to just run a test version (if possible) on your original network after the fix for this is submitted.
