### ISSUE TITLE
Point2dem error 

### ISSUE THREAD

**Issue by erikavrivera** [DOI-USGS/ISIS3#5386]
**ISIS version(s) affected**: 8.0.1

**Description**  
This is my first time using ISIS and ASP; and so far, I didn't encounter issues until I reached the last step of the DEM Generation which is the point2dem. DEM Generation stopped in the writing process when I include additional commands like --error image and --dem-hole--fill-len 20000 (I also tried 5000 but I still get the same error). If I only use the point2dem, the DEM generation is successful. Please see the screenshot below for context. Thanks!
![point2dem error](https://github.com/DOI-USGS/ISIS3/assets/154370736/b0cd6100-d883-45fc-abe1-2cf7e517ae0c)

**Comment by rbeyer** [comment]
So with `--dem-hole-fill-len 20000` you're asking `point2dem` if it finds any gaps in the terrain less than 20,000 pixels across, to attempt to use an algorithm to "fill in" that terrain with what we call an "in-painting" algorithm.  That's a lot of pixels, and thus a great deal of computation, and as the warning says "Memory usage and run-time may go up."  I suspect that what is happening here is that the process runs out of memory trying to compute these "fill-in" values as it is writing out the DEM, and that's the failure you're seeing.

This is NOT a bug, this is a natural consequence of you asking `point2dem` to do something it really isn't designed to do, hence it trying to warn you about it.  In general, the `--dem-hole-fill-len` is for filling in holes of tens to maybe a few hundred pixels across.  Holes larger than that should probably be left as gaps, because there isn't really enough information to reliably fill in the missing information.

If there are large gaps in the terrain, then perhaps you need to refine bundle adjustment or stereo generation parameters before you get to the `point2dem` stage in order to get a better set of matches.

**Comment by rbeyer** [comment]
More importantly, perhaps, is that `point2dem` is an ASP program, and not an ISIS program, so this Issue doesn't even really belong on this repo.

**Comment by erikavrivera** [comment]
Got it. Thanks so much!
