### ISSUE TITLE
gllssi2isis fails with GO-J/JSA-SSI-2-REDR-V1.1 data

### ISSUE THREAD

**Issue by sschmaus** [DOI-USGS/ISIS3#5396]
**ISIS version(s) affected**: 8.0.2

**Description**  
when trying to convert Galileo SSI images downloaded from Opus, I run into the following error:
```
gllssi2isis from=C0349746326R.LBL to=./work/__G1I0012_raw.cub
**ERROR** Unable to read [DATA_SET_ID] from input file [C0349746326R.LBL].
```
The field 'DATA_SET_ID' is available in the label though.

**How to reproduce**  
run this command on Galileo images from Opus, e.g.: https://opus.pds-rings.seti.org/opus/#/view=detail&detail=go-ssi-c0349746326
`gllssi2isis from=C0349746326R.LBL to=./work/__G1I0012_raw.cub`

**Possible Solution**  

**Additional context**  
changing the value of 'DATA_SET_ID' in the label from 'GO-J/JSA-SSI-2-REDR-V1.1' to 'GO-J/JSA-SSI-2-REDR-V1.0' (decrease in minor version) the process executes fine and I was able to process the data.

**Comment by lwellerastro** [comment]
I confirmed that the OPUS downloaded image can not be ingested via gllssi2isis because the program expects 
DATA_SET_ID = "GO-J/JSA-SSI-2-REDR-V1.0" and the OPUS served file has V.1.1 as the OP indicates.

Data from the [PDS](https://planetarydata.jpl.nasa.gov/img/data/go-j_jsa-ssi-2-redr-v1.0/go_0017/g1/io/c034974/6326r.img) can be successfully ingested because they have the expected DATA_SET_ID. In order to ingest the OPUS data we need to consider being able to read V1.1 data. As the OP pointed out, simply making that change to his OPUS image label allowed for it to be ingested, so it could be an easy fix (in theory).

Data is available under my user work area:
PDS download:  /Isis3Tests/Gllssi2isis/Git5396/6326r.lbl and 6326r.img
(see proc.scr for data urls and other notes)

OPUS download:  /Isis3Tests/Gllssi2isis/Git5396/OpusArchive/C0349746326R.LBL and C0349746326R.IMG
