### ISSUE TITLE
Issues running tgocassis2isis on PSA compliant data

### ISSUE THREAD

**Issue by AustinSanders** [DOI-USGS/ISIS3#5413]
**ISIS version(s) affected**: 8.0.2

**Description**  
From comments on #4631 :

I am also having problems using tgocassis2isis to import PSA CaSSIS data:

tgocassis2isis from=cas_raw_sc_2023074T223427-2023074T223431-25038-37-NIR-1125020420-29-2.xml to=123.cub
USER ERROR Given file [cas_raw_sc_2023074T223427-2023074T223431-25038-37-NIR-1125020420-29-2.xml] does not appear to be a valid TGO CaSSIS label.
ERROR Failed to translate output value for [CoreSamples].
ERROR Failed traversing input position. [InputPosition] element does not have a child element named [Array_3D_Image].

I want to know how to reslove this issue

**How to reproduce**  
run `tgocassis2isis from=cas_raw_sc_2023074T223427-2023074T223431-25038-37-NIR-1125020420-29-2.xml to=123.cub`

**Possible Solution**  
Update translation files?

**Additional context**  
Data can be downloaded from https://psa.esa.int/psa/#/pages/search or https://archives.esac.esa.int/psa/ftp/ExoMars2016/em16_tgo_cas/browse_raw/.

**Comment by AustinSanders** [comment]
@wang-github-240118 I created this issue on your behalf to track the issue you reported on #4631.  To help us address this issue, please provide the version of ISIS that you are using.  Also, a link to download the data that you are using would be very helpful.

**Comment by wang-github-240118** [comment]
My isis version is 8.0.2,and I download the data from https://psa.esa.int/psa/#/pages/search or https://archives.esac.esa.int/psa/ftp/ExoMars2016/em16_tgo_cas/browse_raw/.

**Comment by amystamile-usgs** [comment]
Looking through the provided data, these are all .png images. tgocassis2isis only works with .img or .dat images. What's strange is that the application is not throwing this error but rather getting to the translation before failing. But I am also seeing the same errors with .dat files from here: https://archives.esac.esa.int/psa/ftp/ExoMars2016/em16_tgo_cas/data_raw/Near_Earth_Commissioning/Science/50399184/PAN/. 

So seems like two issues are happening.

**Comment by amystamile-usgs** [comment]
@wang-github-240118 Upon inspection of the images you attempted to process using `tgocassis2isis`, it was discovered that the `cas_raw_sc` labels lack essential information necessary for image processing. This includes the filter name, exposure duration, and the unique identifier. Consequently, `tgocassis2isis` cannot support these specific images.

I have implemented fixes to handle the ingestion of `cas_cal_sc` images and have also included error detection for attempting to ingest XML files lacking a .dat or .img data file.

Once these modifications are incorporated into the next version of ISIS, we recommend processing PDS data from https://archives.esac.esa.int/psa/ftp/ExoMars2016/em16_tgo_cas/data_calibrated/ instead of utilizing the "browse" data or the raw data.
