### ISSUE TITLE
Isisminer does not properly handle the presence of bad (e.g. self-intersecting) polygons.

### ISSUE THREAD

**Issue by kledmundson** [DOI-USGS/ISIS3#5612]
**ISIS version(s) affected**: x.y.z
dev

**Description**  

The _footprintinit_ application will sometimes create invalid, self-intersecting polygons. The _isisminer_ application detects bad polygons, reports them, and terminates instead of attempting to repair them. 

**Solution**  

In many cases, self-intersecting polygons can be repaired by creating a buffer of size 0 around the polygon. This is analogous to stretching a rubber band around all points in the polygon (see slide below). The buffer(0) approach will likely fix many (though possibly not all) self-intersecting polygons. While the fix should be incorporated into _footprintinit_, it should also be implemented in _isisminer_. 

**Additional context**  

The slide below shows a polygon with a highlighted self-intersection in blue. The self-intersection was repaired (shown in orange) by applying a buffer of 0.1 around all polygon vertices. Note that typically a buffer of size 0 is applied. Here, a buffer of 0.1 was used for illustration purposes only. 

<img width="1331" alt="selfIntersectingPolygons" src="https://github.com/user-attachments/assets/269712bb-1df7-4bf3-81f3-750089de63cb">

**Comment by acpaquette** [comment]
@kledmundson Couple insights/questions. Is there a planned fix from the yourself or Kris coming in for this? Second, is seems related to #5553

**Comment by kledmundson** [comment]
Yes, fix is coming.

Relation to #5553 I'm not sure about, will have to look.

**Comment by KrisBecker** [comment]
This fix is not directly related to #5553 because [GisGeometry](https://github.com/DOI-USGS/ISIS3/blob/dev/isis/src/base/objs/GisGeometry/GisGeometry.h) uses the GEOS C-API. Code in [PolygonTools](https://github.com/DOI-USGS/ISIS3/pull/5553/files) uses the C++ API so they are separate. We added a `buffer()` method to GisGeometry.

They are likely related as some GIsFootprints created by ISIS have self-intersections. These *leak* through into isisminer processing and aborts the run. The fix that @kledmundson is providing runs a `buffer( 0 )` on the whole polygon in an attempt to fix them. Most all occurrences are fixed using this technique.

**Comment by kledmundson** [comment]
Closed via https://github.com/DOI-USGS/ISIS3/pull/5620.
